### ISSUE TITLE
installation systemd

### ISSUE THREAD

**Issue by tschinz** [sentriz/gonic#100]
Hello,

I'm searching for a long time a suitable alternative to sub/madsonic. This seems to be my solutions. But I can't get it to work. I have an Ubuntu 18.04 Server and installed it as written  ...with systemd.
When I load up http://localhost:4747 is is redirected to http://localhost:4747/gonic/admin/home and I get an 404 page not found error.

With iSub or play:sub I can't get it to work either. Anyone some troubleshooting ideas. Im unfortunately unfamiliar with golang and havent found any tutorial for gonic online.

Help is appreciated

/tschinz

**Comment by sentriz** [comment]
hey. have you started gonic with the `-proxy-prefix` flag?

**Comment by tschinz** [comment]
yes since it was there by default in the config file. Is there any additional configuration necessary

**Comment by sentriz** [comment]
hm maybe you could try delete the `proxy-prefix      /gonic` line from the config and restart the service?

**Comment by tschinz** [comment]
This i’ve tried without luck. Is there any way to debug the problem?

**Comment by sentriz** [comment]
hey thanks for the report. please check out #101 where we can continue
