### ISSUE TITLE
arch installation problems

### ISSUE THREAD

**Issue by hildebro** [sentriz/gonic#101]
I'm having trouble getting gonic to run on my server.

1) install gonic AUR package
2) add my music directory to `/var/lib/gonic/config`
3) ensure gonic user has access to music directory
4) start systemd unit
5) ssh tunnel to local machine

When I open `localhost:4747` on local machine, the url turns into `localhost:4747/gonic/admin/login`, so the systemd unit is actually running in some capacity and my tunnel also works. However, my browser just displays `404 page not found`. Checking the log via `journalctl` doesn't display any errors:
```
gonic[408]: 2020/12/09 13:24:24     db-path         /var/lib/gonic/gonic.db
gonic[408]: 2020/12/09 13:24:24     jukebox-enabled false
gonic[408]: 2020/12/09 13:24:24     listen-addr     127.0.0.1:4747
gonic[408]: 2020/12/09 13:24:24     music-path      /root/music
gonic[408]: 2020/12/09 13:24:24     proxy-prefix    /gonic
gonic[408]: 2020/12/09 13:24:24     scan-interval   0
gonic[408]: 2020/12/09 13:24:24     version         false
gonic[408]: 2020/12/09 13:24:24 starting job 'session clean'
gonic[408]: 2020/12/09 13:24:24 starting job 'http'
```

If I arbitrarily modify the url (i.e. `http://localhost:4747/foobar`), the url isn't modified, but `404 page not found` still shows up and nothing happens in the systemd log. The only exception: When I change the url to `http://localhost:4747/admin/login` it turns into `/gonic/admin/login` with the following log message
```
gonic[408]: 2020/12/09 13:39:28 response  303  for `/admin/home`
```

I also tried a reverse proxy with caddy to interact with gonic, but the behavior in the browser is the same. Furthermore, if I change proxy-prefix to anything else (i.e. `/foorbar`, `0`, `false` or just remove the line from config file), the systemd log does show the value I specified, but `/gonic` is still added to the url in all cases.

**Comment by sentriz** [comment]
ah strange. the issue could be that the redirection from `/` -> `/admin/home` is a HTTP 301 "moved permanently" which browsers cache. i just updated that

could you please try
1. get the latest commit `go get -u go.senan.xyz/gonic/cmd/gonic`
1. remove the proxy-prefix line from the config
1. restart the systemd service
1. clear your browser's cache to clear the 301 redirect caching
1. try again visiting `localhost:4747`

thanks!

**Comment by hildebro** [comment]
Problem fixed, thanks
