### ISSUE TITLE
support multiple artists

### ISSUE THREAD

**Issue by raffomania** [sentriz/gonic#103]
If a track is a collaboration between multiple artists, gonic should be able to associate it with all of them in the DB - this would mean changing `Track.Artist` to `Track.Artists`, a many-to-many relationship. I can understand if this is too much work for you, but it would be really cool to remove "Artist X, Artist Y" entries from my artist list :)

If the subsonic API doesn't support this, you could just join the artist names again when delivering metadata to clients.

**Comment by sentriz** [comment]
not a bad idea 👍  i'm currently working on multiple genre support. so it would be a very similar setup

**Comment by raffomania** [comment]
awesome! love gonic so far, thanks a bunch for putting in all that hard work!

**Comment by hildebro** [comment]
Hey @sentriz,

I noticed that multiple genres support has been added on master some time ago. Since you mentioned it being similar to multiple artists, do you have any estimation on when we might see that?

Furthermore, when might we see both of these features released via AUR?

Thanks for your work!

**Comment by sentriz** [comment]
hey thanks for the nice words :)

the current priority is #108 , when that is merged i'll make a new release including some scanner fixes, listenbrainz, and podcasts support

after that i can consider multiple artists. hopefully it won't be too far away since it's something i'd like to use myself

**Comment by TwistTheNeil** [comment]
In a similar situation (unless this issue captures it already), if there are multiple artists, gonic seems to index a song with the last artist in the list which can be incorrect.

Example:
```
METADATA block #2
  type: 4 (VORBIS_COMMENT)
  comments: 17
    comment[0]: ALBUM=Death by Rock and Roll
    comment[1]: ARTIST=The Pretty Reckless
    comment[2]: ARTIST=Tom Morello
...
    comment[11]: TITLE=And So It Went (featuring Tom Morello)
```

The artist is `The Pretty Reckless` but is registered as `Tom Morello`

**Comment by sentriz** [comment]
Hello just as a small update I am still very into this. For me, implementing this make sense after beets implements this:

https://github.com/beetbox/beets/issues/1824

After that I think it could be a really nice feature

**Comment by sentriz** [comment]
this is getting close on the beets side by the look of things https://github.com/beetbox/beets/pull/4743

also there is a discussion about how the subsonic spec could be extended to better support this stuff here https://github.com/opensubsonic/open-subsonic-api/discussions/8

**Comment by jmbannon** [comment]
Any ideas for timeline on when you think multi-artist tags would be supported? I've been dreaming of a subsonic server that handles this for years.

One idea I've had on my mind for a while is tricking the current subsonic API to support multi-tags via serving albums/tracks/etc based on multi tags. I.e. GET artists/ would return all unique values in all artists multi tags. Then when you select an artist, you serve all albums/tracks that contain that artist in the multi-value. In addition, have support to either use `artists` or `albumartists`

**Comment by sentriz** [comment]
@jmbannon no timeline, but this is something that i would very much like too. i have started working on some of it already

and what you described is close to what i had in mind

just thinking out loud here:

if we we're to consider a sql schema, it could be a be many-to-many situation

```sql
create table artists (id int, name text);
create table albums (id int, name text);
create table artist_albums (artist_id int, album_id int);
```

so for an album [Sniper by Alan Vega & Marc Hurtado](https://musicbrainz.org/release-group/95469885-a4de-4192-b7b7-d13d9a445cf1) we could have

```
artists:
- id=1 name="Alan Vega"
- id=2 name="Marc Hurtado"

albums:
- id=1 name="Sniper"

artist_albums:
- artist_id=1 album_id=1
- artist_id=2 album_id=1
```

here a "get artists" query lists all unique artists, like you said. a get an artist's albums query works like you'd expect too. 

this is all possible to do right now (and thanks to your beets PR :+1:) but the only bit i'm not sure, where maybe some actual tricking may need to be done is -

what artist do we show to the user when we click the album that has id 1? we need to put some single value in the "albumartistid" field in the response. of course this is not an issue when we have the multi "albumartistids" field as described in that opensubsonic issue. but for clients that don't support it we need some value

**Comment by jmbannon** [comment]
> what artist do we show to the user when we click the album that has id 1?

Is that used for navigation or just display? I think the best approach would be to return the single id of whichever artist you clicked on to find it in the first place. If searching by album, you could just naively place the first album artist in there for now

**Comment by sentriz** [comment]
not just navigation or display but the whole data model. for example if a client makes the request getAlbum.view?id=1, we need to return some json that describes that album. one of the fields is a single artist ID, but we have 2 of them. with the extension we can return both, but for the current spec just 1.

that said, this is only for the schema that i described above - maybe there is a smarter way. not sure yet

for the meantime i will probably just pick a random artist ID or the first one that appears in the tags

**Comment by jmbannon** [comment]
Got it, yeah makes sense to have it map to all album artists behind the scenes, and the for current subsonic compatibility, just return the first one.

From what I've seen, the album artist ordering often reflects order of contribution to the album. Returning the first one would be best IMO

**Comment by sentriz** [comment]
things cooking up on the (experimental) multi-artist branch and a couple changes to airsonic-refix

[out.webm](https://github.com/sentriz/gonic/assets/6832539/88a5f7e3-fc74-4849-8b73-3d7379a4ce46)

**Comment by sentriz** [comment]
hey, this can now be confuired with GONIC_MULTI_VALUE_ALBUM_ARTIST

for example in my setup i have

```
GONIC_MULTI_VALUE_ALBUM_ARTIST="multi"
GONIC_MULTI_VALUE_GENRE="delim ;"
```

**Comment by jmbannon** [comment]
Amazing! Does genre support 'multi' ?

**Comment by sentriz** [comment]
jmbannon yes it does 👍 though I haven't tried it yet. I've only been testing albumartists so far, thanks to your work on beets 👌

**Comment by sentriz** [comment]
also, if your tags already had the multi value tags before gonic last saw them, youll need to do a full scan

**Comment by afontenot** [comment]
I'm failing to get this to work. Testing with a fresh gonic setup and airsonic-refix, I have the following in my config file:

    multi-value-album-artist    multi

I'm using [this album / track](https://musicbrainz.org/release/4fe47c20-dac2-495f-9c46-90434babac5b/disc/1#3e135c71-3d9f-42ad-b2c5-c4be6415fd2e) for testing. It's tagged with Picard using additional scripts I wrote to make sure the multi value tags are set correctly.

mutagen-inspect reports this

```
$ mutagen-inspect 01\ -\ There\'s\ No\ Leaving\ Now.flac | grep ARTISTS
ALBUMARTISTS=The Tallest Man on Earth
ALBUMARTISTS=yMusic
ARTISTS=The Tallest Man on Earth
ARTISTS=yMusic
ALBUMARTISTSORT=Tallest Man on Earth, The; yMusic
ARTISTSORT=Tallest Man on Earth, The; yMusic
```

full report: [mutagen-inspect.txt](https://github.com/sentriz/gonic/files/12569875/mutagen-inspect.txt)

But in airsonic-refix, I see only the first artist in the part of the UI where each is individually clickable in your example video.

These files work in both Kodi and QuodLibet, which both support multi-valued tags. Maybe my tags contain something that is tripping up the new code in gonic?

Incidentally, if anyone knows a subsonic API client for web (or desktop Linux) that supports both this multiple artists feature and jukebox mode, I'd love to hear about it.

**Comment by sentriz** [comment]
> But in airsonic-refix, I see only the first artist in the part of the UI where each is individually clickable in your example video.

that's right, it's a new feature of the subsonic spec so not all clients support it

there is discussion ongoing [here](https://github.com/opensubsonic/open-subsonic-api/discussions/8#discussioncomment-6960805)

for refix, I opened a pull request to make that work [here](https://github.com/tamland/airsonic-refix/pull/115)

**Comment by afontenot** [comment]
> > But in airsonic-refix, I see only the first artist in the part of the UI where each is individually clickable in your example video.
> 
> that's right, it's a new feature of the subsonic spec so not all clients support it just yet

Of course it would be something dumb like this on my part. :-) Thanks for working on this.

**Comment by sentriz** [comment]
no worries :grin: thanks!
