### ISSUE TITLE
support semver docker image tags

### ISSUE THREAD

**Issue by onedr0p** [sentriz/gonic#111]
Hi! Thanks for the project, looks amazing. I would like to request that building the Docker image and tagging the images with the release version. Using `:latest` is usually frowned upon.

Maybe update the github workflow? I wrote a go app and do it [this](https://github.com/onedr0p/exportarr/blob/master/.github/workflows/main.yml) way.

Thanks!

**Comment by sentriz** [comment]
hey

the builds are configured on dockerhub's UI and updated them recently

![image](https://user-images.githubusercontent.com/6832539/105608851-57d8b280-5d9d-11eb-878f-8ed3bebe3d4c.png)

if I'm understanding them right, it will only build an image when a new tag is created, create a image tag with the latest semver tag, and point :latest to the latest semver tag too

what are your thoughts on this?

**Comment by onedr0p** [comment]
I think it might be better to use Github actions to build the images. You have much more control.

**Comment by onedr0p** [comment]
See https://github.com/sentriz/gonic/pull/112

**Comment by sentriz** [comment]
:ok: :ok:
