### ISSUE TITLE
Transcoding on FreeBSD

### ISSUE THREAD

**Issue by kisscool** [sentriz/gonic#113]
Transcoding doesn't work on FreeBSD.
After some investigation I found the culprit : in server/encode/encode.go the ffmpegPath is assumed to always be "/usr/bin/ffmpeg", which is true on most Linux distributions but no on FreeBSD (and probably other OSs).

The correct path for FreeBSD is /usr/local/bin/ffmpeg

Edit : after doing a temporary "ln -s /usr/local/bin/ffmpeg /usr/bin/ffmpeg" on my system, the transcoding works fine.

**Comment by sentriz** [comment]
thanks! should hopefully be fixed now on master
