### ISSUE TITLE
Missing 2nd argument for TZ in Dockerfile

### ISSUE THREAD

**Issue by zesoft23** [sentriz/gonic#114]
Hey folks,

I'm trying to build locally to get the latest gonic file for my raspberry pi. I got this error when running `docker build .`

```
jack@tomato:~/Documents/gonic$ docker build .
Sending build context to Docker daemon   2.16MB
Error response from daemon: failed to parse Dockerfile: ENV must have two arguments
```

Line 31 in Dockerfile has just `ENV TZ` when it should have either an argument or a default value. Am I missing an instruction on how to build the docker image or is it actually incorrect? When I remove that line, everything seems to be just fine!

P.S. looking forward to the buildx/multiarch Github actions! Was previously using uGeek's image, but it's a few months out of date.

**Comment by sentriz** [comment]
should be fixed now :+1:
