### ISSUE TITLE
fix arm64 build

### ISSUE THREAD

**Issue by onedr0p** [sentriz/gonic#116]
There appears to be an issue with building gonic on arm64, maybe there are some build flags we are missing.

```
#31 [linux/arm64 builder 8/8] RUN ./_do_build_server
#31 sha256:7dee4ce9ba4d15c229ac93fab86b3ad3096f18fa20b5143823e9e09b0a738659
#31 ERROR: executor failed running [/dev/.buildkit_qemu_emulator /bin/sh -c ./_do_build_server]: exit code: 1

#19 [linux/amd64 builder 8/8] RUN ./_do_build_server
#19 sha256:8f973a5b9d08a01ff1a4b7ecfcb8401d8b1bfa345e38d2cc0c90a26939901b81
#19 CANCELED
------
 > [linux/arm64 builder 8/8] RUN ./_do_build_server:
------
Dockerfile:14
--------------------
  12 |     RUN go mod download
  13 |     COPY . .
  14 | >>> RUN ./_do_build_server
  15 |     
  16 |     FROM alpine:3.12.3
--------------------
error: failed to solve: rpc error: code = Unknown desc = executor failed running [/dev/.buildkit_qemu_emulator /bin/sh -c ./_do_build_server]: exit code: 1
Error: buildx call failed with: error: failed to solve: rpc error: code = Unknown desc = executor failed running [/dev/.buildkit_qemu_emulator /bin/sh -c ./_do_build_server]: exit code: 1
```

**Comment by sentriz** [comment]
seems like it's simple enough to do an arm64 build locally with qemu
```shell
$ docker run --rm --privileged docker/binfmt:a7996909642ee92942dcd6cff44b9b95f08dad64
$ docker buildx ls
default default  running ... linux/arm64 ...
$ docker buildx build --platform linux/arm64  .
```

however it's taking a long (!) time on my machine at least
![image](https://user-images.githubusercontent.com/6832539/106962144-8c058900-6736-11eb-8d60-7343c0b98bda.png)

and on the same step as the github action 
![image](https://user-images.githubusercontent.com/6832539/106962189-a3dd0d00-6736-11eb-8931-9e1811638786.png)

**Comment by onedr0p** [comment]
You might want to break out that `_do_build_server` script into each component of the build to see where it is failing in another branch and see what the errors in the GitHub workflow says.

**Comment by sentriz** [comment]
some success here, it seems like we were missing a github action step to set qemu. so added that here 
https://github.com/sentriz/gonic/commit/9049bfa6aafd878eaf6dd52dc9f646c2476d30de

then kicked off a manual image build 
https://github.com/sentriz/gonic/runs/1846093371?check_suite_focus=true

it's being going for 17 minutes now 😀
perhaps 4 platforms is a bit much

**Comment by sentriz** [comment]
success after 22m :+1:  :+1: 
![image](https://user-images.githubusercontent.com/6832539/107128266-4cfd4200-68b4-11eb-9130-d3c43d798b08.png)

i think next i'd like to try it on raspbian, and perhaps migrate the docs from @uGeek 's image to this "official" one

hey @uGeek what are your thoughts on this. is your arm image customised in anyway?

**Comment by onedr0p** [comment]
This is great success, good work!

**Comment by uGeek** [comment]
> éxito después de 22m +1 +1
> ![imagen ](https://user-images.githubusercontent.com/6832539/107128266-4cfd4200-68b4-11eb-9130-d3c43d798b08.png)
> 
> Creo que a continuación me gustaría probarlo en raspbian, y quizás migrar los documentos de la de imagen @uGeek a esta "oficial".
> 
> Hey @uGeek, ¿qué piensas sobre esto? ¿La imagen de tu brazo está personalizada de alguna manera?

I find it as a great idea!!!

So there is an official image for ARM.

I have tried it and in amd64 it works perfect, but in ARM it doesn't work.

Yesterday I built the image with the new changes. I used the old Dockerfile that was in the repository, the same one used to build the amd64 version and it works perfectly

**Comment by sentriz** [comment]
thanks @uGeek , I could reproduce this too with qemu. I updated the build action and booted up my old raspberry :+1: 

it's definitely working for me now
![20210209_192723](https://user-images.githubusercontent.com/6832539/107416974-05bdbe00-6b0d-11eb-87de-a662b4c7dbe9.png)

could you please confirm if you get the chance? thanks!

**Comment by sentriz** [comment]
closing for now, see above ^ 

docs are updated too
https://github.com/sentriz/gonic/commit/87cd30325748e86cb9ba12789e92740730d6cbba

thanks @uGeek for the original arm image :+1:

**Comment by onedr0p** [comment]
Awesome work!

**Comment by uGeek** [comment]
> thanks @uGeek , I could reproduce this too with qemu. Also I updated the build action and booted up my old raspberry +1
> 
> it's definitely working for me now
> ![20210209_192723](https://user-images.githubusercontent.com/6832539/107416974-05bdbe00-6b0d-11eb-87de-a662b4c7dbe9.png)
> 
> could you please confirm if you get the chance? thanks!

now runs perfectly 👍👏👏👏👏
