### ISSUE TITLE
 Podcast with Gonic

### ISSUE THREAD

**Issue by uGeek** [sentriz/gonic#117]
Great new functionality.

I had several doubts.

- Once subscribed to the podcasts, how is it updated?
- I have subscribed to 4 podcasts and it works perfect, but I have subscribed to mine and the episodes do not appear.
- Lastly, as a suggestion, it would be great to add an option to import podcast subscriptions from an .opml file

Thank you very much. Great job

My Feed: http://feeds.feedburner.com/uGeek
Yesterday I updated the docker ARM to the latest version

**Comment by lxea** [comment]
Hey uGeek, 

>     * Once subscribed to the podcasts, how is it updated?

gonic will automatically refresh all podcasts once every hour but it wont automatically download them.

>     * I have subscribed to 4 podcasts and it works perfect, but I have subscribed to mine and the episodes do not appear.

Sorry to hear that, I'll investigate and see if i can make a fix :) 

>     * Lastly, as a suggestion, it would be great to add an option to import podcast subscriptions from an .opml file

Good idea, I'll also look into this!

**Comment by uGeek** [comment]
I have done a new installation and I have not finished scanning all the music, to test the podcasts. I do not know if it has to do because they are not updated.

It could also be because I am using the docker that I have built, I will try the one from amd64.

DSub has an option to force the server to update, it seems that it works from the app, but it does not update me

**Comment by lxea** [comment]
Whats not updating for you? Are new episodes not appearing? 
#118 should fix the issue of episodes from your feed here not showing up http://feeds.feedburner.com/uGeek

There isnt a force scan option for podcasts except to use the one in dsub/timer

**Comment by uGeek** [comment]
I have mounted the sentriz/gonic docker for amd64, from the previous comment and it takes more than 2 hours and it does not update me. 
I have subscribed to a Radio podcast. In AntennaPod and new episodes arrive and not in the Gonic server

**Comment by lxea** [comment]
Oh weird, do you mind sharing the url with me, i'll try test it and see if i can fix it

**Comment by uGeek** [comment]
For example: http://api.rtve.es/api/programas/1750/audios.rss

**Comment by lxea** [comment]
Hey, I've updated #118 it should hopefully fix updating for this feed.

You'll need to remove the feeds that werent updating and add them again though I think

**Comment by uGeek** [comment]
Brilliant!!! 

Now my Feed works and updates all podcasts perfectly.

Good job and thank you very much

**Comment by Code-Slave** [comment]
Heres a feed that doesnt work as it has a \ in the title

https://feeds.megaphone.fm/themessage

could not create feed: mkdir /podcasts/LifeAfter/The Message: no such file or directory

**Comment by sentriz** [comment]
hey @Code-Slave could you try v0.12.1? if you're using docker it should be built in a few minutes

**Comment by Code-Slave** [comment]
@sentriz  That fixed it thanks.

Question. Are there plans to set server to autodownload podcasts? I archive all my podcasts so when i add one i want it to download them all?

**Comment by lxea** [comment]
I've added a branch with support for autodownloading and downloading all episodes of a podcasts. however i want to do some testing first before itll be merge ready

its here if you want to try it out: https://github.com/lxea/gonic/commit/8c8e212f81d79ba7058e9b2c2101be60fc4fc300

**Comment by sentriz** [comment]
seems like all is sorted here? let me know if not

**Comment by Code-Slave** [comment]
Im liking it for sure
