### ISSUE TITLE
dsub - test connection failure

### ISSUE THREAD

**Issue by lbesnard** [sentriz/gonic#12]
found this post on reddit:
https://www.reddit.com/r/selfhosted/comments/dznn7d/gonic_golang_subsonic_compatible_server/f8cl7pr

I do have exactly the same behaviour:
```
"Connection failure. Resource not found. Please check the server address."

Funny thing is, when I tap on the option "open in browser" inside the server setup page in dsub, it opens the right page.

```

cheers!

**Comment by sentriz** [comment]
Hi Ibesnard. Do you see anything in the gonic logs when you click test connection?

**Comment by sentriz** [comment]
hi, please re-open if you manage to check the logs. thanks!
