### ISSUE TITLE
Method getMusicDirectory: id parameter not working

### ISSUE THREAD

**Issue by PhilipHannemann** [sentriz/gonic#120]
Hey :-)

The method `getMusicDirectory` is not working properly.
It always returns `<error code="10" message="please provide an `id` parameter"></error>`.

In line 57 in the file **handlers_by_folder.go**, it should be:
`id, err := params.Get("id")` instead of `id, err := params.GetID("id")`, I think.

https://github.com/sentriz/gonic/blob/87cd30325748e86cb9ba12789e92740730d6cbba/server/ctrlsubsonic/handlers_by_folder.go#L57

Kind regards
Philip

**Comment by sentriz** [comment]
Hey, by any chance, are you using DSub? If so which version?

On 13 February 2021 20:09:25 GMT, PhilipHannemann <notifications@github.com> wrote:
>Hey :-)
>
>The method `getMusicDirectory` is not working properly.
>It always returns `<error code="10" message="please provide an `id` parameter"></error>`.
>
>In line 57 in the file **handlers_by_folder.go**, it should be:
>`id, err := params.Get("id")` instead of `id, err := params.GetID("id")`, I think.
>
>https://github.com/sentriz/gonic/blob/87cd30325748e86cb9ba12789e92740730d6cbba/server/ctrlsubsonic/handlers_by_folder.go#L57
>
>Kind regards
>Philip
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/sentriz/gonic/issues/120
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by PhilipHannemann** [comment]
> Hey, by any chance, are you using DSub? If so which version?

I didn't, I just used php to connect to the server.
I executed:

```
$password = "pwd";
$salt = "salt";
$token = md5($password . $salt);
$server = 'http://127.0.0.1:81/rest/';

$response = file_get_contents($server.'getMusicDirectory.view?id=1&u=admin&t='.$token.'&s='.$salt.'&v=1.15.0&c=myapp');
```

Kind regards
Philip

**Comment by sentriz** [comment]
ah I see. the server expects the `id` parameter to be in the form of `<table>-<id>`
eg `?id=tr-65` for track with ID 65 

for this endpoint try `?id=al-3`

here are the ID prefixes
https://github.com/sentriz/gonic/blob/master/server/ctrlsubsonic/specid/ids.go#L22

this idea comes from the subsonic API spec where endpoints like `setRating` where it expects a single ID for a track, album, etc 
where there's no nice way to disambiguate them

**Comment by sentriz** [comment]
also, to add to above. try use `getMusicDirectory` with responses from `getIndexes` and you may have better luck : D

**Comment by PhilipHannemann** [comment]
Ok, thanks a lot for the quick response. 
I'll try this out.
And also sounds like a good Idea, to make the id unique.
Maybe it would be nice if you could document this somewhere outside of the code.

Kind regards
Philip

**Comment by sentriz** [comment]
Cool. Really I think any subsonic client shouldn't be thinking about IDs. Different servers use strings, ints, UUIDs, anything (at least from what I've seen)

Closing for now, but very happy to help with other issues if you have them 👍👍

**Comment by PhilipHannemann** [comment]
Thanks a lot, worked very well 👍

You are right. But I just started to work with this server and placed my test-music into the highest directory (in `music/` without any additional folder).
By asking for `getMusicFolders` this gave me the id 1 and I wanted to get all the media for this directory.
Internally the `music/` folder is treated as `al-1`. 
So by asking for `getMusicDirectory` with id `al-1` it worked, but not for the id 1.

Maybe you could consider returning `al-1` as the folder id when asking for `getMusicFolders`.
