### ISSUE TITLE
[enhancement] create cache directory if it doesn't exist

### ISSUE THREAD

**Issue by onedr0p** [sentriz/gonic#127]
I would like Gonic to create the cache directory if it doesn't exist

```
2021/03/22 19:05:33 starting gonic v0.12.2
2021/03/22 19:05:33 provided config
2021/03/22 19:05:33     cache-path      /data/cache
2021/03/22 19:05:33     config-path
2021/03/22 19:05:33     db-path         /data/gonic.db
2021/03/22 19:05:33     genre-split

2021/03/22 19:05:33     jukebox-enabled false
2021/03/22 19:05:33     listen-addr     :80
2021/03/22 19:05:33     music-path      /media-serenity/Library/Music
2021/03/22 19:05:33     podcast-path    /media-serenity/Library/Podcasts
2021/03/22 19:05:33     proxy-prefix
2021/03/22 19:05:33     scan-interval   120
2021/03/22 19:05:33     version         false
2021/03/22 19:05:33 please provide a valid cache directory
```

For now I have to use an `initContainer` to create the directory before the container starts

https://github.com/onedr0p/home-cluster/blob/b53508c551e28190b7914866a640e5ce3c530695/cluster/media/gonic/helm-release.yaml#L20

**Comment by sentriz** [comment]
hey, 
not sure if this is a kubernetes thing, 
but gonic has no logic for creating any of the root folders it's expecting (eg cache, music, podcasts)

at least in dockerland, when provide host->container mounts docker creates the host folders for you (in this example the `/tmp/g_*` folders didn't exist) 

perhaps there is a similar way in kubernetes? 
![image](https://user-images.githubusercontent.com/6832539/112220711-7aad0900-8c1e-11eb-8152-e5d80c7124e7.png)

**Comment by onedr0p** [comment]
:wave: No problem, I have it solved as I mentioned above. I'm trying to put the cache directory under `/data`. However when the application is first created `/data/cache` does not exist. Putting the cache directory here makes it much easier to maintain because I'll only need 1 gonic app volume for everything.
