### ISSUE TITLE
Errors when playing transcoded files via airsonic-refix

### ISSUE THREAD

**Issue by dalecooper** [sentriz/gonic#128]
I've found out about Gonic last week-end, and I love it so far. I'm happy to have found a lightweight alternative to Airsonic.

I need to have a web client for certain situations and it works almost perfectly with https://github.com/tamland/airsonic-refix
The only issue I'm running into is : when audio files are transcoded, they are playing fine but there is no progress bar, and after the transcoded file has been written to the cache dir I can see a lot of errors in the logs, see below

```
Mar 23 13:15:23 andrea sleepservice[163583]: 2021/03/23 13:15:23 response #033[42;1m 200 #033[0m for `/rest/getAlbum?id=al-8&u=admin&s=mJwMR0hjf6CwMH3N&t=6a32a70071239e82aa8db43a59c711f3&c=http:%2F%2Fmusic.ben.work&f=json&v=1.15.0`
Mar 23 13:15:29 andrea sleepservice[163583]: 2021/03/23 13:15:29 transcoding according to transcoding profile of 320k
Mar 23 13:15:29 andrea sleepservice[163583]: 2021/03/23 13:15:29 serving transcode `09. DJ Krush - Listen (feat. Shawn J. Period).flac`: cache [mp3/320k] miss!
Mar 23 13:16:49 andrea sleepservice[163583]: 2021/03/23 13:16:49 error while writing HTTP response: write tcp 192.168.0.40:4443->192.168.0.35:54322: i/o timeout
Mar 23 13:16:49 andrea sleepservice[163583]: message repeated 555 times: [ 2021/03/23 13:16:49 error while writing HTTP response: write tcp 192.168.0.40:4443->192.168.0.35:54322: i/o timeout]
Mar 23 13:16:50 andrea sleepservice[163583]: 2021/03/23 13:16:50 error while writing HTTP response: write tcp 192.168.0.40:4443->192.168.0.35:54322: i/o timeout
Mar 23 13:16:51 andrea sleepservice[163583]: message repeated 580 times: [ 2021/03/23 13:16:50 error while writing HTTP response: write tcp 192.168.0.40:4443->192.168.0.35:54322: i/o timeout]
Mar 23 13:16:51 andrea sleepservice[163583]: 2021/03/23 13:16:51 error while writing HTTP response: write tcp 192.168.0.40:4443->192.168.0.35:54322: i/o timeout
Mar 23 13:16:51 andrea sleepservice[163583]: message repeated 609 times: [ 2021/03/23 13:16:51 error while writing HTTP response: write tcp 192.168.0.40:4443->192.168.0.35:54322: i/o timeout]
Mar 23 13:16:52 andrea sleepservice[163583]: 2021/03/23 13:16:52 error while writing HTTP response: write tcp 192.168.0.40:4443->192.168.0.35:54322: i/o timeout
```

and so on ...

(note : 128k was way too low profile for me so I've updated encode.go and compiled myself to have 320k mp3, but the issue is exactly the same with the original binaries)

I'm not sure if this is due to Gonic or the web client, so I thought I'd try my luck here first.
Any idea ?

**Comment by sentriz** [comment]
hey I had a quick look this evening and I can produce the progress bar issue with airsonic-refix

it seems like it uses the web Audio API's `ontimeupdate` callback for progress bar status, so I made a test page

```html
<script>
  const rand = new Date().valueOf();
  const audio = new Audio();
  audio.src = `https://gonic/rest/stream?id=tr-40&format=raw&v=1.15.0&u=username&p=password&c=web&rand=${rand}`;
  audio.ontimeupdate = () => {
    console.log(audio.currentTime);
  };

  const play = () => {
    console.log("playing");
    audio.play();
  };
</script>

<button onclick="play()">play</button>
```

which, even when gonic is transcoding, prints the progress of the track to the console

![20210324_002241](https://user-images.githubusercontent.com/6832539/112236203-e2238280-8c37-11eb-8f3d-76f47672b8eb.png)

so it at least seems initially like the progress bar should be working

but I'll have another look tomorrow

**Comment by sentriz** [comment]
ah it seems like airsonic-refix uses `audio.duration` to calculate the progress bar. but when gonic is streaming something while transcoding, the duration is returned as `Infinity`

at had a look at some other subsonic clients, and they seem to use the duration in the tags instead
so maybe this makes sense to do client side
(though if there's a way to do it server side, that could be nice. but not sure how to do that)


```html
<script>
  const rand = new Date().valueOf();
  const audio = new Audio();
  audio.src = `https://gonic/rest/stream?id=tr-40&format=raw&v=1.15.0&u=admin&p=password&c=web&rand=${rand}`;
  audio.ontimeupdate = () => {
    console.log("time", audio.currentTime, "duration", audio.duration);
  };

  const play = () => {
    console.log("playing");
    audio.play();
  };
</script>

<button onclick="play()">play</button>
```

![20210324_134034](https://user-images.githubusercontent.com/6832539/112320475-f357a800-8ca6-11eb-81f4-63b95ee8bd4a.png)

I've opened a PR with subsonic-refix to try to this client side
https://github.com/tamland/airsonic-refix/pull/31

**Comment by sentriz** [comment]
Hey the PR @ airsonic refix has been merged . could you check if this is fixed for you? Thanks

**Comment by tamland** [comment]
`audio.duration` returning `Infinity` seems to be specific to chromium. In Firefox it's periodically changed for these streams. Possibly returning what is currently buffered? I.e. the progress bar will appear to jump backwards after a while.
