### ISSUE TITLE
No folders shown when browsing

### ISSUE THREAD

**Issue by staplebatteryhorse** [sentriz/gonic#134]
I've tried this with Jamstash, Ultrasonic and Sublime and none of them show browse by folders when using gonic 0.12.2. 

However those clients do all show the folders when using supysonic or airsonic.

my gonic config
`music-path        /mnt/cifs/music/organized/albums
cache-path        /home/sam/go/bin/cache
db-path           /home/sam/go/bin/gonic.db
jukebox-enabled   false
listen-addr       10.45.45.123:4747
proxy-prefix      /
scan-interval     0
podcast-path      /home/sam/go/bin/podcasts`

this is printed in the gonic server console when I refresh browse by folders in sublime.
`2021/04/20 20:07:03 response  200  for "/rest/getIndexes.view?u=sam&c=Sublime+Music&f=json&v=1.15.0&s=YgoaPy6E&t=4a2f605bcab9c9724dcfdb52974b8013"`

Anyone have any ideas?

**Comment by sentriz** [comment]
hi, did you start a scan on the gonic web UI?

**Comment by staplebatteryhorse** [comment]
Yes, have done full scan which has completed, and can search albums and artists.

**Comment by sentriz** [comment]
what happens if you just `$ curl http://10.45.45.123:4747:/rest/getIndexes.view?u=sam&c=Sublime+Music&f=json&v=1.15.0&s=YgoaPy6E&t=4a2f605bcab9c9724dcfdb52974b8013`

**Comment by staplebatteryhorse** [comment]
output of curl
`{"subsonic-response":{"status":"ok","version":"1.15.0","type":"gonic","gonicVersion":"v0.12.2","indexes":{"lastModified":0,"ignoredArticles":"","index":[]}}}%`

gonic server console
`2021/04/20 20:24:22 response  200  for "/rest/getIndexes.view?u=sam&c=Sublime+Music&f=json&v=1.15.0&s=YgoaPy6E&t=4a2f605bcab9c9724dcfdb52974b8013"`

**Comment by sentriz** [comment]
ah weird. I can reproduce it. it's the same on my system. no idea when this happened

**Comment by sentriz** [comment]
did a git bisect... it's been this way since christmas for browse-by-folder :ok_hand: 

thanks for the report. looking to fix it now

**Comment by staplebatteryhorse** [comment]
Awesome, thank you!

**Comment by sentriz** [comment]
hopefully fixed now in v0.12.3. thanks!

**Comment by sentriz** [comment]
(PS. you will have to scan again, not a full scan, just a normal one should do)
