### ISSUE TITLE
support for prometheus-style metrics

### ISSUE THREAD

**Issue by jelmer** [sentriz/gonic#150]
It would be great if gonic supported prometheus-style metrics at /metrics. Happy to contribute something if you'd be open to accepting PRs that added support for that.

**Comment by sentriz** [comment]
Yeah cool idea. Would the output of using expvar be suitable?

https://pkg.go.dev/expvar

This would be then /debug/vars instead of /metrics

**Comment by jelmer** [comment]
On Sat, Jul 24, 2021 at 12:02:18PM -0700, Senan Kelly wrote:
> Yeah cool idea. Would the output of using expvar be suitable?
> 
> https://pkg.go.dev/expvar
> 
> This would be then /debug/vars instead of /metrics

Unfortunately that wouldn't be scrapable by prometheus directly; if you'd
prefer not to have prometheus support directly in gonic, I could use
/debug/vars that to build a sidecar that exposes metrics appropriate
for prometheus.

Jelmer

-- 
Jelmer Vernooĳ ***@***.***>
PGP Key: https://www.jelmer.uk/D729A457.asc
