### ISSUE TITLE
Can't understand why "please provide a valid music directory"

### ISSUE THREAD

**Issue by acagastya** [sentriz/gonic#151]
I downloaded gonic by running `go get go.senan.xyz/gonic/cmd/gonic`.  In my music folder, I ran `gonic` to test it out, and I got "2021/08/22 06:19:34 please provide a valid music directory".

I followed the directory structure too, it looks like:
```
music
└── experimental
    └── Alan\ Vega
        └── (1980)\ Alan\ Vega
            ├── 01.08\ Jukebox\ Babe.flac
            └── folder.jpg

3 directories, 2 files
```

I ran `gonic -music-path music` and I still get:
```
﻿2021/08/22 06:29:49 starting gonic v0.13.1
2021/08/22 06:29:49 provided config
2021/08/22 06:29:49     cache-path
2021/08/22 06:29:49     config-path
2021/08/22 06:29:49     db-path         gonic.db
2021/08/22 06:29:49     genre-split

2021/08/22 06:29:49     http-log        true
2021/08/22 06:29:49     jukebox-enabled false
2021/08/22 06:29:49     listen-addr     0.0.0.0:4747
2021/08/22 06:29:49     music-path      music
2021/08/22 06:29:49     podcast-path
2021/08/22 06:29:49     proxy-prefix
2021/08/22 06:29:49     scan-interval   0
2021/08/22 06:29:49     version         false
2021/08/22 06:29:49 please provide a valid podcast directory
```

What should I do to fix it?

**Comment by sentriz** [comment]
> In my music folder

If you're already in your music folder when running gonic, try instead `-music-path .`. 

Alternatively go up one level to the directory which contains `music` and run the `-music-path music` as you were

**Comment by acagastya** [comment]
@sentriz I was speaking of two different things I tried.

```
$  pwd && tree . && gonic .
/Users/acagastya/Music/music
.
└── experimental
    └── Alan\ Vega
        └── (1980)\ Alan\ Vega
            ├── 01.08\ Jukebox\ Babe.flac
            └── folder.jpg

3 directories, 2 files
2021/08/22 12:00:32 starting gonic v0.13.1
2021/08/22 12:00:32 provided config
2021/08/22 12:00:32     cache-path
2021/08/22 12:00:32     config-path
2021/08/22 12:00:32     db-path         gonic.db
2021/08/22 12:00:32     genre-split

2021/08/22 12:00:32     http-log        true
2021/08/22 12:00:32     jukebox-enabled false
2021/08/22 12:00:32     listen-addr     0.0.0.0:4747
2021/08/22 12:00:32     music-path
2021/08/22 12:00:32     podcast-path
2021/08/22 12:00:32     proxy-prefix
2021/08/22 12:00:32     scan-interval   0
2021/08/22 12:00:32     version         false
2021/08/22 12:00:32 please provide a valid music directory
```

In the `music` directory I have tried `gonic .` and I have tried `gonic -music-path /Users/acagastya/Music/music` and it does not work, gives the same error.

**Comment by sentriz** [comment]
> `  pwd && tree . && gonic .`

How about instead `pwd && tree . && gonic -music-path .`

**Comment by acagastya** [comment]
Oh, now I realise, when I did `gonic -music-path /Users/acagastya/Music/music`, it said `please provide a valid podcast directory`.  Okay, figured.  I had to supply locations for the podcast and cache.  I just didn't notice the different error.  My bad.  Thanks for pointing out, @sentriz!
