### ISSUE TITLE
error on hitting the search button which opens the search box in dsub

### ISSUE THREAD

**Issue by mschaaf** [sentriz/gonic#152]
The search itself works. 

1. But after opening the search box in the client the errors come up in the logs.

```
Aug 23 20:51:26  gonic[31815]: 2021/08/23 20:51:26 http: panic serving 127.0.0.1:49114: runtime error: invalid memory address or nil pointer dereference
Aug 23 20:51:26  gonic[31815]: goroutine 1327621 [running]:
Aug 23 20:51:26  gonic[31815]: net/http.(*conn).serve.func1(0xc0004c2960)
Aug 23 20:51:26  gonic[31815]:         /media/data/gonic/go/src/net/http/server.go:1804 +0x153
Aug 23 20:51:26  gonic[31815]: panic(0xb64720, 0x12b04f0)
Aug 23 20:51:26  gonic[31815]:         /media/data/gonic/go/src/runtime/panic.go:971 +0x499
Aug 23 20:51:26  gonic[31815]: go.senan.xyz/gonic/server/ctrlsubsonic.(*Controller).ServeStream(0xc000176820, 0xd50570, 0xc000843ae8, 0xc00032b400, 0x0)
Aug 23 20:51:26  gonic[31815]:         /root/go/pkg/mod/go.senan.xyz/gonic@v0.13.1/server/ctrlsubsonic/handlers_raw.go:221 +0x226
Aug 23 20:51:26  gonic[31815]: go.senan.xyz/gonic/server/ctrlsubsonic.(*Controller).HR.func1(0xd50570, 0xc000843ae8, 0xc00032b400)
Aug 23 20:51:26  gonic[31815]:         /root/go/pkg/mod/go.senan.xyz/gonic@v0.13.1/server/ctrlsubsonic/ctrl.go:109 +0x47
Aug 23 20:51:26  gonic[31815]: net/http.HandlerFunc.ServeHTTP(0xc00047d5b0, 0xd50570, 0xc000843ae8, 0xc00032b400)
Aug 23 20:51:26  gonic[31815]:         /media/data/gonic/go/src/net/http/server.go:2049 +0x44
Aug 23 20:51:26  gonic[31815]: go.senan.xyz/gonic/server/ctrlsubsonic.(*Controller).WithUser.func1(0xd50570, 0xc000843ae8, 0xc00032b300)
Aug 23 20:51:26  gonic[31815]:         /root/go/pkg/mod/go.senan.xyz/gonic@v0.13.1/server/ctrlsubsonic/middleware.go:87 +0x6ac
Aug 23 20:51:26  gonic[31815]: net/http.HandlerFunc.ServeHTTP(0xc00013e600, 0xd50570, 0xc000843ae8, 0xc00032b300)
Aug 23 20:51:26  gonic[31815]:         /media/data/gonic/go/src/net/http/server.go:2049 +0x44
Aug 23 20:51:26  gonic[31815]: go.senan.xyz/gonic/server/ctrlsubsonic.(*Controller).WithRequiredParams.func1(0xd50570, 0xc000843ae8, 0xc00032b300)
Aug 23 20:51:26  gonic[31815]:         /root/go/pkg/mod/go.senan.xyz/gonic@v0.13.1/server/ctrlsubsonic/middleware.go:50 +0x1c5
Aug 23 20:51:26  gonic[31815]: net/http.HandlerFunc.ServeHTTP(0xc00073a870, 0xd50570, 0xc000843ae8, 0xc00032b300)
Aug 23 20:51:26  gonic[31815]:         /media/data/gonic/go/src/net/http/server.go:2049 +0x44
```

2. Picking an artist name fro mthe search recommendation leads to the errors: `please provide an 'id' parameter`

**Comment by sentriz** [comment]
hi! thanks for the report. could you try the docker `nightly` image if you're doing the docker. or otherwise trying building from the `develop` branch to see if this is fixed? thanks!

**Comment by mschaaf** [comment]
IMHO I compiled the latest development verison. The command I used is `sudo GOBIN=/usr/local/bin go install go.senan.xyz/gonic/cmd/gonic@latest`. Is this correct?

**Comment by sentriz** [comment]
maybe try `sudo GOBIN=/usr/local/bin go install go.senan.xyz/gonic/cmd/gonic@develop`

**Comment by mschaaf** [comment]
No, it did not, but I checked out the branch and compiled it. The version is still reported as 0.13.1, is this correct?
I can't reproduce it with a self-compiled version of this branch. I will watch it and report back if it happens again.

My 2. point from above is still an issue, but maybe unrelated to the 1st point.

Thanks for the fast help.

**Comment by mschaaf** [comment]
The request to point 2 is `/rest/getArtist.view?u=<user>&s=<something>&t=<something>&v=1.2.0&c=DSub&id=47777` The server response is:
```
<subsonic-response xmlns="http://subsonic.org/restapi" status="failed" version="1.15.0" type="gonic">
<error code="10" message="please provide an `id` parameter"/>
</subsonic-response>
```

**Comment by mschaaf** [comment]
The error message is misleading as the id is provided but seems not to be valid. The artist id accepted by gonic is `ar-47777`. All artist ids start with `ar-`, but dsub does not send it.

**Comment by sentriz** [comment]
ah ! I think you maybe hitting this 

https://github.com/daneren2005/Subsonic/issues/1043

I think the solution is to upgrade to DSub 5.5.2 (APKs are on GitHub for example, not sure what version the Play Store is at)

if that doesn't work, please re-open. thanks!

**Comment by mschaaf** [comment]
Yes, it seems so. The search returns the correct id, so dsub seems to remove non-number characters from the id field.
I will try to upgrade.

**Comment by mschaaf** [comment]
The dsub version https://github.com/daneren2005/Subsonic/releases/tag/5.5.2R2 fixed it, but it is not in the play store.
