### ISSUE TITLE
Artist image from Last.fm

### ISSUE THREAD

**Issue by randrej** [sentriz/gonic#153]
Since you're already getting the artist info and similar artists from last.fm, would it be possible to also get the artist image? Another provider would also be fine. In Sublime Music, the albums have proper covers, yet artists don't have a picture, which looks uneven.

**Comment by Duncaen** [comment]
The image is already used, but last.fm just provides the generic star item. It seems like they removed support for that.
https://stackoverflow.com/questions/55978243/last-fm-api-returns-same-white-star-image-for-all-artists

So this would need to use some other service as alternative.

**Comment by sentriz** [comment]
Ah true, I misread this issue as getting the artist images from musicbrainz

**Comment by karlprieb** [comment]
Navidrome is using Spotify API for this now
