### ISSUE TITLE
Improved documentation on using encrypting site

### ISSUE THREAD

**Issue by michael-keyes** [sentriz/gonic#155]
Would it be possible to add a bit more documentation on how to encrypt a gonic instance?

**Comment by sentriz** [comment]
Hi ! Do you mean have gonic listen over TLS? Or something else

**Comment by michael-keyes** [comment]
> Hi ! Do you mean have gonic listen over TLS? Or something else

Hi sentriz! Thanks for the quick response asking for clarification on my poorly worded request.
I've been trying without success to encrypt my gonic instance/site using certbot, but have been uable to do so even with the assistance of the documentation.

**Comment by sentriz** [comment]
Ah I see gotcha. it's not possible to ask gonic to serve with a custom TLS cert. However, what I do, and I imagine many others , use a reverse proxy like nginx, caddy, traefik, etc - and put TLS in front of that instead .


Caddy and traefik are also able to automatically acquire and renew certs for you

**Comment by michael-keyes** [comment]
> Ah I see gotcha. it's not possible to ask gonic to serve with a custom TLS cert. However, what I do, and I imagine many others , use a reverse proxy like nginx, caddy, traefik, etc - and put TLS in front of that instead .
> 
> Caddy and traefik are also able to automatically acquire and renew certs from Lets Encrypt for you (instead of certbot)
> 
> Does this sound interesting?

Thanks for your help. It sounds as though my problem is beyond the scope of this project. Thank you for offering assistance, I'll to figure this using the methods you mentioned. Do you feel that a detailed explanation of the process for acquiring TLS is needed or should users be more informed on such processes before using Gonic?

**Comment by sentriz** [comment]
Definitely it would be worth mentioning that most people use it with a reverse proxy. I'll think about adding something to the docs.

And PS just in case your not sure, the reason everyone uses reverse proxies  in the "selfhosting" world is you can serve all your many sites/services from a port. Eg

https://gonic.my.domain -> http://localhost:9393
https://othersite.my.domain -> http://localhost:7868

And so there's no port numbers to remember, https is automatic, less attack surface . very nice 👌

**Comment by michael-keyes** [comment]
> Definitely it would be worth mentioning that most people use it with a reverse proxy. I'll think about adding something to the docs.
> 
> And PS just in case your not sure, the reason everyone uses reverse proxies in the "selfhosting" world is you can serve all your many sites/services from a port. Eg
> 
> https://gonic.my.domain -> http://localhost:9393
> https://othersite.my.domain -> http://localhost:7868
> 
> And so there's no port numbers to remember, https is automatic, less attack surface . very nice 
> 
> Caddy would be easiest for https

**Comment by michael-keyes** [comment]
> > Definitely it would be worth mentioning that most people use it with a reverse proxy. I'll think about adding something to the docs.
> > And PS just in case your not sure, the reason everyone uses reverse proxies in the "selfhosting" world is you can serve all your many sites/services from a port. Eg
> > https://gonic.my.domain -> http://localhost:9393
> > https://othersite.my.domain -> http://localhost:7868
> > And so there's no port numbers to remember, https is automatic, less attack surface . very nice
> > Caddy would be easiest for https

Thanks a lot!
