### ISSUE TITLE
Newly added cover art to existing album is not picked up by full nor incremental scan

### ISSUE THREAD

**Issue by mschaaf** [sentriz/gonic#158]
Having a folder for an album and have it scanned already but without a cover art image.
Adding that later it will not be added to the database by an incremental scan nor a full scan.
The only thing that helps is renaming the album folder and wait for another scan and rename it back afterwards.

**Comment by sentriz** [comment]
thanks! I could reproduce this and is hopefully now fixed

**Comment by mschaaf** [comment]
Thanks for the fast help. I installed your fix and indeed it works now.
