### ISSUE TITLE
Last.fm scrobbling not working

### ISSUE THREAD

**Issue by TheLastZombie** [sentriz/gonic#162]
I set up and linked Last.fm to my Gonic (0.14.0) instance, but scrobbling doesn't seem to be working.

![image](https://user-images.githubusercontent.com/8181990/136991668-3a58e9dc-912f-4967-b3cc-a2d608aa4bdb.png)

I tested this with [Ultrasonic](https://github.com/ultrasonic/ultrasonic), which updates the now playing status but doesn't send any scrobbles, and [Subtracks](https://github.com/austinried/subtracks), which does neither. I enabled the respective scrobble settings in both apps.

The log doesn't contain any errors either:

```
Oct 12 18:09:06 raspberrypi gonic[640]: 2021/10/12 18:09:06 serving raw `01. Enter Sandman.mp3`
Oct 12 18:09:07 raspberrypi gonic[640]: 2021/10/12 18:09:07 response  200  for `/rest/scrobble?u=roesch&t=[...]&s=[...]&v=1.15.0&c=subtracks&id=tr-9529`
```

I also double-checked the API key/secret and my account connection. Curiously enough, Listenbrainz scrobbling *does* work.

**Comment by TheLastZombie** [comment]
Ah, now I'm getting something:

```
2021/10/13 06:28:58 new scrobble request
2021/10/13 06:28:58 scrobbling with 0
2021/10/13 06:28:58 scrobbling with lastfm 17. Perfect Sound Whatever.mp3
2021/10/13 06:28:58 lastfm response:
2021/10/13 06:28:58 HTTP/2.0 200 OK
Content-Length: 451
Access-Control-Allow-Methods: POST, GET, OPTIONS
Access-Control-Allow-Origin: *
Access-Control-Max-Age: 86400
Alt-Svc: clear
Content-Type: text/xml; charset=UTF-8
Date: Wed, 13 Oct 2021 04:28:58 GMT
Server: openresty/1.13.6.2
Via: 1.1 google
```
```XML
<?xml version="1.0" encoding="UTF-8"?>
<lfm status="ok">
  <scrobbles ignored="1" accepted="0">
    <scrobble>
      <track corrected="0">Perfect Sound Whatever</track>
      <artist corrected="0">Jeff Rosenstock</artist>
      <album corrected="0">WORRY.</album>
      <albumArtist corrected="0">Jeff Rosenstock</albumArtist>
      <timestamp>2011765</timestamp>
      <ignoredMessage code="1"></ignoredMessage>
    </scrobble>
  </scrobbles>
</lfm>
```
```
2021/10/13 06:28:58 scrobbling with 1
```

The `ignoredMessage` sticks out to me. According to [Last.fm's API documentation](https://www.last.fm/api/scrobbling#filtered-requests), a code of `1` means "filtered artist", but in the provided example, the field isn't empty (plus I've successfully scrobbled this artist before).

I also noticed the timestamps vary greatly (2011765 above, 1288728940 in the example). I wonder if it has something to do with that, but the `ignoredMessage` code for "timestamp too far in the past" is `3`.

**Comment by sentriz** [comment]
yeah that is a funny looking timestamp. what is the `?time=` param that ultrasonic sends to the `/rest/scrobble` endpoint? if any

I also updated the issue-162 branch to improve the time parsing. maybe that could fix it?
