### ISSUE TITLE
Support output to a named pipe in Jukebox mode (like mpd) for the purpose of feeding the output to snapcast

### ISSUE THREAD

**Issue by danhansen** [sentriz/gonic#164]
It would be great to have an option for gonic to output to a named pipe for the purpose of feeding snapcast. This is more of a "nice-to-have", given that the same result can more or less already be achieved with the `snd-aloop` kernel module or the `module-pipe-sink` pulseaudio module. However, those solutions have more moving parts/dependencies, which makes them less ideal for things like docker deployment. The named pipe approach is very self-contained.

Here is an example of how that can be configured between snapcast and mpd today:

https://github.com/badaix/snapcast/blob/master/doc/player_setup.md#mpd

The implementation appears to be more or less as simple as invoking `fwrite` to write the contents of the audio buffer to the named pipe:

https://github.com/MusicPlayerDaemon/MPD/blob/master/src/output/plugins/PipeOutputPlugin.cxx

If I find some spare time, I may take a stab at an implementation.

**Comment by sentriz** [comment]
@danhansen it's looking like i'm going to update jukebox mode to use mpv and talk to over IPC

(then we get less resource usage, gapless playback, support for more file formats, removal of a few dependencies that are giving me trouble at the moment)

in that case, how about we support some new gonic option like `-jukebox-mode-extra-args`, to which you could supply `--ao=pcm --ao-pcm-file=path/to/my-pipe` ?
