### ISSUE TITLE
Scans (full or not) do not detect songs in previously empty folders

### ISSUE THREAD

**Issue by tereteru** [sentriz/gonic#165]
Sometimes, it happens that gonic starts scanning while some album on my server hasn't been fully downloaded. If that's the case, then, even after subsequent (full) scans, it will not detect music in that folder.
Only renaming the folder (or resetting the whole database) seems to fix this.

**Comment by robot3498712** [comment]
Hi sentriz,
I meanwhile looked into my problem in greater detail, and implemented following:
https://github.com/robot3498712/gonic/commit/89749d9ce85aa42f2280e5354b49c542f9a0cf7f
https://github.com/robot3498712/gonic/commit/80ef6f36429f8067ab82c746d3ed6806404e752c
https://github.com/robot3498712/gonic/commit/3f871dd3da289c3865e993d92f7ff7eb46b9d8cc
This does fix my cover issue.
I don't know golang enough to make a pull request (or notice any nasty side effects it may have), but perhaps this gives you ideas while doing the rework.

**Comment by sentriz** [comment]
@robot3498712 thanks very much checking out the scanner code and implementing a fix 👍

though I did decide to completely re-do the scanner again and this time with tests

I think it's much simpler now (only one callback, no defer magic, no implicit transactions, no push / pop stack business)

@robot3498712 , @tereteru 
would you mind checking out this (slightly experimental) branch to see if things are better now?

`go install go.senan.xyz/gonic/cmd/gonic@mockfs-scanner`

thanks!!

**Comment by robot3498712** [comment]
Outstanding, thanks @sentriz for the super speedy overhaul.
I directly upgraded to 0.15 branch and it appears to be working perfectly fine now.
<3 gonic

**Comment by sentriz** [comment]
great to hear :) thanks for letting me know

**Comment by tereteru** [comment]
Hi, I can confirm it's fixed on my end as well with the v0.15 branch!
Thanks a lot!
