### ISSUE TITLE
no music found with fuse.sshfs

### ISSUE THREAD

**Issue by kusky3** [sentriz/gonic#166]
How to reproduce:
set "music-path" to $dir
set 755 to $dir
$dir is fuse.sshfs
run full scan and incremental scan

expected behavior:
the music is indexed

actual behavior:
no music found

**Comment by sentriz** [comment]
hi, is there any output in the gonic logs when scanning?

**Comment by kusky3** [comment]
'''error while scanning: walking filesystem: stat /test/music: permission denied'''
do i need write permission for gonic on it?

**Comment by sentriz** [comment]
ah yes, directories should have the execute bit set. try chmod 775, or 777. if you don't want write access it could be 555

**Comment by kusky3** [comment]
i gave rwx to "others"
still getting permission denied

**Comment by sentriz** [comment]
what user / group is the gonic process running as?

**Comment by kusky3** [comment]
gonic:gonic

**Comment by sentriz** [comment]
you say the error in the logs is for `stat /test/music` is that still the case? and is that the folder you gave o+rwx to? if the error is now for deeper folders, all folders the music dir need o+rx or o+rwx I think (`chmod -R`)

**Comment by sentriz** [comment]
actually, maybe you can ask sshfs to do that for you `sshfs -o allow_other,default_permissions `

**Comment by kusky3** [comment]
yes, thanks.
it's not a gonic issue, allow_other is what i was missing.
I created a gonic user with the same uid in the remote machine and make it the owner.
