### ISSUE TITLE
Missing artistId property on songs returned by API

### ISSUE THREAD

**Issue by jeffvli** [sentriz/gonic#170]
Some endpoints are currently omitting the `artistId` property when returning songs. This impacts the browsing experience on some clients as you're unable to navigate to the artist page without it.

Here's a list of some of the endpoints that I've checked that are missing the property (not complete):
- `/getRandomSongs`
- `/getPlaylists`
- `/getPlaylist`
- `/getSongsByGenre`
- `/getMusicDirectory`
- `/getSong`

Here's some that do include the property (not complete):
- `/getAlbumList2`
- `/getAlbum`

Example song returned from `/getRandomSongs` missing `artistId`.
```
"song": [
  {
    "id": "tr-28145",
    "album": "Ronald Jenkees",
    "albumId": "al-4909",
    "artist": "Ronald Jenkees",
    "bitRate": 221,
    "contentType": "audio/mpeg",
    "created": "2021-11-09T23:29:25.266331406-08:00",
    "duration": 182,
    "isDir": false,
    "isVideo": false,
    "parent": "al-4909",
    "path": "RonaldJenkees/Ronald Jenkees - Ronald Jenkees (V0)/13 56K (Rap).mp3",
    "size": 5053788,
    "suffix": "mp3",
    "title": "56k",
    "track": 13,
    "type": "music",
    "year": 2007
  },
```

And this is the same song returned from `/getAlbum` which includes the `artistId`:
```
  {
    "id": "tr-28145",
    "album": "Ronald Jenkees",
    "albumId": "al-4909",
    "artist": "Ronald Jenkees",
    "artistId": "ar-1931",
    "bitRate": 221,
    "contentType": "audio/mpeg",
    "created": "2021-11-09T23:29:25.266331406-08:00",
    "duration": 182,
    "isDir": false,
    "isVideo": false,
    "parent": "al-4909",
    "path": "RonaldJenkees/Ronald Jenkees - Ronald Jenkees (V0)/13 56K (Rap).mp3",
    "size": 5053788,
    "suffix": "mp3",
    "title": "56k",
    "track": 13,
    "type": "music",
    "year": 2007
  },
```

It would be nice if this was made consistent between all songs returned by the API.

**Comment by sentriz** [comment]
thank you for investigating. should be fixed in the endpoints you mentioned now

**Comment by sentriz** [comment]
(if not please let me know. thanks!)
