### ISSUE TITLE
symlinked albums removed from database

### ISSUE THREAD

**Issue by cascooscuro** [sentriz/gonic#174]
After installing  latest master (https://github.com/sentriz/gonic/commit/155c8b4a8b10eec486dd1bb89b96b4da68cf8236), using multiple folders,  when scan finished,  most of my albums had disappeared:

```
Nov 26 10:38:08 gon gonic[2031182]: 2021/11/26 10:38:08 finished clean tracks in 17.74279s, 508773 removed
Nov 26 10:48:06 gon gonic[2031182]: 2021/11/26 10:48:06 finished clean albums in 9m57.56656s, 48993 removed
Nov 26 10:48:38 gon gonic[2031182]: 2021/11/26 10:48:38 finished clean artists in 32.81913s, 26704 removed
Nov 26 10:48:40 gon gonic[2031182]: 2021/11/26 10:48:40 finished clean genres in 1.33226s, 2143 removed
Nov 26 10:48:40 gon gonic[2031182]: 2021/11/26 10:48:40 finished scan in 16m36.27997s, +0/8727 tracks (3 err)
```

It looks that the removed tracks/albums are only symlinked directories. Directories that are not symlinked are not affected.

**Comment by sentriz** [comment]
Oh no, sorry this happened. Do you symlink top level music paths? As in the ones in passed with GONIC_MUSIC_PATH? Or do you symlink paths a bit deeper? like an individual album for example

**Comment by sentriz** [comment]
Also interesting that 50% of the total scan time was spent in the clean albums stage.... I need to look at that

**Comment by cascooscuro** [comment]
Thanks for your prompt answer!

In my case I'm symlinking albums. 
My gonic config is like this:

```
...
music-path       /_genre/soundtrack
music-path       /_genre/opera
...
```

and the folder structure:

```
[media@gon _genre]$ ls -al soundtrack/AIR/
total 76
drwxr-xr-x    2 media media  4096 Feb  3  2021  .
drwxr-xr-x 1407 media media 65536 Oct  4 03:33  ..
lrwxrwxrwx    1 media media    77 Feb  3  2021 '(2000) The Virgin Suicides (REC-01; 7243 8488482 6; CDV 2910)  [FLAC]' -> '/media/music/id/946133/Air - The Virgin Suicides (2000) [CDV 2910]'
```

**Comment by cascooscuro** [comment]
Thanks for releasing a fix so quickly!!

I'm testing it in my setup and what I'm seeing is that the artist used (the top folder containing the album) is the one that follows the symlink, not the source folder.

I will try to explain myself better. In my previous exmple:

```
[media@gon _genre]$ ls -al soundtrack/AIR/
total 76
drwxr-xr-x    2 media media  4096 Feb  3  2021  .
drwxr-xr-x 1407 media media 65536 Oct  4 03:33  ..
lrwxrwxrwx    1 media media    77 Feb  3  2021 '(2000) The Virgin Suicides (REC-01; 7243 8488482 6; CDV 2910)  [FLAC]' -> '/media/music/id/946133/Air - The Virgin Suicides (2000) [CDV 2910]'
```

What I'm seeing as artist is "946133" instead of "AIR".

Maybe my setup is a bit of special, but perhaps it would make sense to use the source folder.

Thanks for your support.

**Comment by sentriz** [comment]
thanks for checking it out @cascooscuro :+1: though that fix was a bit of a workaround. with the latest changes in that PR, 7d63cfd5ba5fc72317c9d8346b56c0ca7ec37dae, a kind of recursive walk happens when it encounters a symlink. is that situation any better now?

**Comment by cascooscuro** [comment]
Thanks @sentriz but it looks that still shows destination folder:

```
        <album id="al-2430" coverArt="al-2430" artist="134304" created="2021-11-29T21:42:03.61923393+01:00" title="Frank Zappa &amp; The Mothers of Invention - (1968) Cruising with Ruben &amp; The Jets (FLAC) (ZR 3838) (2012)" parent="al-2429" isDir="true" name="" songCount="13" duration="2480"></album>

```

**Comment by sentriz** [comment]
@cascooscuro that's an interesting case. do you know, did it work as you expected it to do in the past? perhaps around fc50f01de338d34054794a7451c25f8dab8a49ba

**Comment by sentriz** [comment]
Hi . I wrote a test case to describe the behaviour you expected. From some again limited testing I think it should be working now with the latest of that branch. Could you confirm? Thanks!

**Comment by cascooscuro** [comment]
Thanks! 
It's working except for the cases where the album is multidisc and its audio files are enclosed in multiple directories. Like this one for example:

```
[media@gon _genre]$ ls -al "rock/Lou Reed/(1978) Live - Take No Prisoners (German Release)  [FLAC]"
lrwxrwxrwx 1 media media 69 Feb  3  2021 'rock/Lou Reed/(1978) Live - Take No Prisoners (German Release)  [FLAC]' -> '/xxx/yyy/zzz/id/381533/Lou Reed - Live - Take No Prisoners'

[media@gon _genre]$ ls -al '/xxx/yyy/zzz/id/381533/Lou Reed - Live - Take No Prisoners'
total 44
drwxrwxr-x 4 media media  4096 Mar 18  2019  .
drwxrwxrwx 3 media media  4096 Mar 18  2019  ..
-rwxrwxrwx 1 media media 22925 Jun 28  2015  Cover.jpg
drwxrwxr-x 2 media media  4096 Mar 18  2019 'Disc 1'
drwxrwxr-x 2 media media  4096 Mar 18  2019 'Disc 2'
-rwxrwxrwx 1 media media   750 Jun 28  2015 'Lou Reed - Live - Take No Prisoners.m3u'
[media@gon _genre]$

```

In those cases the folder is empty and no audio files are shown.

Thanks again for your help.

**Comment by sentriz** [comment]
hey @cascooscuro how are things working now? I did some more testing and both cases you described seem to work for me now. but it does seem you're quite good a catching the edge cases that I miss :grin:

**Comment by cascooscuro** [comment]
Thanks @sentriz it's working now, albums are detected.

But I'm now realizing that multi-disc albums introduce quite a good amount  of complexity. Taking the example in the previous comment:
```
[media@gon _genre]$ ls -al "rock/Lou Reed/(1978) Live - Take No Prisoners (German Release)  [FLAC]"
lrwxrwxrwx 1 media media 69 Feb  3  2021 'rock/Lou Reed/(1978) Live - Take No Prisoners (German Release)  [FLAC]' -> '/xxx/yyy/zzz/id/381533/Lou Reed - Live - Take No Prisoners'

[media@gon _genre]$ ls -al '/xxx/yyy/zzz/id/381533/Lou Reed - Live - Take No Prisoners'
total 44
drwxrwxr-x 4 media media  4096 Mar 18  2019  .
drwxrwxrwx 3 media media  4096 Mar 18  2019  ..
-rwxrwxrwx 1 media media 22925 Jun 28  2015  Cover.jpg
drwxrwxr-x 2 media media  4096 Mar 18  2019 'Disc 1'
drwxrwxr-x 2 media media  4096 Mar 18  2019 'Disc 2'
-rwxrwxrwx 1 media media   750 Jun 28  2015 'Lou Reed - Live - Take No Prisoners.m3u'
[media@gon _genre]$
```
I was expecting the artist to be "Lou Reed" but as "(1978) Live - Take No Prisoners (German Release)  [FLAC]" is the folder that contains both discs, it becomes the artist.

I'm not sure how airsonic does it but it looks there is some heuristic and use of tags to detect multi disc albums and correctly display artists in those cases (https://github.com/airsonic/airsonic/pull/567).

It would be great if gonic could detect those multi-disc albums and correctly display the artist. In any case just at it is now it's working perfectly.

Thanks for your work here @sentriz !!

**Comment by sentriz** [comment]
Ah yes ! Sorry I forgot about that. One of the requirements of a filesystem layout for gonic is that one album is in one folder. Exactly what you pointed out. And the reason is that it makes things dramatically simpler when implementing both browse by tags and browse by folder (I think I mentioned this requirement in the readme somewhere)

Personally I use beets.io to organise my music and it puts multidisc albums in the same folder but just prefixes the filenames with the disc number. Hopefully this works for you and apologies if not

On 21 December 2021 19:42:09 GMT, cascooscuro ***@***.***> wrote:
>Thanks @sentriz it's working now, albums are detected.
>
>But I'm now realizing that multi-disc albums introduce quite a good amount  of complexity. Taking the example in the previous comment:
>```
***@***.*** _genre]$ ls -al "rock/Lou Reed/(1978) Live - Take No Prisoners (German Release)  [FLAC]"
>lrwxrwxrwx 1 media media 69 Feb  3  2021 'rock/Lou Reed/(1978) Live - Take No Prisoners (German Release)  [FLAC]' -> '/xxx/yyy/zzz/id/381533/Lou Reed - Live - Take No Prisoners'
>
***@***.*** _genre]$ ls -al '/xxx/yyy/zzz/id/381533/Lou Reed - Live - Take No Prisoners'
>total 44
>drwxrwxr-x 4 media media  4096 Mar 18  2019  .
>drwxrwxrwx 3 media media  4096 Mar 18  2019  ..
>-rwxrwxrwx 1 media media 22925 Jun 28  2015  Cover.jpg
>drwxrwxr-x 2 media media  4096 Mar 18  2019 'Disc 1'
>drwxrwxr-x 2 media media  4096 Mar 18  2019 'Disc 2'
>-rwxrwxrwx 1 media media   750 Jun 28  2015 'Lou Reed - Live - Take No Prisoners.m3u'
***@***.*** _genre]$

**Comment by cascooscuro** [comment]
My main use case is to organize my music library without altering the original files, that's why I have rely on tricks like symlinks and folder structure. I also have multiple instances that present different views of the library: based on genre, on playlists, on record label...  Gonic is perfect due to its low footprint .

I completely agree with you that's it's better to keep it simple and try to use things like beets to properly tag/name the library. I recently discovered that brtfs can handle some sort of deduplication and also beets supports it, so I will try it to see if it works for me.

Thanks!
