### ISSUE TITLE
Expose data so client apps can determine servertype and version

### ISSUE THREAD

**Issue by MichaelBechHansen** [sentriz/gonic#18]
For clients apps to tailor the user interface to the exact server capabilities, it would be helpful to expose a way to determine servertype and version.

In an ideal world, the "version" property of the Subsonic responses would be enough.
In practice servers like Gonic implement a subset of the Subsonic API.

Allowing the client apps to learn the server type and version facilitates tailoring exposed functionality to what the server actually support.

Many servers (funk whale, madsonic, ampache, ...) expose a "type" property on all Subsonic responses, for example a ping-response from funkwhale:
`
{
    "subsonic-response": {
        "status": "ok",
        "version": "1.16.0",
        "type": "funkwhale",
        "funkwhaleVersion": "0.17"
    }
}
`

Some servers do not expose "type" in responses, but have information in the getLicense-response that can be used to know servertype...  For example AirSonic has "email": "airsonic@github.com".

If for example "type" and "gonicVersion" is added to responses, clients like play:Sub Music Streamer (https://apps.apple.com/fr/app/play-sub-music-streamer/id955329386) will be able to make a tailored UI for Gonic.

**Comment by sentriz** [comment]
good idea, thank you
