### ISSUE TITLE
File scan gets stuck

### ISSUE THREAD

**Issue by espilioto** [sentriz/gonic#183]
Running 0.14.0 in a container and loving it because it's lightweight and supports folder view ❤
No idea why no other server does that, browsing by tags isn't convenient with large collections.

During the initial scan the site became unresponsive and the last entries in the logs were:
`TagLib: MPEG::Header::parse() -- MPEG header did not match MPEG synch.`
`TagLib: MPEG::Properties::read() -- Could not find an MPEG frame in the stream.`
`TagLib: MPEG::Header::parse() -- MPEG header did not match MPEG synch.`

Restarting the container fixed it, but when I tried to complete the scan (using incremental) it just froze again a few seconds later.
Also tried the full scan, but the behavior was identical.

Any ideas?

Thanks in advance :D

Edit: I decided to just let it sit and a few hours later check on it by restarting the container.
The track count had changed ever so slightly (like 20 songs), meaning that something did happen even if everything else was frozen.

**Comment by sentriz** [comment]
hey @espilioto thanks :) may I ask what your hardware is, and how much music are you scanning? I have not seen or heard of gonic freezing before

**Comment by espilioto** [comment]
At the moment it's running on a test VM with half the logical processors of a Ryzen 1700 (8) and 8GB of ram.
It's scanning a collection of about 33k MP3s/~230GB (a FLAC/transcoding test will be done later 😄)

**Comment by sentriz** [comment]
well that is very strange indeed. also when you stay v0.14.0. is that the release tag? could you try master if you're running from source (`$ go install <gonic>@master`), or else the `:nightly` tag if running from docker?

**Comment by espilioto** [comment]
Pulled the nightly and spun it up.
In a matter of 1-2 minutes had already passed the point where the old instance failed.
Things are looking good!

Will update you when it finishes scanning.

**Comment by sentriz** [comment]
ah ok interesting. I can reproduce the UI locking up when taglib is slow to read some tags (since there is an open database transaction that isn't being closed)

I'm thinking it could be an issue with filesystem access or tag issues like you suggested, so maybe we could test both at the same time

when gonic is scanning it should print what folder it is about to process, before any transaction is started, like

```
processing folder `/path/to/folder`
<locks up>
``` 

so could you try to check all the tracks in that path with ffprope (from ffmpeg)?

something like `$ find /path/to/folder -exec ffprobe '{}' \;` (with bash, and gnu find if you have it)

and see if ffprope can read all the files and their tags

PS what filesystem is gonic scanning to pickup music? local ex4, ntfs, remote sshfs?

**Comment by espilioto** [comment]
Aight, I'll give ffprobe a go and edit the comment with the results.

Gonic scans a ntfs hdd connected to my home server that provides a smb share, so the volume looks like this:

```
volumes:
  music:
    driver: local
    driver_opts:
      type: cifs
      device: "//192.168.69.69/xxx/zzz"
      o: "user=user,password=pass"
```

**Comment by sentriz** [comment]
good to know thanks, then I also think it makes sense to do it inside the gonic container like for example

```
$ docker-compose exec <gonic> /bin/sh
> find /music/path/to/album ...
```

just incase  you didn't know

**Comment by espilioto** [comment]
I scanned a bunch of directories including the last one before the hang.
Most of the tracks had this result:

```
[mp3 @ 0x7fb8d2a34640] Format mp3 detected only with low score of 1, misdetection possible!
[mp3 @ 0x7fb8d2a34640] decoding for stream 0 failed
[mp3 @ 0x7fb8d2a34640] Could not find codec parameters for stream 0 (Audio: mp3 (mp3float), 0 channels, fltp): unspecified frame size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
```

**Comment by sentriz** [comment]
ah right. well that's the problem I would say. seems like the mp3s are corrupt for something, so the gonic tag reader is hanging. really it shouldn't hang it should, it should error out. for the meantime I would say you should get rid of that folder, and try a gonic scan again

**Comment by sentriz** [comment]
PS would you mind emailing me one of those broken mp3s? if it's not too much trouble. would be easy for me to try fix this later on :sunglasses:

**Comment by espilioto** [comment]
Done!
