### ISSUE TITLE
 scan takes quite a long time

### ISSUE THREAD

**Issue by cascooscuro** [sentriz/gonic#187]
Using latest release (https://github.com/sentriz/gonic/commit/24d64e2125995bbe446fcadc449cc0914a70202c)

scanning takes a very long time:

```
Jan 19 16:26:15 server systemd[1]: Started Gonic Media Server.
Jan 19 16:26:15 server gonic[760148]: 2022/01/19 16:26:15 starting gonic v0.14.0
Jan 19 16:26:15 server gonic[760148]: 2022/01/19 16:26:15 provided config
Jan 19 16:26:15 server gonic[760148]: 2022/01/19 16:26:15     cache-path      /var/lib/gonic/gonic_cache
Jan 19 16:26:15 server gonic[760148]: 2022/01/19 16:26:15     config-path     /var/lib/gonic/config
Jan 19 16:26:15 server gonic[760148]: 2022/01/19 16:26:15     db-path         /var/lib/gonic/gonic.db
Jan 19 16:26:15 server gonic[760148]: 2022/01/19 16:26:15     genre-split
Jan 19 16:26:15 server gonic[760148]: 2022/01/19 16:26:15     http-log        true
Jan 19 16:26:15 server gonic[760148]: 2022/01/19 16:26:15     jukebox-enabled false
Jan 19 16:26:15 server gonic[760148]: 2022/01/19 16:26:15     listen-addr     192.168.1.2:4747
Jan 19 16:26:15 server gonic[760148]: 2022/01/19 16:26:15     music-path      /music_collages
Jan 19 16:26:15 server gonic[760148]: 2022/01/19 16:26:15     podcast-path    /var/lib/gonic/gonic_podcast
Jan 19 16:26:15 server gonic[760148]: 2022/01/19 16:26:15     proxy-prefix
Jan 19 16:26:15 server gonic[760148]: 2022/01/19 16:26:15     scan-interval   1440
Jan 19 16:26:15 server gonic[760148]: 2022/01/19 16:26:15     version         false
Jan 19 16:26:15 server gonic[760148]: 2022/01/19 16:26:15 migration '202002192100' finished
Jan 19 16:26:15 server gonic[760148]: 2022/01/19 16:26:15 migration '202002192019' finished
Jan 19 16:26:15 server gonic[760148]: 2022/01/19 16:26:15 migration '202002192222' finished
Jan 19 16:26:15 server gonic[760148]: 2022/01/19 16:26:15 migration '202003111222' finished
Jan 19 16:26:15 server gonic[760148]: 2022/01/19 16:26:15 migration '202003121330' finished
Jan 19 16:26:15 server gonic[760148]: 2022/01/19 16:26:15 migration '202003241509' finished
Jan 19 16:26:15 server gonic[760148]: 2022/01/19 16:26:15 migration '202004302006' finished
Jan 19 16:26:15 server gonic[760148]: 2022/01/19 16:26:15 migration '202012151806' finished
Jan 19 16:26:15 server gonic[760148]: 2022/01/19 16:26:15 migration '202101081149' finished
Jan 19 16:26:15 server gonic[760148]: 2022/01/19 16:26:15 migration '202101111537' finished
Jan 19 16:26:15 server gonic[760148]: 2022/01/19 16:26:15 migration '202102032210' finished
Jan 19 16:26:15 server gonic[760148]: 2022/01/19 16:26:15 migration '202102191448' finished
Jan 19 16:26:15 server gonic[760148]: 2022/01/19 16:26:15 migration '202110041330' finished
Jan 19 16:26:15 server gonic[760148]: 2022/01/19 16:26:15 migration '202111021951' finished
Jan 19 16:26:15 server gonic[760148]: 2022/01/19 16:26:15 migration '202201042236' finished
Jan 19 16:26:15 server gonic[760148]: 2022/01/19 16:26:15 starting job 'scan timer'
Jan 19 16:26:15 server gonic[760148]: 2022/01/19 16:26:15 starting job 'session clean'
Jan 19 16:26:15 server gonic[760148]: 2022/01/19 16:26:15 starting job 'http'
Jan 19 16:26:15 server gonic[760148]: 2022/01/19 16:26:15 starting job 'podcast refresher'
Jan 19 21:37:19 server gonic[760148]: 2022/01/19 21:37:19 starting scan
Jan 19 21:48:13 server gonic[760148]: [249B blob data]
Jan 19 21:48:13 server gonic[760148]: [232B blob data]
Jan 20 09:05:08 server gonic[760148]: 2022/01/20 09:05:08 finished clean tracks in 5.57986s, 0 removed
Jan 20 09:05:08 server gonic[760148]: 2022/01/20 09:05:08 finished clean albums in 230.99ms, 0 removed
Jan 20 10:39:05 server gonic[760148]: 2022/01/20 10:39:05 finished clean artists in 1h33m56.93323s, 6584 removed
Jan 20 10:39:08 server gonic[760148]: 2022/01/20 10:39:08 finished clean genres in 2.62097s, 9 removed
Jan 20 10:39:11 server gonic[760148]: 2022/01/20 10:39:11 finished scan in 13h1m52.11749s, +1990854/1990855 tracks (0 err)
Jan 20 16:26:16 server gonic[760148]: 2022/01/20 16:26:16 starting scan
Jan 20 16:27:15 server gonic[760148]: [249B blob data]
Jan 20 16:27:15 server gonic[760148]: [232B blob data]
Jan 20 17:25:26 server gonic[760148]: 2022/01/20 17:25:26 finished clean tracks in 1.70868s, 21 removed
Jan 20 17:25:27 server gonic[760148]: 2022/01/20 17:25:27 finished clean albums in 166.51ms, 0 removed
Jan 20 18:00:59 server gonic[760148]: 2022/01/20 18:00:59 finished clean artists in 35m32.30033s, 6584 removed
Jan 20 18:01:01 server gonic[760148]: 2022/01/20 18:01:01 finished clean genres in 2.51565s, 9 removed
Jan 20 18:01:01 server gonic[760148]: 2022/01/20 18:01:01 finished scan in 1h34m45.87234s, +27003/1990855 tracks (0 err)
Jan 20 19:23:13 server gonic[760148]: 2022/01/20 19:23:13 starting scan
Jan 20 19:23:32 server gonic[760148]: [249B blob data]
Jan 20 19:23:32 server gonic[760148]: [232B blob data]
Jan 20 20:18:58 server gonic[760148]: 2022/01/20 20:18:58 finished clean tracks in 1.71301s, 0 removed
Jan 20 20:18:58 server gonic[760148]: 2022/01/20 20:18:58 finished clean albums in 167.39ms, 0 removed
Jan 20 20:55:13 server gonic[760148]: 2022/01/20 20:55:13 finished clean artists in 36m14.76288s, 6584 removed
Jan 20 20:55:16 server gonic[760148]: 2022/01/20 20:55:16 finished clean genres in 2.62618s, 9 removed
Jan 20 20:55:16 server gonic[760148]: 2022/01/20 20:55:16 finished scan in 1h32m2.60503s, +27290/1991163 tracks (0 err)
Jan 21 16:26:16 server gonic[760148]: 2022/01/21 16:26:16 starting scan
Jan 21 16:27:11 server gonic[760148]: [249B blob data]
Jan 21 16:27:11 server gonic[760148]: [232B blob data]
Jan 21 17:49:06 server gonic[760148]: 2022/01/21 17:49:06 finished clean tracks in 3.3758s, 0 removed
Jan 21 17:49:07 server gonic[760148]: 2022/01/21 17:49:07 finished clean albums in 184.36ms, 0 removed
Jan 22 01:50:46 server gonic[760148]: 2022/01/22 01:50:46 finished clean artists in 8h1m39.54289s, 6584 removed
Jan 22 01:50:55 server gonic[760148]: 2022/01/22 01:50:55 finished clean genres in 9.30778s, 9 removed
Jan 22 01:51:03 server gonic[760148]: 2022/01/22 01:51:03 finished scan in 9h24m47.13808s, +26982/1991163 tracks (0 err)
Jan 22 16:26:16 server gonic[760148]: 2022/01/22 16:26:16 starting scan
Jan 22 16:27:10 server gonic[760148]: [249B blob data]
Jan 22 16:27:10 server gonic[760148]: [232B blob data]
Jan 22 17:47:48 server gonic[760148]: 2022/01/22 17:47:48 finished clean tracks in 3.42023s, 0 removed
Jan 22 17:47:48 server gonic[760148]: 2022/01/22 17:47:48 finished clean albums in 201.36ms, 0 removed
Jan 23 03:04:07 server gonic[760148]: 2022/01/23 03:04:07 finished clean artists in 9h16m18.51284s, 6584 removed
Jan 23 03:04:10 server gonic[760148]: 2022/01/23 03:04:10 finished clean genres in 3.04823s, 9 removed
Jan 23 03:04:10 server gonic[760148]: 2022/01/23 03:04:10 finished scan in 10h37m54.15316s, +26982/1991163 tracks (0 err)

```

First scan was around 13h. The next two incremental scans took only 94/92 minutes. The next two incremental scans have lasted around 10h.

The database is quite big:5200 artists, 160k albums, 2M tracks

I'm testing now with a release  previous to [https://github.com/sentriz/gonic/commit/24d64e2125995bbe446fcadc449cc0914a70202c](url) to see if there are any differences.

As always, thanks in advance for your help.

**Comment by cascooscuro** [comment]
Small update.
With latest release 0.14.0 (Oct 3 2021):

First Scan (9h):
Feb 04 17:08:33 server gonic[863386]: 2022/02/04 17:08:33 starting scan
Feb 05 02:21:14 server gonic[863386]: 2022/02/05 02:21:14 finished scan in 9h12m41.21716s, +2010875/2010875 tracks (0 err)
Feb 05 02:21:19 server gonic[863386]: 2022/02/05 02:21:19 finished clean tracks in 4.76575s, 0 removed
Feb 05 02:21:19 server gonic[863386]: 2022/02/05 02:21:19 finished clean albums in 225.63ms, 0 removed
Feb 05 02:21:19 server gonic[863386]: 2022/02/05 02:21:19 finished clean artists in 14.64ms, 0 removed
Feb 05 02:21:29 server gonic[863386]: 2022/02/05 02:21:29 finished clean genres in 10.49369s, 55 removed

Second scan: (30min)
Feb 06 09:34:53 server gonic[863386]: 2022/02/06 09:34:53 starting scan
Feb 06 10:06:39 server gonic[863386]: 2022/02/06 10:06:39 finished scan in 31m45.48232s, +21/2010875 tracks (0 err)
Feb 06 10:06:42 server gonic[863386]: 2022/02/06 10:06:42 finished clean tracks in 3.1483s, 21 removed
Feb 06 10:06:42 server gonic[863386]: 2022/02/06 10:06:42 finished clean albums in 246.94ms, 0 removed
Feb 06 10:06:42 server gonic[863386]: 2022/02/06 10:06:42 finished clean artists in 27.56ms, 0 removed
Feb 06 10:06:45 server gonic[863386]: 2022/02/06 10:06:45 finished clean genres in 2.5353s, 2 removed

**Comment by sentriz** [comment]
hi! sorry for the delay on this one

if this has started happening to you between cb6b33a9fb69589bf73e33773c6f16bf073ce865 and 24d64e2125995bbe446fcadc449cc0914a70202c then I think I have an idea of what caused the slower scans

if you get a chance could you try again with master? thanks!

**Comment by sentriz** [comment]
actually, in terms of scanning, I think it should be identical to around cb6b33a9fb69589bf73e33773c6f16bf073ce865

if not please let me know / reopen!

**Comment by cascooscuro** [comment]
Thanks @sentriz !

First scan 11h
Feb 09 21:58:11 server gonic[1329090]: 2022/02/09 21:58:11 starting scan
Feb 10 08:31:35 server gonic[1329090]: 2022/02/10 08:31:35 finished clean tracks in 3.81199s, 0 removed
Feb 10 08:31:35 server gonic[1329090]: 2022/02/10 08:31:35 finished clean albums in 223.43ms, 0 removed
Feb 10 09:07:57 server gonic[1329090]: 2022/02/10 09:07:57 finished clean artists in 36m21.93221s, 6589 removed
Feb 10 09:08:00 server gonic[1329090]: 2022/02/10 09:08:00 finished clean genres in 2.97035s, 9 removed
Feb 10 09:08:00 server gonic[1329090]: 2022/02/10 09:08:00 finished scan in 11h9m48.96924s, +2010875/2010876 tracks (0 err)
2nd incremental 3h40m
Feb 11 14:33:21 server gonic[1329090]: 2022/02/11 14:33:21 starting scan
Feb 11 16:49:56 server gonic[1329090]: 2022/02/11 16:49:56 finished clean tracks in 1m14.33688s, 18033 removed
Feb 11 17:27:01 server gonic[1329090]: 2022/02/11 17:27:01 finished clean albums in 37m5.07763s, 1392 removed
Feb 11 18:13:43 server gonic[1329090]: 2022/02/11 18:13:43 finished clean artists in 46m42.33525s, 6533 removed
Feb 11 18:13:49 server gonic[1329090]: 2022/02/11 18:13:49 finished clean genres in 5.30682s, 17 removed
Feb 11 18:13:49 server gonic[1329090]: 2022/02/11 18:13:49 finished scan in 3h40m27.35328s, +43423/2008812 tracks (0 err)

3rd incremental 3h12m
Feb 12 09:01:36 server gonic[1329090]: 2022/02/12 09:01:36 starting scan
Feb 12 10:40:10 server gonic[1329090]: 2022/02/12 10:40:10 finished clean tracks in 4.17553s, 0 removed
Feb 12 10:40:11 server gonic[1329090]: 2022/02/12 10:40:11 finished clean albums in 232.19ms, 0 removed
Feb 12 12:14:00 server gonic[1329090]: 2022/02/12 12:14:00 finished clean artists in 1h33m49.87274s, 6589 removed
Feb 12 12:14:05 server gonic[1329090]: 2022/02/12 12:14:05 finished clean genres in 4.68749s, 9 removed
Feb 12 12:14:07 server gonic[1329090]: 2022/02/12 12:14:07 finished scan in 3h12m31.00659s, +58335/2040527 tracks (0 err)

It's difficult to compare to 0.14.0, because in this case the incremental updates had a lot of changes, but it's interesting that the "clear artist" routine it's taking longer. Maybe in my case it's something related to having all the library symlinked.
I will keep a look at it and let you know.

Thanks for your help.

**Comment by sentriz** [comment]
I think first of all, I want to find out why when some people do a scan twice without any filesystem changes, the second scan reports some tracks were removed then added again. I haven't been able to reproduce this until now (by fuzzing the scanner)

so I'll try fix that, then see how that helps with the performance

**Comment by cascooscuro** [comment]
I can provide access to my db if you think it can help.

Thanks!

**Comment by sentriz** [comment]
thanks @cascooscuro , how is it looking now on master?

there are some performance improvements and hopefully a fix for your situation of tracks being added and removed again (and the clean artists stuff)

personally on my system it's taking about 5s for an inc scan of 36k tracks

![image](https://user-images.githubusercontent.com/6832539/155801054-02b67cf6-2653-434d-8ea3-d158a523f9d8.png)

**Comment by cascooscuro** [comment]
Thanks @sentriz 

First scan looks much faster:

Feb 26 12:06:50 server gonic[195005]: 2022/02/26 12:06:50 starting scan
Feb 26 18:50:02 server gonic[195005]: 2022/02/26 18:50:02 finished clean tracks in 1.98063s, 0 removed
Feb 26 18:50:02 server gonic[195005]: 2022/02/26 18:50:02 finished clean albums in 187.48ms, 0 removed
Feb 26 18:50:02 server gonic[195005]: 2022/02/26 18:50:02 finished clean artists in 12.8ms, 0 removed
Feb 26 18:50:04 server gonic[195005]: 2022/02/26 18:50:04 finished clean genres in 1.92724s, 0 removed
Feb 26 18:50:04 server gonic[195005]: 2022/02/26 18:50:04 finished scan in 6h43m13.91228s, +2075279/2075279 tracks (95 err)
Feb 26 18:50:04 server gonic[195005]: 2022/02/26 18:50:04 error while scanning:
Feb 26 18:50:04 server gonic[195005]: lstat : no such file or directory
Feb 26 18:50:04 server gonic[195005]: lstat : no such file or directory
Feb 26 18:50:04 server gonic[195005]: lstat : no such file or directory
Feb 26 18:50:04 server gonic[195005]: lstat : no such file or directory
Feb 26 18:50:04 server gonic[195005]: lstat : no such file or directory
Feb 26 18:50:04 server gonic[195005]: lstat : no such file or directory
... 95 occurences of these  "lstat" error

second scan looks good too in terms of speed but it's detecting 21 tracks as removed when there hasn't been any changes in the filesystem:

Feb 26 21:32:55 server gonic[195005]: 2022/02/26 21:32:55 starting scan
Feb 26 22:27:26 server gonic[195005]: 2022/02/26 22:27:26 finished clean tracks in 1.78104s, 21 removed
Feb 26 22:27:26 server gonic[195005]: 2022/02/26 22:27:26 finished clean albums in 171.84ms, 0 removed
Feb 26 22:27:26 server gonic[195005]: 2022/02/26 22:27:26 finished clean artists in 12.34ms, 0 removed
Feb 26 22:27:27 server gonic[195005]: 2022/02/26 22:27:27 finished clean genres in 1.11459s, 0 removed
Feb 26 22:27:27 server gonic[195005]: 2022/02/26 22:27:27 finished scan in 54m32.16474s, +21/2075279 tracks (95 err)
Feb 26 22:27:27 server gonic[195005]: lstat : no such file or directory
Feb 26 22:27:27 server gonic[195005]: lstat : no such file or directory
Feb 26 22:27:27 server gonic[195005]: lstat : no such file or directory
Feb 26 22:27:27 server gonic[195005]: lstat : no such file or directory
Feb 26 22:27:27 server gonic[195005]: lstat : no such file or directory
... 95 occurences of these  "lstat" error


apart from these lstat errors there are a few TagLib errors that I have seen before. In understand these are not relevant:

Feb 26 15:32:02 server gonic[195005]: TagLib: ID3v2.4 no longer supports the frame type TDAT.  It will be discarded from the tag.
Feb 26 15:42:36 server gonic[195005]: TagLib: Ogg::XiphComment::parse() - Discarding a field. Invalid base64 data
Feb 26 15:45:46 server gonic[195005]: TagLib: FLAC::File::scan() -- multiple Vorbis Comment blocks found, discarding
Feb 26 15:20:20 server gonic[195005]: TagLib: String::copyFromUTF8() - UTF8-CPP error: Invalid UTF-8
Feb 26 17:36:35 server gonic[195005]: TagLib: ID3v2.4 no longer supports the frame type TSIZ.  It will be discarded from the tag.

**Comment by cascooscuro** [comment]
A third scan was also quite fast and in this case no changes were detected:

Feb 27 00:19:07 server gonic[195005]: 2022/02/27 00:19:07 starting scan
Feb 27 01:05:02 server gonic[195005]: 2022/02/27 01:05:02 finished clean tracks in 1.79943s, 0 removed
Feb 27 01:05:02 server gonic[195005]: 2022/02/27 01:05:02 finished clean albums in 173.66ms, 0 removed
Feb 27 01:05:02 server gonic[195005]: 2022/02/27 01:05:02 finished clean artists in 12.42ms, 0 removed
Feb 27 01:05:04 server gonic[195005]: 2022/02/27 01:05:04 finished clean genres in 1.12244s, 0 removed
Feb 27 01:05:04 server gonic[195005]: 2022/02/27 01:05:04 finished scan in 45m56.51239s, +0/2075279 tracks (95 err)
Feb 27 01:05:04 server gonic[195005]: 2022/02/27 01:05:04 error while scanning:
Feb 27 01:05:04 server gonic[195005]: lstat : no such file or directory
Feb 27 01:05:04 server gonic[195005]: lstat : no such file or directory
Feb 27 01:05:04 server gonic[195005]: lstat : no such file or directory
Feb 27 01:05:04 server gonic[195005]: lstat : no such file or directory
Feb 27 01:05:04 server gonic[195005]: lstat : no such file or directory
Feb 27 01:05:04 server gonic[195005]: lstat : no such file or directory
...

**Comment by sentriz** [comment]
thanks! it seems like the scans are a bit more stable now. so all in all, we've gone from a 30 min inc scan (v0.14), to a 45 min inc scan (master)?

still pretty slow. but have an absolutely massive db though

does your database file live on an ssd or spinny disc? and what filesystem does the music live on? sorry if I asked this already

**Comment by cascooscuro** [comment]
That's right. First scan is now 3h faster than 0.14 (9h>6h) and incremental is only 15m slower (31m->45m).

It's also interesting that in both 0.14 and now the incremental scan detected 21 tracks to be removed.

db is on ssd and media on a 20TB  ext4 LV made of two spinning disks.

Thanks.

**Comment by sentriz** [comment]
okay, that's pretty good news I suppose.

I still think it's weird since my scan of 36k tracks takes 5.5s. scaling it up to your size `(2_000_000/36_000)*5.5` is 300s not 45m

I know it wouldn't scale linearly but it's still off by an order of magnitude

just incase there's something weird happening and we're not doing a lot of waiting on io, so maybe we could do a cpu profile

https://github.com/sentriz/gonic/tree/add-scanner-profiling

if you're up for it, you could install again with this branch, then do a simple inc scan (no need to do anymore full scans)
let it do it's thing, and it should create a file similar to `/tmp/gonic-pprof-cpu-<timestamp>` to share

(and incase you're using docker, I think a `docker cp "gonic:/tmp/gonic-pprof-cpu-1234" .` should copy it out of the container and into cwd)

**Comment by cascooscuro** [comment]
Thanks @sentriz

Here you are:

[gonic-pprof-cpu-1646039542416956185.gz](https://github.com/sentriz/gonic/files/8152645/gonic-pprof-cpu-1646039542416956185.gz)

**Comment by sentriz** [comment]
![profile001](https://user-images.githubusercontent.com/6832539/155987119-a9f9310e-72e9-4c93-93b0-959a1c5e2d99.svg)

very interesting, still looking now

**Comment by sentriz** [comment]
@cascooscuro can we get any faster than 45m if you do a `$ sqlite3 path/to/gonic.db "vacuum"`?

**Comment by cascooscuro** [comment]
Before vacuum:
629M Feb 28 13:19 gonic.db

After vacuum:
599M Mar  1 10:10 gonic.db

Scan finishes in 46m:

Mar 01 10:14:51 server gonic[427576]: 2022/03/01 10:14:51 starting scan
Mar 01 11:01:19 server gonic[427576]: 2022/03/01 11:01:19 finished clean tracks in 1.73178s, 0 removed
Mar 01 11:01:19 server gonic[427576]: 2022/03/01 11:01:19 finished clean albums in 164.76ms, 0 removed
Mar 01 11:01:19 server gonic[427576]: 2022/03/01 11:01:19 finished clean artists in 13.58ms, 0 removed
Mar 01 11:01:20 server gonic[427576]: 2022/03/01 11:01:20 finished clean genres in 1.15736s, 0 removed
Mar 01 11:01:20 server gonic[427576]: 2022/03/01 11:01:20 finished scan in 46m29.23894s, +0/2080559 tracks (0 err)

Not sure if its impacting the scan but just wanted to let you know that all the media is under symlinks. 

Thanks for taking care of this.

**Comment by sentriz** [comment]
600M!! my db is 11M!! that is crazy. could you send me it?

**Comment by sentriz** [comment]
thanks! I could not find anything crazy in there really. 

also interestingly, I just grabbed an album for the first time this morning and checked the logs. the scan took ~1m! which adds up to you approximately (2000000 track / 36000 track) * 1m = ~55m.
but after scanning again right afterwards, I was back to 5s (both times inc scans)

so now by current theory is that my harddrives (a few seagate ST8000DM004) have a 128MB onboard cache. when it's hot I get fast speeds, when cold I speeds similar to yours


________________________________


since the only thing the inc scanner is doing during an inc scan is a `stat`, I think there's not too many ways of going faster. except maybe some parallelisation. though I imagine we could end up going even slower then in some situations

**Comment by cascooscuro** [comment]
I think that with these latest releases scanning times are stable and agree with you that there is not much else we can do speed it up. 

My main concern was the strange duration of the "clean/tracks/artist/genres" and that is fixed now, so I think we can close this.

Thanks!!

**Comment by awsms** [comment]
could we have multi-threaded scanning? in comparison with epoupon/lms, gonic takes around 4* more time to scan the same library :(
