### ISSUE TITLE
Database constraint errors while attempting to scan library

### ISSUE THREAD

**Issue by Neurrone** [sentriz/gonic#190]
I'm using version 506899b. I have two folders of media: `/music` and `/audiobooks`, in case this matters.

In the music folder, I have the following structure:

* artist name
    1. album 1: contents of this album
    2. album 2
    3. album 3

```
2022/02/02 21:10:58 finished scan in 11m55.91023s, +22457/22458 tracks (299 err)                                                     
2022/02/02 21:10:58 error while scanning:                                                                                            
"/music/Aleksandar Dimitrijevic": first or create parent: UNIQUE constraint failed: albums.left_path, albums.right_path              
"/music/Aleksandar Dimitrijevic/Sinners": first or create parent: UNIQUE constraint failed: albums.left_path, albums.right_path      
"/music/Andreas Waldetoft": first or create parent: UNIQUE constraint failed: albums.left_path, albums.right_path                    
"/music/Andreas Waldetoft/Creation And Beyond": first or create parent: UNIQUE constraint failed: albums.left_path, albums.right_path
"/music/Andreas Waldetoft/Crusader Kings II Soundtrack": first or create parent: UNIQUE constraint failed: albums.left_path, albums.right_path                                                                                                                            
```

It goes on for about 200 more lines with similar errors.

**Comment by sentriz** [comment]
thanks @Neurrone 

master is a little bit unstable at the moment and I've seen this one before. it's related to #187 

hoping to fix it soon, in the meantime 27ac8e1d25d9b58a8c71b9f7318a6b398f4a5865 should work better for you

please reopen if you have the same issue then. thanks!

**Comment by Neurrone** [comment]
Thanks. Is the database safe to reuse when I downgrade?

**Comment by sentriz** [comment]
yep should be fine :+1:

**Comment by Neurrone** [comment]
I'm still seeing this error, 15 errors instead of hundreds even after the downgrade.

**Comment by sentriz** [comment]
how about now?

**Comment by Neurrone** [comment]
Yes, tonnes. Doesn't seem to have helped with this problem.

**Comment by sentriz** [comment]
maybe you upgraded the database at a tricky time when the feature of multiple folders was being added. master can be a bit unstable at times. perhaps you could try scanning again with a fresh database? alternatively you could email me your database and I could try take a look
