### ISSUE TITLE
Feature request: Per-user folder permissions

### ISSUE THREAD

**Issue by jgdye** [sentriz/gonic#191]
It would be nice if we could set per-user folder permissions, so that each user's all file view and folder list would only contain items in folders they had permission to view, similar to Airsonic.  A couple of use cases I can think of are families with multiple users with very different musical tastes or parents wanting to have access to explicit content without providing access to their children, while letting the children have access to the rest of the music (and possibly even having the reverse case, where the children have access to "kid's music" that the adults don't want making it into a random playlist for themselves).

**Comment by sentriz** [comment]
perhaps related #156

btw is this something that airsonic does? and is it mentioned in the subsonic api spec?

**Comment by dotsoltecti** [comment]
Although this would be a cool feature, a simple workaround is to launch multiple gonic-containers (one for each user). In my case, this gonic-setup is only using a fraction of the resources airsonic-advanced used to use. I'm just saying, I would be delighted if this feature got implemented, but in the meantime, I'll manage. ;)

**Comment by sentriz** [comment]
closign in favour of #156
