### ISSUE TITLE
Question with gonic and substreamer app ( android )

### ISSUE THREAD

**Issue by Vctrsnts** [sentriz/gonic#197]
Hi.

I use the version 0.14.0 ( docker version ) with substreamer ( app in android ).

Working fine, but I have a questions :
 - Where is the order the albums when selection artist folder? Is possible to change? Because I see ( example with artist Tiesto ) : 
   - Club Life 687
   - Club Life 600
   - Club Life 700
   - Club Life 688
   - etc...

I have this question, because with other alternatives ( navidrome in docker ) on the same option ( artist - tiesto ) and the same configuration in app ( substreamer in android ) the order of albums is correct :
  - Club Life 600
  - Club Life 687
  - Club Life 688
  - Club Life 700
  - etc...

Thanks a lot

**Comment by sentriz** [comment]
wow, I haven't listened to the club life podcast in probably 10 years. mad that he's still making them :grin: 

should be fixed now on master, let me know if not
