### ISSUE TITLE
API lookup albumList byYear with range error

### ISSUE THREAD

**Issue by robot3498712** [sentriz/gonic#208]
Hi, I may have found an issue:

https://github.com/sentriz/gonic/blob/release-v0.15.0/server/ctrlsubsonic/handlers_by_folder.go
(and possibly other handlers)
```
"tag_year BETWEEN ? AND ?",
			params.GetOrInt("toYear", 2200),
			params.GetOrInt("fromYear", 1800))
```
**Params are in incorrect order; fromYear should come first.**
Noticed via https://github.com/crustymonkey/py-sonic/blob/master/libsonic/connection.py

**Comment by sentriz** [comment]
thanks. that was silly :)
