### ISSUE TITLE
what is the example docker yaml and how do you use it?

### ISSUE THREAD

**Issue by jrwren** [sentriz/gonic#21]
The README shows some yaml but it does not seem to be docker-compose yaml.

What is it and how does one use it?

**Comment by sentriz** [comment]
hi jreren. that is docker-compose.yml in the readme. what trouble are you having with it?

**Comment by jrwren** [comment]
Does it go under a `services:` entry? As is as the whole document, docker says:

```
Starting gonic ... done
ERROR: No containers to start
```

which... now that I read it again looks like it should work.

**Comment by sentriz** [comment]
yeah that should have been more clear. updated now. thanks!

**Comment by jrwren** [comment]
another thing that would help for people like me who rarely use docker compose is the reminder of the command `docker-compose up`

Thanks for you help.

**Comment by sentriz** [comment]
updated :+1: closing for now. let me know if you have other problems
