### ISSUE TITLE
Listenbrainz API: CamelCase instead of snake_case

### ISSUE THREAD

**Issue by krateng** [sentriz/gonic#216]
Hey,

I don't know Go, but from looking at [listenbrainz.go](https://github.com/sentriz/gonic/blob/master/scrobble/listenbrainz/listenbrainz.go), scrobbles seem to be submitted with JSON values that follow CamelCase (e.g. `ListenType`) instead of snake_case (e.g. `listen_type`), like the [Listenbrainz documentation](https://listenbrainz.readthedocs.io/en/latest/users/json/#submission-json) suggests.

Now this isn't an issue for me of course, I just wanted to verify whether this is indeed part of the ListenBrainz specification or an implementation detail of the reference server.

Thank you!

Linked: krateng/maloja#141

**Comment by sentriz** [comment]
hey, they are actually snake_case but the issue seems to be a missing header

**Comment by krateng** [comment]
Thanks for the quick fix!
