### ISSUE TITLE
Can't get scrobbling to last.fm to work

### ISSUE THREAD

**Issue by hugalafutro** [sentriz/gonic#219]
Hi,
I used airsonic-advanced as server and Ultrasonic as player on android phone. I swapped server to gonic (really like how lightweight it is) and noticed my scrobbles stopped

I've set up the last.fm api, it says linked in gonic admin screen. No scrobbles were sent so I thought my user has to be named same as last.fm user so I tried that but to no avail.

In logs I can see some true/false submissions, but when I actually check the last.fm page last scrobble was 5 days ago from when I still used airsonic.
```
gonic  | 2022/05/02 13:21:20 response  200  for `/rest/scrobble.view?c=Ultrasonic&f=json&id=tr-18642&p=REDACTED&submission=false&u=sammael&v=1.15.0`
gonic  | 2022/05/03 13:31:14 response  200  for `/rest/scrobble.view?c=Ultrasonic&f=json&id=tr-6155&p=REDACTED&submission=false&u=sammael&v=1.15.0`
gonic  | 2022/05/03 13:31:14 response  200  for `/rest/scrobble.view?c=Ultrasonic&f=json&id=tr-18642&p=REDACTED&submission=true&u=sammael&v=1.15.0`
gonic  | 2022/05/03 13:31:46 response  200  for `/rest/scrobble.view?c=Ultrasonic&f=json&id=tr-21&p=REDACTED&submission=false&u=sammael&v=1.15.0`
gonic  | 2022/05/03 13:31:50 response  200  for `/rest/scrobble.view?c=Ultrasonic&f=json&id=tr-6155&p=REDACTED&submission=false&u=sammael&v=1.15.0`
gonic  | 2022/05/03 22:19:28 response  200  for `/rest/scrobble.view?c=Ultrasonic&f=json&id=tr-21&p=REDACTED&submission=false&u=sammael&v=1.15.0`
gonic  | 2022/05/03 22:19:46 response  200  for `/rest/scrobble.view?c=Ultrasonic&f=json&id=tr-25485&p=REDACTED&submission=false&u=sammael&v=1.15.0`
gonic  | 2022/05/03 22:24:52 response  200  for `/rest/scrobble.view?c=Ultrasonic&f=json&id=tr-25485&p=REDACTED&submission=true&u=sammael&v=1.15.0`
gonic  | 2022/05/03 22:24:53 response  200  for `/rest/scrobble.view?c=Ultrasonic&f=json&id=tr-5674&p=REDACTED&submission=false&u=sammael&v=1.15.0`
gonic  | 2022/05/04 11:37:45 response  200  for `/rest/scrobble.view?c=Ultrasonic&f=json&id=tr-205&p=REDACTED&submission=false&u=Sammael666&v=1.15.0`
gonic  | 2022/05/04 11:40:25 response  200  for `/rest/scrobble.view?c=Ultrasonic&f=json&id=tr-26144&p=REDACTED&submission=false&u=Sammael666&v=1.15.0`
gonic  | 2022/05/04 11:45:54 response  200  for `/rest/scrobble.view?c=Ultrasonic&f=json&id=tr-26144&p=REDACTED&submission=true&u=Sammael666&v=1.15.0`
gonic  | 2022/05/04 11:45:54 response  200  for `/rest/scrobble.view?c=Ultrasonic&f=json&id=tr-16257&p=REDACTED&submission=false&u=Sammael666&v=1.15.0`
```

I tried playing a song in kodi and that scrobbles ok (according to last.fm page gonic never connected):
![image](https://user-images.githubusercontent.com/30209689/166670178-b4d5aefd-859d-4f58-8dba-3139a1e524d7.png)

Thanks for any advice!

**Comment by jrabensc** [comment]
Did you try to scrobble multiple tracks? For me, it's only working for some of my music, more obscure tracks are not working currently.

**Comment by hugalafutro** [comment]
I've played music via gonic for ~5 days not a single track scrobbled, same tracks scrobble from anywhere else. On the Last.fm page it still says gonic never connected and gonic says it's succesfully connected to last.fm

**Comment by hugalafutro** [comment]
This is the gap where I used gonic, the music is fairly mainstream nothing obscure like weird characters or nothing:
![image](https://user-images.githubusercontent.com/30209689/167250421-2c6f648a-50d9-4658-aeba-7aacb441f50b.png)

**Comment by sentriz** [comment]
@hugalafutro @jrabensc I just added a commit to mater that will log stuff if we recieve an error message from lastfm. it should be like `received bad lastfm response: ...`

could you try run from master and see if anything is logged? i can also publish a debug docker image if that helps. thanks!

**Comment by hugalafutro** [comment]
It'd be great if you could post the docker image as that's how I run gonic. Thanks!

**Comment by sentriz** [comment]
:+1: it should be availible from the :nightly tag after this has completed

https://github.com/sentriz/gonic/actions/runs/2327869607

**Comment by jrabensc** [comment]
Yes, a container would be easier for me as well.

**Comment by sentriz** [comment]
PS, since you'll be upgrading from the 0.14 docker image to nightly, I would recommend backing up your gonic db before you upgrade. just in case :D

**Comment by jrabensc** [comment]
Just tested it, still not scrobbling.

Log:

```
Creating network "gonic_default" with the default driver
Pulling gonic (sentriz/gonic:nightly)...
nightly: Pulling from sentriz/gonic
df9b9388f04a: Pull complete
479466ee7ea4: Pull complete
ed6a81a7d47f: Pull complete
049a639e7d86: Pull complete
Digest: sha256:9a72a1bd99caec332ad16e809faf4d60d62ff04ab2e594831c8bacaa2e24a527
Status: Downloaded newer image for sentriz/gonic:nightly
Creating gonic_gonic_1 ... done
Attaching to gonic_gonic_1
gonic_1  | 2022/05/15 19:52:21 starting gonic v0.14.0
gonic_1  | 2022/05/15 19:52:21 provided config
gonic_1  | 2022/05/15 19:52:21     cache-path      /cache
gonic_1  | 2022/05/15 19:52:21     config-path     
gonic_1  | 2022/05/15 19:52:21     db-path         /data/gonic.db
gonic_1  | 2022/05/15 19:52:21     genre-split     ";"
gonic_1  | 2022/05/15 19:52:21     http-log        true
gonic_1  | 2022/05/15 19:52:21     jukebox-enabled false
gonic_1  | 2022/05/15 19:52:21     listen-addr     :80
gonic_1  | 2022/05/15 19:52:21     music-path      /music
gonic_1  | 2022/05/15 19:52:21     podcast-path    /podcasts
gonic_1  | 2022/05/15 19:52:21     proxy-prefix    
gonic_1  | 2022/05/15 19:52:21     scan-interval   0
gonic_1  | 2022/05/15 19:52:21     tls-cert        
gonic_1  | 2022/05/15 19:52:21     tls-key         
gonic_1  | 2022/05/15 19:52:21     version         false
gonic_1  | 2022/05/15 19:52:21 migration '202110041330' finished
gonic_1  | 2022/05/15 19:52:21 migration '202111021951' finished
gonic_1  | 2022/05/15 19:52:21 migration '202201042236' finished
gonic_1  | 2022/05/15 19:52:21 migration '202202092013' finished
gonic_1  | 2022/05/15 19:52:21 migration '202202121809' finished
gonic_1  | 2022/05/15 19:52:21 migration '202202241218' finished
gonic_1  | 2022/05/15 19:52:21 migration '202204270903' finished
gonic_1  | 2022/05/15 19:52:21 starting job 'podcast refresher'
gonic_1  | 2022/05/15 19:52:21 starting job 'http'
gonic_1  | 2022/05/15 19:52:21 starting job 'session clean'
[...]
gonic_1  | 2022/05/15 19:54:04 response  200  for `/rest/scrobble.view?u=johannes&c=Sublime+Music&f=json&v=1.15.0&s=9OOUdRnY&t=a315e2a505a4ada58f64a5c02b1cf079&id=tr-5430`
gonic_1  | 2022/05/15 19:56:44 response  200  for `/rest/scrobble.view?u=johannes&c=Sublime+Music&f=json&v=1.15.0&s=u9Cf3Clh&t=f8d414e2fbe74b01820ce34b54b65d26&id=tr-5436
```

**Comment by hugalafutro** [comment]
updated to `:nightly`, did incremental scan, unlinked from last.fm, disconnected on last.fm page, then reconnected again (to start from clean slate) and situation seems the same, ie gonic web ui says linked, last.fm page says gonic is linked, but never connected and no scrobbles go through.

here's the log for the few songs I played with `:nightly`

**Comment by sentriz** [comment]
@jrabensc @hugalafutro 

hmm that is weird. though I do see you're both scrobbing with presumably the non-admin user? did you also setup scrobbing for the user account that you're scrobbling with?

eg - the admin user must setup the api key once, and then each user must individually link their accounts on the gonic UI

**Comment by sentriz** [comment]
could you see if there is any output for 

`$ sqlite3 gonic.db "select last_fm_session from users where name='johannes'"`

or 

`$ sqlite3 gonic.db "select last_fm_session from users where name='Sammael666'"`

**Comment by hugalafutro** [comment]
> @jrabensc @hugalafutro
> 
> hmm that is weird. though I do see you're both scrobbing with presumably the non-admin user? did you also setup scrobbing for the user account that you're scrobbling with?
> 
> eg - the admin user must setup the api key once, and then each user must individually link their accounts on the gonic UI
> 

This was it! I was totally unaware of the fact each user needs to log in to gonic web ui and press link, users only ever logged in from android ultrasonic app and admin only ever logged in from web ui but never played any music - hence no scrobbles. 

Scrobbles now coming through for the phone user, thanks for your help!

**Comment by sentriz** [comment]
good to hear it's working :) and btw the reason it's done per-user is that it allows different gonic users to each be connected to their respective lastfm accounts

**Comment by jrabensc** [comment]
Some of my music is scrobbling, so I guess the link is working for me. Just **some** tracks are not working as I described in the other issue. I think it's not working for music which is more obscure or not released on Spotify and so on. Probably some lastfm spam blocking?

**Comment by hugalafutro** [comment]
@jrabensc Did you try searching for the artist that doesn't scrobble on last.fm? Chances are if the last.fm doesn't know it it won't scrobble I'd wager. As for blocking, not sure, I have some albums that are banned from being played live or broadcasted (Eisregen), but last.fm scrobbles them just fine. Last thing I can think of is make sure the files are properly tagged either via Picard or Lidarr (which is what I use).

**Comment by jrabensc** [comment]
Yes I did, the artists are definitively available at lastf.m and are tagged correctly using beets and Musicbrainz as source for the tags. I guess we would need a more verbose debugging option here.

**Comment by sentriz** [comment]
if you're running from nightly and there are no message in your console like "received bad lastfm response" then it means lastfm is happily accepting all your scrobbles and just not rendering them for some reason
