### ISSUE TITLE
Return genre and year tag in getMusicDirectory Child elements

### ISSUE THREAD

**Issue by thirtythreeforty** [sentriz/gonic#223]
The Subsonic API allows optional `genre` and `year` fields in `<Child>` tags. Can these be added to the response?

https://github.com/sentriz/gonic/blob/64d8e014b3f46d43186d9e71eb3072bfad98bb3f/server/ctrlsubsonic/spec/construct_by_folder.go#L41-L61

Clients might cache this and use it, rather than browsing by the dedicated genre API. (I'm writing such a client for Poweramp and all tracks show up as "unknown genre.")

**Comment by sentriz** [comment]
thanks makes sense
