### ISSUE TITLE
feature request: a .gonicignore file to prevent scanning of things

### ISSUE THREAD

**Issue by jrwren** [sentriz/gonic#23]
it would be nice if i could ignore some parts of a tree.

e.g.
.gonicignore file in the root with contents:
```
html
lost+found
templates
```

I have those folders for some other projects and they need not be scanned.

I'd like to implement this and send a PR if you would accept it.

**Comment by sentriz** [comment]
just to clarify. these are `html
lost+found
templates` folders in your music library?

**Comment by jrwren** [comment]
Yes. My music library is on its own fs on my home bad and I have a few other folders in that sir that are not music. One is deep enough with enough files that it would speed up scanning a bit to ignore it.

**Comment by sentriz** [comment]
sorry, I think this feature would add more complexity that it's worth. please re-open if you disagree. 
in the meantime, maybe you could create a new folder, point gonic at it, and symlink your real music dirs inside it?
