### ISSUE TITLE
Volume control not working in Jukebox mode

### ISSUE THREAD

**Issue by Ke1i** [sentriz/gonic#231]
I installed gonic via docker (actually podman) and everything works so far except for volume control - I have to use alsamixer to raise or lower the volume. Is there a variable I can change or settings I can tinker with to have volume control working?
I've tried both Dsub and Ultrasonic clients on Android and changing the volume does nothing.
Here's my podman run command:
```
sudo podman run -dt --name=gonic
    -e TZ=Africa/Nairobi
    -e GONIC_JUKEBOX_ENABLED=true
    -p 4747:80
    -v /home/keli/containers/gonic/db:/data
    -v /home/keli/containers/gonic/cache:/cache 
    -v /media/Music:/music 
    -v /media/Music/Podcasts:/podcasts 
    --device=/dev/snd:/dev/snd 
    --group-add=audio 
docker.io/sentriz/gonic:latest
```

**Comment by Ke1i** [comment]
Just opened the logs and I can see the 'setGain' commands when I press the volume buttons, so the commands are being sent but it does nothing to the actual volume. Here's a sample output of said logs:
```
2022/07/19 09:23:26 response  200  for `/rest/jukeboxControl.view?action=status&u=admin&c=Ultrasonic&f=json&v=1.15.0&t=006cd094bf0350433b466ffa1762e0f5&s=77EF1F06A58AF1729C74DB23CB910E1D`
2022/07/19 09:23:28 response  200  for `/rest/jukeboxControl.view?action=stop&u=admin&c=Ultrasonic&f=json&v=1.15.0&t=db00e1063e5992756000634d0499662f&s=AB934D72EBF38B143A8DD2EB0280890A`
2022/07/19 09:23:37 response  200  for `/rest/jukeboxControl.view?action=setGain&gain=0.9&u=admin&c=Ultrasonic&f=json&v=1.15.0&t=c6afdb70c1ed4759196be11b0a38d4dc&s=7B69FC796D849B8D3AAE7CA4C9C3AC04`
```

**Comment by sentriz** [comment]
hey, volume control for jukebox is not implemented yet. the jukebox has a static gain of 0.9 out of 1

definitely it would be something worth added. i may also be added in #221, but not sure

either way, i'll try get this in before the next release

**Comment by sentriz** [comment]
closing in favour of #211 :+1:
