### ISSUE TITLE
Album art from music meta tag

### ISSUE THREAD

**Issue by hellojaccc** [sentriz/gonic#234]
Hi, thanks for lightweight server. it's great

I tried on many clients, but it seems that it doesn't read album art. Is it possible to add that feature? It's basic feature in my opinon.

**Comment by hellojaccc** [comment]
Ah sorry, i didnt read README carefully. I need to add folder.jpg to have album art. 

Is it possible to read album art from meta tag? It'd be very useful.

**Comment by sentriz** [comment]
nice that you got it working :+1:  we have an issue for that one already #11
