### ISSUE TITLE
Subdirs in album dirs break scanning

### ISSUE THREAD

**Issue by dexterlb** [sentriz/gonic#235]
I have the following directory structure:

```
artists
└─ Some Artist/
    └─ Some Album/
        ├─ cover.png
        ├─ lyrics/
        │    ├─ Song 1.txt
        │    └─ Song 2.txt
        ├─ Song 1.flac
        └─ Song 2.flac
```
Currently, the scanner discovers each album twice: we have `{LeftPath: "artists/Some Artist", RightPath: "Some Album"}` and `{LeftPath: "artists/Some Artist/Some Album", RightPath: "lyrics"}` - apparently the lyrics directory is discovered as a separate album.

This seems to break some things like fetching cover art, since gonic seems to be looking for `cover.png` in `lyrics/` in some cases.

Is this a bug or a feature? If the latter, is there an easy way around it without changing my library structure?

**Comment by sentriz** [comment]
that should work just fine. are running from source or docker? er something else?

**Comment by sentriz** [comment]
hi! going to make the assumption that you're running the latest stable release. it works for me on master (or the docker nightly image)

or the next stable release which is hopefully coming soon

please reopen if you're running nightly though. thanks!
