### ISSUE TITLE
New release request

### ISSUE THREAD

**Issue by zpuskas** [sentriz/gonic#245]
Last release was almost a year ago. Since then many features have been added, so a new release would be in order. This would also useful for distro maintainers.

**Comment by sentriz** [comment]
coming soon hopefully, just wanna get these out frist

https://github.com/sentriz/gonic/labels/before%20next%20release

a couple are issues, a couple are PRs

**Comment by sentriz** [comment]
also if anyone reading this is on 0.14, it would be very handy if you try out the master or :nightly builds. that will be close to the 0.15 release - so would be great to get some people to try it out and see are there any issues when the db migrations run, or any issues after a scan, etc

thanks!

p.s. maybe back up your database first if you try it :grin:

**Comment by sentriz** [comment]
also if you didn't know, the next release is tracked here https://github.com/sentriz/gonic/pull/218

**Comment by sentriz** [comment]
done 👍
