### ISSUE TITLE
Transcoding support

### ISSUE THREAD

**Issue by spijet** [sentriz/gonic#25]
Hello @sentriz!

First of all, thank you so much for making this awesome server! It works wonders in low-CPU/RAM environments, compared to traditional JVM-powered Subsonic implementations.

But I think there's still one thing that many people would love to see: transcoding support. Are there any plans for implementing it? If not (or if you don't have enough time for it), will you accept any PRs that implement this?

**Comment by DOFfactory** [comment]
Please make sure to introduce Opus transcoding as well!

**Comment by spijet** [comment]
I was thinking about generic transcoding support, similar to what was made in SubSonic and its forks (server selects one of the transcoding rules and invokes a command that takes source file as an argument, streaming encoded data to it's standard output), but with caching support (so that server doesn't have to re-encode frequently accessed tracks every time). Opus (and every other streamable format really) fits this idea pretty well. :)

**Comment by DOFfactory** [comment]
looking forward to the implementation

**Comment by sentriz** [comment]
this is next on my TODO after 1 or 2 more bug fixes here in the issues

**Comment by spijet** [comment]
I've managed to write some (quite hacky) code to separate `/stream` and `/download` endpoints, and added transcoding functions (with hard-coded FFmpeg profiles) with file caching. It actually works much better than I expected! Had to raise HTTP write timeout to ~80 seconds, though, or gonic would stop streaming the response (uncached track) before FFmpeg finishes.

I'll try to wrap it up into a proper git-fork and upload it as a separate branch, so you can take a look at this mess. :stuck_out_tongue:

**Comment by sentriz** [comment]
oooh very nice! I'm looking forward to seeing it

**Comment by spijet** [comment]
Uploaded everything and filed a PR with my edits: #35. Feedback is really appreciated! :)

**Comment by sentriz** [comment]
done! thank you to @spijet
