### ISSUE TITLE
Support exclude file filter

### ISSUE THREAD

**Issue by ReinforceZwei** [sentriz/gonic#253]
## Current
There are insrumental songs when browsing folders.
![image](https://user-images.githubusercontent.com/39955851/200287258-473b345a-dc9d-4a79-a4f0-cfa90218dd9e.png)

I don't want insrumental songs be added to or shown in the library, but there's no filter available for excluding those songs.

## What I want
- Add a list field (or regex field)
- User can add keywords to the list (or specify a regex)
- If the file name contains keywords (or the regex matches), exclude the file in the library

**Comment by sentriz** [comment]
this seems out of the scope of the project. do you know of any other examples of music servers doing this? why not just delete those files?

**Comment by ReinforceZwei** [comment]
Yes, Airsonic (and Airsonic advanced) has this option to exclude file by regex.
![image](https://user-images.githubusercontent.com/39955851/200294155-ddd9ca02-0191-4407-97de-813166703abd.png)

**Comment by bartmans** [comment]
+1 for this, not just filepatterns, but directories also. My Synology adds an extra (normally hidden dir (@eadir). Also for #recycle or dir's created by Goodsync syncing tool etc.
