### ISSUE TITLE
Tracks missing

### ISSUE THREAD

**Issue by Kabsky** [sentriz/gonic#26]
Using the latest docker version (0.4.3), scanner report:
2019/12/16 14:25:28 finished scan in 379.254659ms, +226/435 tracks (0 err)

But only 209 track are added to the database.
The folder structure is: Artist/Album/Tracks

What seem to not work correctly are the 2 folders were i put various mp3.
For those 2 folders, sometimes 2 songs are added to the database, sometimes more, never all.

Thanks for gonic !

**Comment by sentriz** [comment]
hi. did you see an errors in the logs while scanning?

**Comment by Kabsky** [comment]
Hi,

I hope those are the log you want:

gonic        | 2020/01/24 10:56:59 response  303  for `/admin/start_scan_do`
gonic        | 2020/01/24 10:57:00 finished scan in 320.935929ms, +226/435 tracks (0 err)
gonic        | 2020/01/24 10:57:00 response  200  for `/admin/home`
gonic        | 2020/01/24 10:57:00 finished clean in 13.153914ms, -0 tracks

On front page in the stats section:
artists: | 9
albums: | 18
tracks: | 209

**Comment by sentriz** [comment]
can you show me what sort of file types you have in your music collection? maybe there are files types that gonic doesn't know about get

`find /path/to/my/music -type f | awk -F. '!a[$NF]++{print $NF}'`

**Comment by Kabsky** [comment]
```
find /data/music/ -type f | awk -F. '!a[$NF]++{print $NF}'
mp3
png
jpg
```

**Comment by sentriz** [comment]
hi! i think this may be fixed now. stupidly i was doing a join instead instead of left join to get track counts a while ago, hiding results from some queries

**Comment by Kabsky** [comment]
hello, i have updated to 0.8.8.
Delete the whole config to try, but always the same behavior: "scan full" = 209 tracks.
Another scan and bam it display 377 tracks until i refresh the page and came back to 209 tracks :(

**Comment by sentriz** [comment]
interesting. sounds the exact same as #63 gonna close in favour of that. btw if anyone is willing to help debug this more. an idea might be to email me link to a portion of tracks (say with firefox send or something) some that scan correctly, and some that dont. i can try to reproduce this then. thanks!

**Comment by sentriz** [comment]
should be fixed now! thanks for all your help
