### ISSUE TITLE
User's "Download Role" is hardcoded to disabled

### ISSUE THREAD

**Issue by spijet** [sentriz/gonic#264]
It seems that gonic includes the `downloadRole` flag for user roles in it's spec:
https://github.com/sentriz/gonic/blob/44800e964d27af44ed94d4365df5fa04525b405f/server/ctrlsubsonic/spec/spec.go#L243

But at the moment there seems to be no way of actually enabling this role for certain users. Instead, gonic just returns `false` in this field. This makes some clients (e.g. Jamstash) think that the user is not allowed to download songs as files (without transcoding) and disable the "download" button whatsoever.
Would it be hard to add a way to enable this role per-user, e.g. by adding a control toggle in admin area?

**Comment by spijet** [comment]
Here's the relevant piece of code in Jamstash source:

https://github.com/tsquillario/Jamstash/blob/280d5ffb261f0282f4f815cfc8398d498b32b9da/app/common/main-controller.js#L241-L259

**Comment by sentriz** [comment]
ah interesting. well since we currently already allow anyone to use download.view, how about we hardcode it to true? to match the actual permissions

then later on we follow up with toggles with #156

**Comment by spijet** [comment]
Sounds reasonable. Thank you for quick fix! 🧡
