### ISSUE TITLE
Podcast episode w/o audio causes segfault

### ISSUE THREAD

**Issue by brian-doherty** [sentriz/gonic#269]
2022/12/09 11:41:27 failed to find audio in feed item, skipping
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xc8 pc=0x8e3872]

goroutine 50133 [running]:
go.senan.xyz/gonic/podcasts.(*Podcasts).AddNewEpisodes(0xc0002c2e10, 0xc0003906c0, {0xc000bae800?, 0xc7, 0x100})
	/home/brian/gonic/podcasts/podcasts.go:173 +0x212
go.senan.xyz/gonic/podcasts.(*Podcasts).refreshPodcasts(0xc0001c1e10?, {0xc0000bc1c0, 0x7, 0x0?})
	/home/brian/gonic/podcasts/podcasts.go:301 +0x2df
go.senan.xyz/gonic/podcasts.(*Podcasts).RefreshPodcasts(0xc0002c2e10)
	/home/brian/gonic/podcasts/podcasts.go:286 +0xdd
go.senan.xyz/gonic/server.(*Server).StartPodcastRefresher.func1()
	/home/brian/gonic/server/server.go:398 +0x98
go.senan.xyz/gonic/server.(*Server).StartPodcastRefresher.func2()
	/home/brian/gonic/server/server.go:406 +0x43
github.com/oklog/run.(*Group).Run.func1({0xc000442f00?, 0xc0002a8048?})
	/home/brian/go/pkg/mod/github.com/oklog/run@v1.1.0/group.go:38 +0x2f
created by github.com/oklog/run.(*Group).Run
	/home/brian/go/pkg/mod/github.com/oklog/run@v1.1.0/group.go:37 +0x22a

AddEpisode returned nil, nil in this case which shouldn't be hit. Recommend it return an error of your choice instead so that the caller doesn't assume the episode returned is non nil.

**Comment by sentriz** [comment]
thanks, how does this look? https://github.com/sentriz/gonic/commit/b47c880ea5ffd357878b7617c3493d7b1f48f4cf

**Comment by brian-doherty** [comment]
Looks great, thanks!
