### ISSUE TITLE
Follow Symlinks in GONIC_MUSIC_PATH

### ISSUE THREAD

**Issue by Flameborn** [sentriz/gonic#27]
Currently, Gonic does not detect and follow symbolic links pointing to directories.

Not having the ability to specify multiple paths, e.g. one for audio books, music, podcasts, etc, it is currently not possible to add multiple sources.

Implementing symbolic links support  would be one way of allowing this.

**Comment by sentriz** [comment]
should be fixed now. try v0.6.1

can reopen if somethings gone wrong. thanks!

**Comment by Flameborn** [comment]
Thank you very much for adding this.

The symlinks seem to work fine, however at the moment I am getting:

_panic: runtime error: invalid memory address or nil pointer dereference_

I am not sure if it is because of a folder, or a tag read error (those can cause a similar panic).

**Comment by sentriz** [comment]
hmm. could you post the full traceback with the panic please?

**Comment by Flameborn** [comment]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x88 pc=0x377a0c]
goroutine 70 [running]:
senan.xyz/g/gonic/scanner.(*Scanner).callbackPost(0x1995a10, 0x19715c0, 0xb, 0x18ee2d0, 0x0, 0x0)
        /home/alarm/git/gonic/scanner/scanner.go:232 +0x70
github.com/karrick/godirwalk.walk(0x19715c0, 0xb, 0x18ee2d0, 0x1be1f88, 0xb, 0x0)
        /home/alarm/go/pkg/mod/github.com/karrick/godirwalk@v1.10.12/walk.go:308 +0x30c
github.com/karrick/godirwalk.walk(0x19b8fa7, 0x5, 0x1a13fe0, 0x1be1f88, 0x0, 0x0)
        /home/alarm/go/pkg/mod/github.com/karrick/godirwalk@v1.10.12/walk.go:280 +0x258
github.com/karrick/godirwalk.Walk(0x19b8fa7, 0x5, 0x1830788, 0x12, 0x9c14a0)
        /home/alarm/go/pkg/mod/github.com/karrick/godirwalk@v1.10.12/walk.go:220 +0x13c
senan.xyz/g/gonic/scanner.(*Scanner).Start(0x1995a10, 0x0, 0x0)
        /home/alarm/git/gonic/scanner/scanner.go:88 +0x1c4
senan.xyz/g/gonic/server/ctrladmin.(*Controller).ServeStartScanDo.func1.1(0x19abc00)
        /home/alarm/git/gonic/server/ctrladmin/handlers.go:265 +0x28
created by senan.xyz/g/gonic/server/ctrladmin.(*Controller).ServeStartScanDo.func1
        /home/alarm/git/gonic/server/ctrladmin/handlers.go:264 +0x2c
```

**Comment by sentriz** [comment]
hi!
I can reproduce this. while scanning I keep track of the tree using a stack, pushing for dirs, and popping when we leave them. symlinks to dirs aren't being pushed currently, so the nil pointer happens when the pop happens but nothing there.

i've asked a quesstion about this here

https://github.com/karrick/godirwalk/issues/44

**Comment by karrick** [comment]
https://github.com/karrick/godirwalk/pull/45

**Comment by karrick** [comment]
The following tag has the feature request, however I have been testing a performance improvement branch, and am about ready to release that, but wanted to get this feature out for you first.

https://github.com/karrick/godirwalk/releases/tag/v1.15.0

**Comment by sentriz** [comment]
thank you for that karrick. comment left here:

https://github.com/karrick/godirwalk/pull/45#issuecomment-579365810

not sure if you get notified for closed PRs

**Comment by karrick** [comment]
@sentriz, thanks for pointing out the `path` not getting set bug. I fixed it and did a code audit to make sure that `path` was set every time a `Dirent` is created.

Please give https://github.com/karrick/godirwalk/releases/tag/v1.15.2 a try.

**Comment by sentriz** [comment]
@Flameborn could you try gonic `v0.6.2` if you have a chance?

**Comment by Flameborn** [comment]
Just finished scanning my library and all seems to be well: symlinks work as expected, and there are no panics.
