### ISSUE TITLE
Gonic service does not start after upgrade

### ISSUE THREAD

**Issue by enolp** [sentriz/gonic#272]
Hi, I have issues getting gonic running after upgrading from 0.14.0v to 0.15.0v. Here is the systemd service log:

> avi 12 23:18:21 user systemd[1]: Started gonic service.
> avi 12 23:18:21 user gonic[1219]: SIGILL: illegal instruction
> avi 12 23:18:21 user gonic[1219]: PC=0x4102ef m=0 sigcode=2
> avi 12 23:18:21 user gonic[1219]: instruction bytes: 0xff 0xff 0xff 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0
> avi 12 23:18:21 user gonic[1219]: goroutine 1 [running, locked to thread]:
> avi 12 23:18:21 user gonic[1219]: runtime.chanrecv(0x0, 0x0, 0x0)
> avi 12 23:18:21 user gonic[1219]:         runtime/chan.go:508 +0xef fp=0xc0000427e0 sp=0xc000042750 pc=0x4102ef
> avi 12 23:18:21 user gonic[1219]: runtime.goexit()
> avi 12 23:18:21 user gonic[1219]:         runtime/asm_amd64.s:1594 +0x1 fp=0xc0000427e8 sp=0xc0000427e0 pc=0x46fa61
> avi 12 23:18:21 user gonic[1219]: goroutine 2 [runnable]:
> avi 12 23:18:21 user gonic[1219]: runtime.forcegchelper()
> avi 12 23:18:21 user gonic[1219]:         runtime/proc.go:293 fp=0xc000042fe0 sp=0xc000042fd8 pc=0x441f80
> avi 12 23:18:21 user gonic[1219]: runtime.goexit()
> avi 12 23:18:21 user gonic[1219]:         runtime/asm_amd64.s:1594 +0x1 fp=0xc000042fe8 sp=0xc000042fe0 pc=0x46fa61
> avi 12 23:18:21 user gonic[1219]: created by runtime.init.6
> avi 12 23:18:21 user gonic[1219]:         runtime/proc.go:290 +0x25
> avi 12 23:18:21 user gonic[1219]: goroutine 3 [runnable]:
> avi 12 23:18:21 user gonic[1219]: runtime.gcenable.func1()
> avi 12 23:18:21 user gonic[1219]:         runtime/mgc.go:178 fp=0xc0000437e0 sp=0xc0000437d8 pc=0x423420
> avi 12 23:18:21 user gonic[1219]: runtime.goexit()
> avi 12 23:18:21 user gonic[1219]:         runtime/asm_amd64.s:1594 +0x1 fp=0xc0000437e8 sp=0xc0000437e0 pc=0x46fa61
> avi 12 23:18:21 user gonic[1219]: created by runtime.gcenable
> avi 12 23:18:21 user gonic[1219]:         runtime/mgc.go:178 +0x6b
> avi 12 23:18:21 user gonic[1219]: goroutine 4 [runnable]:
> avi 12 23:18:21 user gonic[1219]: runtime.gcenable.func2()
> avi 12 23:18:21 user gonic[1219]:         runtime/mgc.go:179 fp=0xc000043fe0 sp=0xc000043fd8 pc=0x4233c0
> avi 12 23:18:21 user gonic[1219]: runtime.goexit()
> avi 12 23:18:21 user gonic[1219]:         runtime/asm_amd64.s:1594 +0x1 fp=0xc000043fe8 sp=0xc000043fe0 pc=0x46fa61
> avi 12 23:18:21 user gonic[1219]: created by runtime.gcenable
> avi 12 23:18:21 user gonic[1219]:         runtime/mgc.go:179 +0xaa
> avi 12 23:18:21 user gonic[1219]: rax    0xc00006a000
> avi 12 23:18:21 user gonic[1219]: rbx    0x0
> avi 12 23:18:21 user gonic[1219]: rcx    0x1
> avi 12 23:18:21 user gonic[1219]: rdx    0x1
> avi 12 23:18:21 user gonic[1219]: rdi    0x1
> avi 12 23:18:21 user gonic[1219]: rsi    0xc0000071e0
> avi 12 23:18:21 user gonic[1219]: rbp    0xc000042770
> avi 12 23:18:21 user gonic[1219]: rsp    0xc000042750
> avi 12 23:18:21 user gonic[1219]: r8     0xa1e19ea722f38801
> avi 12 23:18:21 user gonic[1219]: r9     0xf91320
> avi 12 23:18:21 user gonic[1219]: r10    0xa
> avi 12 23:18:21 user gonic[1219]: r11    0x0
> avi 12 23:18:21 user gonic[1219]: r12    0x7ffe7fc2ec58
> avi 12 23:18:21 user gonic[1219]: r13    0x40
> avi 12 23:18:21 user gonic[1219]: r14    0xc0000061a0
> avi 12 23:18:21 user gonic[1219]: r15    0x7fd9cb023602
> avi 12 23:18:21 user gonic[1219]: rip    0x4102ef
> avi 12 23:18:21 user gonic[1219]: rflags 0x10246
> avi 12 23:18:21 user gonic[1219]: cs     0x33
> avi 12 23:18:21 user gonic[1219]: fs     0x0
> avi 12 23:18:21 user gonic[1219]: gs     0x0
> avi 12 23:18:21 user systemd[1]: gonic.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
> avi 12 23:18:21 user systemd[1]: gonic.service: Failed with result 'exit-code'.`

I don't know what is causing this. I'm using Arch Linux

**Comment by sentriz** [comment]
strange, how did you still gonic?

**Comment by enolp** [comment]
Sorry, but I don't understand your question. Do you mean how do I run gonic? I run it trough a systemd service which it's execution argument is: `/usr/bin/gonic -config-path /var/lib/gonic/config`. That's all I know

**Comment by sentriz** [comment]
oh sorry, i meant to say how did you install gonic. eg from the AUR, or a `go install`, or something else?

**Comment by enolp** [comment]
Yeah, I installed gonic through AUR when 0.14v was available and updated as soon as 0.15v got released.

**Comment by sentriz** [comment]
interesting, can you show me some info about your system? and the gonic binary?

eg

```
$ uname -a
$ file $(which gonic)
```

**Comment by enolp** [comment]
`uname -a`
> Linux HOSTER 6.0.12-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 08 Dec 2022 11:03:38 +0000 x86_64 GNU/Linux

`file $(which gonic)`
> /usr/bin/gonic: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=XXX, for GNU/Linux 4.4.0, stripped

I've stripped sha1 BuildID for security reasons

**Comment by sentriz** [comment]
ok thanks. very strange. we have very similar machines, and the AUR package works fine for me. 

maybe could you try a clean rebuild? not sure what AUR helper your using, if any, but with yay it would be

`yay --rebuild gonic` i think
