### ISSUE TITLE
Possible bug found : media type is "al"

### ISSUE THREAD

**Issue by garfieldairlines** [sentriz/gonic#274]
I am using gonic with bonob and I noticed that on 5+ minute tracks it suddenly skips and plays the next track in the list. If I am lucky enough I can see on the Android App that there is a "problem with the file encoding".

Except it isn't the case : I can use gonic + Symfonium or Sonixd without any tracks skipping or stopping.
Using airsonic-advanced with the built in sonos integration also works perfectly on the sonos system.

No extra compression or transcoding is being used in any case. Sadly it's quite hard to get logs since that system isn't really open source friendly…

**Comment by sentriz** [comment]
hm it looks like bonob is asking gonic to play an album, not a track. you should see in your logs stream.view?id=al-123

**Comment by sentriz** [comment]
ok nice, then I added an empty lyrics.view, let me know if that helps

**Comment by sentriz** [comment]
hm, I wasn't able to reproduce it. Let the Rhythm was playing fine for me with sonixd, all the way through. 

however I just made a change to master, can you try build again with that? or, if you're using docker try the ":nightly" tag when [this job is done](https://github.com/sentriz/gonic/actions/runs/3782885274)

**Comment by sentriz** [comment]
ah, you're using the "download" feature on an album. i don't think you mentioned that. anyway that will give the "media type is unknown: "al"" error, since gonic doesn't support downloading full albums. 

it shouldn't affect playback so we can ignore it for now. can you send me the "In My Mind" track has the playback issues?

**Comment by sentriz** [comment]
with the original file I ran with through ffprobe and it gave some sort of corruption error. so id say reencoding at the same bitrate will also fix it

however , Google chrome (raw, without sonixd) can also play the original file for me. so I'll so some investigation with the react audio player that sonixd uses + gonic as a raw file server

**Comment by sentriz** [comment]
hey i did some more testing, for example with works.flac and noworks.flac (let the rhythm and in my mind)


https://user-images.githubusercontent.com/6832539/209599963-820b61ca-52d8-4423-b19e-7ddf85cc3ce5.mp4

it was a sort of minimal reproduction test with a simple go http fileserver that gonic uses, and react-audio-player that sonixd uses

as expected works.flac works, and noworks.flac does not work. but what's strange is while react-audio-player's onerror hook runs for noworks.flac, is doesn't print anything useful. just an error object for noworks.flac and nothing else - that i can find

the project is [here](share.senan.xyz/gonic-react-audio-corruption-test.zip) if anyone is interested (just needs a `go run main.go` then visit `http://localhost:3000/?p=/f/works.flac` or `http://localhost:3000/?p=/f/noworks.flac`) maybe you will have better luck than me

though for the meantime @garfieldairlines I would just recommend running some sort of validator on your audio files. maybe [badfiles for beets](https://docs.beets.io/en/v1.4.5/plugins/badfiles.html), or maybe ffprobe which shows the error: 

![image](https://user-images.githubusercontent.com/6832539/209601181-632bfc70-8501-47f7-825f-bd56872abce8.png)

**Comment by sentriz** [comment]
howdy, there is an issue open for custom transcode profiles :point_right:  #244 

but in the meantime as you mentioned, it should be possible to 
- clone the repo
- edit transcode.go
- docker build -t <tag> .
- run with new <tag> instead
