### ISSUE TITLE
beets.db support

### ISSUE THREAD

**Issue by Wmartin417** [sentriz/gonic#275]
Would be very nice to be able to use the beets.db for music, as [sound](https://github.com/hednowley/sound/), [ampache](https://ampache.org/), and [beetstream](https://github.com/BinaryBrain/Beetstream) have implemented.

I prefer to keep my files untagged directly and just parse the beets.db if possible. Only downside with the ones that I listed, sound doesn't seem to be maintained any longer, beetstream is missing a lot of the subsonic api endpoints, and I believe ampache currently has a bug with using beets.

**Comment by sentriz** [comment]
sorry, while i agree it would be nice (i use beets myself :+1: ), it would be such a huge change that maybe it should be a fork of gonic or something. i want to try and keep gonic simple
