### ISSUE TITLE
Log location?

### ISSUE THREAD

**Issue by cristiano5** [sentriz/gonic#279]
I'm using Gonic via docker on Unraid and would like to have swag scan the log file for any failed login attempts so I can block the IP automatically. I see that http logging is enabled by default but I can't find the log file location though. Would be nice to have it in the data folder

**Comment by sentriz** [comment]
gonic doesn't log to a file, only stderr. but maybe you could start gonic with a wrapper to write to a file. eg 


`docker run -v $PWD/logs:/logs sentriz/gonic 'sh' '-c' 'gonic 2>&1 | tee /logs/gonic'`

will but logs in `$PWD/logs/gonic`
