### ISSUE TITLE
Should "most played" list divide by track count?

### ISSUE THREAD

**Issue by brian-doherty** [sentriz/gonic#285]
The "most played" list tends to overweight really long albums (box sets especially) because it is sorted by track plays and they have so many track. I submit as a question -- should it divide by track count instead, to give a notion of which _albums_ you play the most?

**Comment by sentriz** [comment]
good idea :+1: or even it could be based on the track length. so you're sorting by most hours listened, regardless of how many tracks. eg i have some albums that are an hour long with only 2 tracks

**Comment by brian-doherty** [comment]
Yeah I could see an argument for either.
