### ISSUE TITLE
Add m4b support

### ISSUE THREAD

**Issue by Flameborn** [sentriz/gonic#29]
Currently, m4b audio books do not seem to be picked up by a Gonic scan.

Taglib has support for their metadata.

Would it be possible to support these files in the future please?

**Comment by sentriz** [comment]
yes, should hopefully be as simple as adding to this section: 

https://github.com/sentriz/gonic/blob/master/mime/mime.go

(list of file extensions to mime types)

 I'm only on my phone now unfortunately. I'll check it out in my morning

**Comment by Flameborn** [comment]
Adding _m4b_ to the mimetypes indeed makes m4b files available in the scan.

When I tried before submitting the issue, I did not recreate the database, so they were not picked up afterwards, which must've been something to do with the symlinks issue earlier.

Should I send a PR?

**Comment by sentriz** [comment]
hey I'd be happy to accept a PR. i can also do it myself if that's easier. according to google to corresponding mime type is `audio/mp4a-latm`, but didn't find too much about that.

**Comment by Flameborn** [comment]
I think the mimetype you mentioned is for the _mp4_ format. M4b should be _audio/m4b_, similarly to m4a.

Play:Sub seems to recognize it, according to my tests.

I'll send in a PR in a few minutes.
