### ISSUE TITLE
What is the purpose of internet_radio_stations configuration information?

### ISSUE THREAD

**Issue by wrwetzel** [sentriz/gonic#291]
I entered a couple of radio-station streams in the "internet_radio_stations" section of the Gonic configuration web page. I could find no mention of them any any of the Android subsonic-protocol clients I examined: Subtracks, Symphonium, Subsonic, Substreamer, and Ultrasonic. What is the purpose of this option? What clients support it?

I explored several subsonic servers including Navidrome and others. Gonic is the simplest and the best. It just works and I have settled on it for my home music server.

Thanks,
Bill

**Comment by sentriz** [comment]
hello, maybe @brian-doherty can help here?

**Comment by brian-doherty** [comment]
The APIs are documented in the official Subsonic spec at http://www.subsonic.org/pages/api.jsp .
I use DSub and it makes use of them. I'm not sure about other clients. I like DSub because it also supports gapless playback.

**Comment by wrwetzel** [comment]
Thanks very much for getting back and for the explanation. I'll have a look at DSub.

**Comment by sentriz** [comment]
@wrwetzel if you didn't know there are binaries for dsub available [here](https://github.com/daneren2005/Subsonic/releases) if you just want to try it out. or support the author with the google play version if you like it then :grin:

**Comment by wrwetzel** [comment]
Thanks for the pointer. No, I was not aware of the binaries. I'm glad I tried it before buying. Indeed it does support the internet radio category but I could find no way to browse folders hierarchically. Top level folders were commingled with ones below the top level in a flat display. I suspect I'll stay with with "HiFi Cast" app, which does support folder browsing. Having internet radio integrated would be convenient but there are plenty of internet radio apps.
