### ISSUE TITLE
Compilation errors on FreeBSD

### ISSUE THREAD

**Issue by thesnallygaster** [sentriz/gonic#293]
Hi,
When compiling on FreeBSD I get these errors:
`scanner/scanner.go:641:10: stat.Ctim undefined (type *syscall.Stat_t has no field or method Ctim)
scanner/scanner.go:645:30: stat.Ctim undefined (type *syscall.Stat_t has no field or method Ctim)`
This's been happening since this commit: [https://github.com/sentriz/gonic/commit/14a266842600fae27a134590d69542dc5d0d2cfc](url)
I can fix this by replacing Ctim with Ctimespec but as I don't really know how Go works I'm not able to change those things per OS at the moment as it seems that different OSes have different fields/methods defined in *syscall.Stat_t

**Comment by sentriz** [comment]
strage. we were assuming ctime was create time, but it's not. it's change time. same as stat.ModTime()

so it looks like we dont need that syscall stuff
