### ISSUE TITLE
FLAC compression 8 - error could not read tag

### ISSUE THREAD

**Issue by BigB84** [sentriz/gonic#297]
Hi,

I encouraged strange problem while converting wav 16 bit 48k to flac. 
Firstly I used the highest possible value **8** but gonic  threw error - couldn't read tags.

If I left default compression, everything was cool, gonic didn't threw anything.

I tried multiple gonic versions [>= 0.14.0 and master]

Could someone reproduce it?

If I'm not wrong you could just use some opus for tests as they are more likely to be 48k or resample with sox.

**Comment by sentriz** [comment]
hi, can you email me the source wav file and the ffmpeg/flac/sox/whatever command you're using? email is available on my profile. thanks!
