### ISSUE TITLE
importing m3u playlists with http links

### ISSUE THREAD

**Issue by AndrNizov** [sentriz/gonic#298]
Hi!
I've been experimenting with torrent hi-res audio, using [Torrserve](https://github.com/YouROK/TorrServe) a golang app that process magnet-url or torrent file and serves it's content via http. Works perfectly with VLC, i.e. upload a magnet-link and receive an m3u playlist.
But I've been thinking how to import that m3u playlist into streaming server to have a more convenient control from android client and tried gonic (v0.15.0 AUR based for Arch).
Unfortunately gonic couldn't import these m3u playlists, example is below,
```
#EXTM3U
#EXTINF:0,01. Tigerforest - Bellefontaine (Original Mix).flac              
http://192.168.0.197:8090/stream/01.%20Tigerforest%20-%20Bellefontaine%20%28Original%20Mix%29
.flac?link=579333af9ac08d38ff92cea1bf085186e292d57d&index=1&play
#EXTINF:0,02. Dharma Frequency - Floating Dreams (Original Mix).flac
http://192.168.0.197:8090/stream/02.%20Dharma%20Frequency%20-%20Floating%20Dreams%20%28Origin
al%20Mix%29.flac?link=579333af9ac08d38ff92cea1bf085186e292d57d&index=2&play
#EXTINF:0,03. Elmara - Northern Lights (Original Mix).flac
http://192.168.0.197:8090/stream/03.%20Elmara%20-%20Northern%20Lights%20%28Original%20Mix%29.
flac?link=579333af9ac08d38ff92cea1bf085186e292d57d&index=3&play   
```
http://192.168.0.197:8090 is my instance of Torrserve running on the same machine. 
Am I doing something wrong, or this feature is not supported?

**Comment by sentriz** [comment]
hi, sorry i don't think it's possible. the playlists are meant to just be paths to local file that gonic has already scanned. it can't just fetch files over the network and serve them - subsonic clients will expect that each item in the playlist has metadata, links to the album, links to the artist, etc
