### ISSUE TITLE
Most of my music embedded tags are in Chinese

### ISSUE THREAD

**Issue by jiaoting** [sentriz/gonic#301]
Compared with airsonic, the number of music scanned is the same, but the musicians and albums are different, and the music information is missing a lot, and the album cover cannot be scanned. I use the embedded music information.
![b9d3c72d52195cd7f8ad9d9ed8e1b4d](https://user-images.githubusercontent.com/12553424/223001712-0ba40c86-da6b-46bf-b8ca-31d6caba22c0.jpg)
![783e375bd3bffba59c6cf4444b3881f](https://user-images.githubusercontent.com/12553424/223001721-39297ccd-598c-464c-9d76-683f18dc3573.jpg)

**Comment by jiaoting** [comment]
Most of my music embedded tags are in Chinese

**Comment by sentriz** [comment]
hi! can you email me some example audio files? (email is in profile)

then, a screenshot of how they look in gonic, and also a screenshot of how they look in airsonic?

thanks :+1:

**Comment by jiaoting** [comment]
> hi! can you email me some example audio files? (email is in profile)
> 
> then, a screenshot of how they look in gonic, and also a screenshot of how they look in airsonic?
> 
> thanks 👍

I send email

**Comment by sentriz** [comment]
hey, how is it looking now?
