### ISSUE TITLE
About the files stored in the /covers directory

### ISSUE THREAD

**Issue by awsms** [sentriz/gonic#302]
I was wondering if they were fetched externally, and if yes from which sources?
Anyway I really don't see the point of caching jpg=>png transcodes, since it's just bloat...... my folder is already >200MB while I just set up gonic

**Comment by sentriz** [comment]
the covers come from your local filesystem. eg folder.png files that you have. except the subsonic api allows clients to request them at any size like 50x50, 800x800. we were thinking it makes sense to cache these resizes. what do you think?

**Comment by awsms** [comment]
ok, i see now

> eg folder.png files that you

i only use jpegs, compressed with jpegoptim so they're very rarely >600kb
caching image does make sense indeed, but why caching pngs? i see it like caching mp3=>wav transcodes

in my /var/gonic/cache/covers folder, running ```du -ch *png``` will give me 554MB

now if I batch convert them to jpegs with ffmpeg (
``` for f in *png; ffmpeg -i $f -vf scale="iw/1:ih/1" -q:v 2 2/$f.jpg -qscale 0; end```  )

and run ```du -ch *jpg```, I get 132MB

this png was https://rimgo.esmailelbob.xyz/fOvseuo.png

here is the jpg that came out https://rimgo.totaldarkness.net/J3wUG6l.jpg

almost a third of the size less, for the same picture quality

**Comment by sentriz** [comment]
its not so much about storage, it's about response times. a client can request a list of albums, 

and for one each request getCoverArt?size=300x300

another client and come along and request a bunch of getCoverArt?size=30x30

if we don't cache those then we have to do the resize operation again and again which is cpu intensive (esp for someone runnning on a raspberry pi for example) and it slows the loading of the page

could could also say why don't we just serve the original image if they're so small (in your case) but some clients break if they receive an image larger then they requested

**Comment by awsms** [comment]
yep i get the argument behind storing several res of the same file, but could it be disabled in the future so covers are served as-is, or even transcoded on the go on every request for servers that "hardwarly" speaking are able to do this with no problem?

maybe as an option in the configfile

**Comment by sentriz** [comment]
hm yeah maybe it makes sense as a config option. though maybe we need a nicer caching abstraction. things we cache right now are transcoded audio, cover images, artist images. but i also want to cache artist infos taken from lastfm etc. 

would be nice to have a cache abstraction where the user can decide what they want to cache, and where they want to cache it. (nowhere, filesystem, database)
