### ISSUE TITLE
Support track artists in getArtist & getArtistInfo2

### ISSUE THREAD

**Issue by TypicalFence** [sentriz/gonic#304]
It would be pretty cool to support track artists in endpoints like `getArtist` and `getArtistInfo2` but limiting `getArtists` just to album artists.

Currently when a client links to the artist of a given track the user is taken to a page about the album artists which is sometimes differs from the track artist, for example for split-ep's or compilations.  So it would also mean returning the actual track artists in which ever endpoint returns track lists.

**Comment by sentriz** [comment]
sorry i don't think it's possible right now. gonic's concept of an "artist" is only album artists. artist's have links to albums etc, which doesn't make much sense for track artists

maybe when #103 comes around we could figure something out
