### ISSUE TITLE
List of not supported files on path

### ISSUE THREAD

**Issue by marlop352** [sentriz/gonic#308]
Is there a way to get a list of all the files that are on the music library path but are not being added to the library because of a error or not being supported by gonic?
Or a list of all the files that were added to the library?

Either is fine but the first one is best.

**Comment by marlop352** [comment]
the parser seem to really dislike having ".Mp3" or ".MP3" files instead of ".mp3" 😅

some ".mp3" also don't work, is there any log when files error out when being analyzed?

**Comment by sentriz** [comment]
> the parser seem to really dislike having ".Mp3" or ".MP3" files instead of ".mp3" sweat_smile

ah i see, then I just pushed support for scanning files like that https://github.com/sentriz/gonic/commit/d83fe560d3df980c0bf99d03e026af9bce30e0c7

> some ".mp3" also don't work, is there any log when files error out when being analyzed? 

that depends, do you see anything in the "err" section after the scan is done? for example

`finished scan in 8.75ms, +0/100 tracks (2 err)`

**Comment by marlop352** [comment]
Not sure what happened, just did a full scan instead of an incremental one and all .mp3 seem(the numbers still look to not match by very little) to be currently detected in contrast to just running the incremental one. I also just fixed all my file extensions to be lowercase.

And I'm in the middle of a full scan after resetting the container(compose down + wipe data dir) so no logs to look at 😅
will check if I see any err on the after the full scan.

**Comment by marlop352** [comment]
2023/04/12 15:21:20 finished scan in 4m20.84141s, +42074/42074 tracks (1 err)

**Comment by marlop352** [comment]
I also just found the source of the rest of the discrepancy between number of files on gonic and on my system, I was counting some music files more than one because of a versioning system.

You even detect 257 more files(out of 42146) than airsonic 😍, missing only wav, opus, mpeg and oga files.
Most if not all of the missing ones can be easily replaced by compatible files.

**Thank you very much for the assistance and for the software.**

As an aside would you be interested in a bug report for windows support?
(I need to re-test it but I'm almost sure there was only issue last time I tried: part of the path was being doubled on Windows)

**Comment by sentriz** [comment]
nice, great to hear :+1: and sure, feel free to open a windows issue
