### ISSUE TITLE
getBookmarks API should return single entry for each bookmark, not an array

### ISSUE THREAD

**Issue by Glandos** [sentriz/gonic#310]
I am using Ultrasonic Android client, which fails to retrieve bookmarks from Gonic.
Indeed, based on the report made in https://gitlab.com/ultrasonic/ultrasonic/-/issues/1113 it seems that the API should returns:
```json
{
  "subsonic-response": {
    "status": "ok",
    "version": "1.15.0",
    "type": "gonic",
    "bookmarks": {
      "bookmark": [
        {
          "entry": {
            "id": "tr-2762",
            "type": "tr"
          },
          "username": "tablette",
          "position": 17268,
          "comment": "",
          "created": "2023-04-21T21:54:13.694454843+02:00",
          "changed": "2023-04-21T21:54:13.695276602+02:00"
        }
      ]
    }
  }
}
```

and not
```json
{
  "subsonic-response": {
    "status": "ok",
    "version": "1.15.0",
    "type": "gonic",
    "bookmarks": {
      "bookmark": [
        {
          "entry": [
            {
              "id": "tr-2762",
              "type": "tr"
            }
          ],
          "username": "tablette",
          "position": 17268,
          "comment": "",
          "created": "2023-04-21T21:54:13.694454843+02:00",
          "changed": "2023-04-21T21:54:13.695276602+02:00"
        }
      ]
    }
  }
}
```

Discussion was a bit more complete in the fix made for Navidrome in https://github.com/navidrome/navidrome/issues/1099

I think the code is quite simple to change in https://github.com/sentriz/gonic/blob/d83fe560d3df980c0bf99d03e026af9bce30e0c7/server/ctrlsubsonic/handlers_bookmark.go#L34 but I still never have changed any line of Go in my life…

**Comment by sentriz** [comment]
thanks :+1:

**Comment by Glandos** [comment]
That wast fast, thanks!

I installed it manually from source, and now bookmarks are working. Well, Ultrasonic is not displaying correct info, but it's gonic's problem.
