### ISSUE TITLE
[Feature Request] Turn off artist art

### ISSUE THREAD

**Issue by jprjr** [sentriz/gonic#312]
Hi there!

So, I have a lot of music that doesn't follow the `Artist/Album` layout. I have a whole collection of videogame music, organized by console like `NES/Super Mario Bros`, and I have cover files in the console folders, so the result is when I view Koji Kondo I see a picture of the NES logo.

I looked at the code and it seems like a pretty big lift to re-organize how artist art is found, I'd prefer to just turn it off.

**Comment by sentriz** [comment]
this is changed on the multi artist branch
