### ISSUE TITLE
Per-user last.fm key?

### ISSUE THREAD

**Issue by sardaukar** [sentriz/gonic#32]
Are all users of the server reporting to the same last.fm account? Is it possible for it to be per-user?

**Comment by sentriz** [comment]
no just the admin account sets the last.fm api key. then after that, any user (including admin) can login a click "link" to set up their last.fm scrobbling to their individual accounts. they should see a "allow gonic to access your account" or similar

**Comment by sardaukar** [comment]
Thanks for clearing it up!
