### ISSUE TITLE
Feature request: Support for wav files (at least for directory browsing)

### ISSUE THREAD

**Issue by peterNordin** [sentriz/gonic#320]
I just tried setting up Gonic (using docker) for the first time and it seems to work fine, except for the scanner ignoring all of my wav music files.
The README seems to hint that wav files should be supported, (at least by taglib).
However, the `supportedAudioTypes` in `mime.go` suggests it is not supported.

This is a request to add basic support for wav files (that do not contain metadata / tags). It would be nice if they would at least show up in the directory browsing mode. Right now I get lots of empty directories instead.

**Comment by sentriz** [comment]
I see no reason not to support wav. I could add it later or would happily accept a PR now

**Comment by sentriz** [comment]
you just need to add to the supportAudioTypes as you mentioned

**Comment by peterNordin** [comment]
OK, that was easy, I tried it as you suggested and it seems to work. I will create a PR
