### ISSUE TITLE
Unable to 'Shuffle' in Audinaut

### ISSUE THREAD

**Issue by tordenflesk** [sentriz/gonic#33]
Stuck on "Shuffle list is loading" in Audinaut.

![image](https://user-images.githubusercontent.com/2136727/73973752-7858f400-4923-11ea-9913-f645b8afbafb.png)

**Comment by sentriz** [comment]
hmm strange. i don't use audinaut (i would like to but chromecast support i dont think)
I will try it again shortly and check this. @nvllsvm do you have this problem per chance?

**Comment by spijet** [comment]
Actually, I get similar error when trying to load a random playlist using `subcl` (CLI *sonic-to-MPD client) and Soundwaves (iOS app). The endpoint they're trying to use is `/rest/getRandomSongs.view?size=N&v=1.9.0`, where N is the number of random songs user requested.

**Comment by sentriz** [comment]
ah. okay i need to implement that one

**Comment by sentriz** [comment]
hi! that is implemented now. please let me know how it works out. thanks!

**Comment by nvllsvm** [comment]
The fix works great in Audinaut, thanks!
