### ISSUE TITLE
Support for Custom Transcoders

### ISSUE THREAD

**Issue by jeffgt14** [sentriz/gonic#334]
This is somewhat similar to https://github.com/sentriz/gonic/issues/244 but expands a little. One of the great things about Airsonic is the ability to add custom transcoders in the transcode folder and use those over FFmpeg. FFmpeg does some great things but doesn't handle some tasks well on lossless files (writing headers to FLAC files when piped to stream, decoding DSD encoded Wavpack files to PCM for streaming, etc.). Airsonic provides the flexibility to do almost whatever suits your personal needs for a streaming server without the restrictions of a single transcoder.

I think this may also be dependent on being able to set a transcode profile per file format. The short time I've played around with gonic, I was able to add transcode profiles to transcode.go using ffmpeg but the UI restricted me to one transcode profile per client (i.e. couldn't set DSub as the client with a transcode profile for FLAC files to stream as FLAC and  MP3 files to stream as MP3, etc.). I know I could turn off transcoding entirely but I have tons of hi-res 24/96 FLAC files that I currently downsample to 16/44 FLAC for streaming with Airsonic.

**Comment by sentriz** [comment]
if I read this right, you're looking for two things

1. support for binaries other than ffmpeg 
2. support for client transcode rules based on filetype

did I get that right? at least for number 1 this is already covered by #244 since if you can provide your own transcode commands it can be any command not just ffmpeg

**Comment by jeffgt14** [comment]
Yep that's correct then. 

I didn't think 244 covered transcoders other than FFmpeg so it should cover it if so. Airsonic requires you to symlink a transcoder to the /transcode folder for it to be used. I wasn't sure where Gonic was pulling it's instance of FFmpeg from to do something similar. I'll probably have to play around with the transcode.go file some more then.

**Comment by sentriz** [comment]
for baremetal installs it shouldn't matter, gonic just starts a subprocess of the first element in the transcode command string. you just need to have ffmpeg (or whatever the future command may be) in your $PATH

for docker, we can just optimistically install a bunch of encoders in the image. right now just ffmpeg but it's easy to add whatever. feel free to open issues or pull requests for those 

regarding point two mentioned earlier, also feel free to open an issue there - not sure I fully understand it anyway 

thanks!
