### ISSUE TITLE
If Gonic can't locate cover/folder.jpg in a folder, use the first image from that folder instead

### ISSUE THREAD

**Issue by awsms** [sentriz/gonic#338]
Title sums it all!

**Comment by sentriz** [comment]
not sure its a great idea. I don't like unexpected behavior personally. are there any filenames you would like to add to the list of acceptable cover art filenames?

**Comment by awsms** [comment]
There are a bunch of known templates,
"Albumname.jpg" or "Artist - Albumname.jpg" for EAC rips,
"R-digits-digits.jp(e)g" for discogs,
"00-.*.jpg" for scene releases

I reach the point where a third of my music collection doesn't have an artwork image because of this

**Comment by sentriz** [comment]
good point 👍

**Comment by awsms** [comment]
On a related note, what do you think about parsing (the first track of a folder's) attached images in the tags?
In case Gonic couldn't find a cover image in the folder of course.

**Comment by sentriz** [comment]
there's an issue tracking that one #11

**Comment by gerroon** [comment]
Can Gonic grab cover images from the songs as well? It would be nice if it can't find a album image in the folder, it just grabs from the first song that has embedded image.

**Comment by sentriz** [comment]
there's an issue tracking that one #11

**Comment by s-fleck** [comment]
Just wanted to +1 this. I know unexpected behavior is something that's not a comfortable idea from a programmers perspective... however.:

* i'm pretty sure it's possible to come up with heuristics that display the "best" cover in 99% of the cases
* even if the wrong image is displayed, that's probably still nicer from an UX perspective then none at all! It still gives you a visual clue.

I prioritizing the following regex patterns (in that order) would already work pretty well:

1. `folder.*`
2. `cover.*`
3. `front.*`
4. `.*cover.*`
5. `.*front.*`  
6. `00.*`
7. `.*scan.*`
8. any image file

if there are several matches for one pattern, always take the first one (sorted alphabetically).

This does not account for:
* Subfolders (Artwork, Covers, Scans) - probably a bit more complicated i assume?
* Images from the tags (not sure if they are supported, if not they should probably have pretty high priority? just under `folder.*`?)

**Comment by awsms** [comment]
Is there any interest from the dev to implement this?

**Comment by nolexio** [comment]
I would also love to see this feature. Only a few folders containg a cover.jpg or folder.jpg, but instead there are a lot of files starting with the value 00-.

In my opinion an environment able would be the best deal to define how cover scanning should be handled.

I.e. 
1. default only cover.jpg, folder.jpg, 
2. first image in dir
3. regex
