### ISSUE TITLE
getGenres Support

### ISSUE THREAD

**Issue by sumnerevans** [sentriz/gonic#34]
It seems that Gonic does not support the `getGenres` endpoint. Is this in the roadmap? (I know you are busy, I just graduated and I know the final year pains.)

This is affecting a user of my Subsonic client:
https://gitlab.com/sumner/sublime-music/issues/109#note_284391742
(arguably, my client should be more resilient to not having certain endpoints missing, and that's a goal I have in the future, but I just wanted to make you aware on the server-side.)

**Comment by sentriz** [comment]
hey thanks for the report and sympathies :) this is something thats doable. taglib supports genres i'm sure

**Comment by sentriz** [comment]
also, checking out Sublime Music. `A native Subsonic/Airsonic/*sonic client for Linux. Built using Python and GTK+.`
i have been looking for exactly this. it's a bit of a pain having to use my phone for music all the time. lookin forward to trying it out

**Comment by sumnerevans** [comment]
Awesome! Please create issues for any problems that you have as you are trying it out. Sublime Music is still pretty unstable at this point.
