### ISSUE TITLE
Gonic fails to scan tags in OGG Vorbis file

### ISSUE THREAD

**Issue by mgoral** [sentriz/gonic#342]
Hi,

I'm running recent version of Gonic from the master branch (through Docker) and Gonic fails to scan one album with the following error:

```
2023-07-26T19:04:09.900132145Z 2023/07/26 21:04:09 error while scanning: 
2023-07-26T19:04:09.900169880Z "/music/The Dave Brubeck Quartet/Time Out": populate track "01 Blue Rondo a la Turk.ogg": cannot process /music/The Dave Brubeck Quartet/Time Out/01 Blue Rondo a la Turk.ogg: could not read tags
```

After this error, no more files from this directory are scanned.

This is Vorbis OGG file and I'm fairly certain that there are no problems with tags in this file, i.e. examining it with `vorbiscomment -l` doesn't show anything suspicious. It was ripped from the CD (with abcde) and imported to the library through the beets.

**Comment by sentriz** [comment]
hi can you email me that song please?

**Comment by mgoral** [comment]
Sure, please check your e-mail. :)

**Comment by sentriz** [comment]
interesting i can't reproduce it with that file it, it scans fine for me. did you a try a rescan?

**Comment by mgoral** [comment]
In older versions of gonic there was a button for full rescan, but now there seems to be only left one for incremental scans. Is there any way to force gonic to do a full rescan?

**Comment by sentriz** [comment]
if the album never successfully scanned it will be rescanned during the incremental scan. do you still get the same error when you do the normal inc scan?

**Comment by mgoral** [comment]
Yes, all the time. Now I have also updated some other album with with files with lower bitrates (because d-sub stuttered with high bitrate oggs) and Gonic also failed to add them, although previously it added them without any problems :|

I think it must be something on my side, maybe a problem with my import pipeline, but I'm not sure what.

**Comment by mgoral** [comment]
Yeah, if I copy the files directly, skipping `beet import`, Gonic successfully recognizes them. It's interesting though that it scans for you and not for me.

**Comment by mgoral** [comment]
It's embarrassing, but it was permissions issue. I uploaded files as a different user than gonic docker is configured with. Thanks for your time and support. I love gonic so far, keep it up! :)

**Comment by sentriz** [comment]
nice, glad you got it sorted :+1:
