### ISSUE TITLE
[Feature] animated cover art

### ISSUE THREAD

**Issue by BetaPictoris** [sentriz/gonic#343]
Streaming services such as TIDAL and Apple Music now have animated cover art for [some](https://music.apple.com/album/1440833098) [albums](https://music.apple.com/album/1373516902). It would be nice to be able to put a `cover.mp4` or `cover.gif` file and have it pick it up.

**Comment by sentriz** [comment]
gifs should be fine i think - gonic will already serve files like cover.gif, etc :+1: 

as for video formats - i doubt there are any subsonic clients that would be happy if a server returned a video as cover art. even web clients won't work if they are natively putting the images in an <img /> tag 

either way, maybe it's a good idea to propose this at @opensubsonic [discussions](https://github.com/opensubsonic/open-subsonic-api/discussions) 

if it's something that's agreed upon we could add it to gonic too

**Comment by BetaPictoris** [comment]
Alright, I opened a discussion, thanks for making an amazing server!

**Comment by sentriz** [comment]
thanks :D we can reopen / rename this issue if it's implemented :+1:
