### ISSUE TITLE
Get Playlist - error, if track was removed from library

### ISSUE THREAD

**Issue by archekb** [sentriz/gonic#345]
@sentriz, How do you think, are we should reject playlist fully, if we delete some track from library (and rescan the library)? 
I suppose - not, we should do not return error for playlist, we should make a `continue` (for hide this track) or return playlist with this track, for user manual deletion or delete this track automatically, but in case if mount share was not mounted (in any reason), we do not should remove this track from list, because it can returning, then third variant is not valid, first variant not good too, because we will get many garbage in playlist, then the good choose is second variant, return full playlist for manual deleting.

https://github.com/sentriz/gonic/blob/8f05f33ab8a1534433a252c085cbd5586084dd09/server/ctrlsubsonic/handlers_playlist.go#L209-L212

**Comment by sentriz** [comment]
yeah i think just logging an error and contining the loop would be fine

**Comment by archekb** [comment]
one more ... we have opportunity to add not downloaded podcast episode to the playlist (right now it's break the playlist), not sure is it right behavior. But even we fix playlist return, i think we do not should add not downloaded podcast episode to the playlist.
