### ISSUE TITLE
Convert podcast description to text

### ISSUE THREAD

**Issue by brian-doherty** [sentriz/gonic#349]
The Subsonic players I've used for podcasts (DSub, Airsonic) don't handle HTML in the podcast description well and so it doesn't render properly. Purpose instead to convert to text.

**Comment by sentriz** [comment]
i think something like bluemonday could be a good fit for that 
![image](https://github.com/sentriz/gonic/assets/6832539/390d28fe-f056-4e1d-8e19-3050b22985cd)

**Comment by brian-doherty** [comment]
Don't get me wrong -- it would be way cooler if the client would either
strip or (preferably) render the HTML. But other clients don't parse it
either.

Does the parser you suggest add in \n\n for the paragraph breaks? And
should it?

**Comment by archekb** [comment]
>  it would be way cooler if the client would either strip or (preferably) render the HTML

**Comment by brian-doherty** [comment]
Yeah, the issue is that other clients don't render the HTML either. I'm asking whether we should just strip at the server because of that. For example, DSub.

**Comment by archekb** [comment]
I suppose it's not server issue (because server get description from podcast and sent it to client as raw), this is client issue, maybe you need to open issue for client?

Because after your comment I'll add support html tags to Airsonic-refix. ;)

**Comment by brian-doherty** [comment]
So I checked and while the Subsonic API definition is ambiguous on this, the actual Subsonic implementation converts HTML to text on the way into the database. The magic question is -- do we keep the HTML and give clients the opportunity to go above and beyond, or do we match so that clients used to the way that Subsonic does things render correctly?

**Comment by sentriz** [comment]
i think keep it simple for now - if we sanitise the html on the way out of the db and into the rest view, we keep all clients happy, while still keeping the data intact any clients decide to support it later

**Comment by brian-doherty** [comment]
![Screenshot_20230814_143323_DSub](https://github.com/sentriz/gonic/assets/76168809/2640ced8-28b1-4383-b0ee-ea82c56a6b15)

So, bluemonday does OK but doesn't add carriage returns for paragraph breaks. See attached photo. I wonder if https://github.com/k3a/html2text or https://github.com/jaytaylor/html2text would be better.

**Comment by brian-doherty** [comment]
![Screenshot_20230814_144957_DSub](https://github.com/sentriz/gonic/assets/76168809/c9b4d8fe-6091-4508-960e-34c6f8240fa3)
I used jaytaylor/html2text because it was more popular and I think it's way better. I'll send that in as a PR for you to see what you think.

**Comment by archekb** [comment]
Maybe we can makes it optional? Description without tags looks boring. (after adding rendering xD) Something like `GONIC_PODCAST_RAW_DESCRIPTION`

**Comment by BetaPictoris** [comment]
> Maybe we can makes it optional? Description without tags looks boring. (after adding rendering xD) Something like `GONIC_PODCAST_RAW_DESCRIPTION`
> 
> PS Maybe we will Sanitaize and podcast description, not only Episodes description?

What about adding it as an option depending on the client parameter, similar to transcoding profiles?  That way it'd be possible to use it for clients that support it, all, or none.

**Comment by brian-doherty** [comment]
Making it a config parameter AND adding sanitization to the podcast
description are OK by me if they're OK by Senan. I don't think we should
add to the Subsonic API but if we did it would be a parameter to
getPodcasts and getNewestPodcasts.

**Comment by sentriz** [comment]
oh, i just noticed we can close this one. we can chat about the option over on #352 i suppose. thanks!

**Comment by BetaPictoris** [comment]
> Making it a config parameter AND adding sanitization to the podcast description are OK by me if they're OK by Senan. I don't think we should add to the Subsonic API but if we did it would be a parameter to getPodcasts and getNewestPodcasts.

I was thinking more of an option in the admin page like transcoding profiles but for podcast description sanitization, kinda like this: 

![Frame 1](https://github.com/sentriz/gonic/assets/65696362/7488154a-fd01-4e00-82e6-008d6697ccc0)

I don't think doing it this way would require moving away from the Subsonic API....
