### ISSUE TITLE
Podcast directory path change from name to id (or some hash)

### ISSUE THREAD

**Issue by archekb** [sentriz/gonic#350]
I have two podcasts with the same name, and of course episodes download to one directory on the hard drive (by the name of podcast). 

What it threaten:
- overwriting covers
- overwriting episodes files (if files will have the same names, as ex. `episode1, episode2 ... etc.`)

I think we should change the name in the path to something else, as podcast ID or podcast URL hash or ID-Name

**Comment by sentriz** [comment]
cc @lxea thoughts on this?

**Comment by lxea** [comment]
I'd rather not have it use the ID, I prefer having a readable file structure for this podcasts.

If a podcast is added and a folder "Podcast Name" already exists for it we could just create the new podcast in a folder named "Podcast Name (1)"

**Comment by sentriz** [comment]
:+1: yes i believe we already do that for podcast episode paths, doing it for podcast paths makes sense to me. we are self consistent and also have readable paths then
