### ISSUE TITLE
Specify cover filename

### ISSUE THREAD

**Issue by cirdanlunae** [sentriz/gonic#358]
For...reasons...I have two cover files in each of my album folders: `Cover.jpg` and `folder.jpg`. `Cover.jpg` is full-res, and `folder.jpg` is 240x240 for iPod compatibility. Gonic seems to be using the low-res `folder.jpg` rather than the higher-res `Cover.jpg`. Is there a way that we could specify artwork file names, such as with a command flag? Thanks!

**Comment by sentriz** [comment]
this would be solved by #338
