### ISSUE TITLE
Incorrect mimetype is returned when streaming m4b

### ISSUE THREAD

**Issue by Flameborn** [sentriz/gonic#36]
I am not entirely sure why, but when streaming/downloading an m4b file, an incorrect mimetype _video/mp4_ is returned, instead of audio/m4b. I believe this is when the _stream.view_ handler is invoked.

I haven't really seen a reference to this anywhere in the Gonic sources, is it possible that the mimetype is something _http.ServeFile()_ returns, along with the file?

If so, is it possible to overwrite this with the mimetypes defined in Gonic?

The mimetype for _m4b_ is definitely _audio/m4b_, see [here](https://stackoverflow.com/questions/2082293/get-mimetype-from-filename)

I am currently testing this issue via Play:Sub.

**Comment by sentriz** [comment]
howdy sorry for the late reply. it seems `http.ServeFile()` only tries to guess the content type if the header is not set already. so we can set it ourselves if we know it
https://github.com/sentriz/gonic/commit/6de50dc865063e0679e18531939d8c1f1967f99f
going to merge this branch tonight. please reopen if you have any issues!
