### ISSUE TITLE
Transcoding settings for Gonic + DSub

### ISSUE THREAD

**Issue by dbogdanov** [sentriz/gonic#361]
I have doubts on how transcoding settings work for Gonic and DSub.

Even though I have max bitrate set to 320 MP3 in DSub, no transcoding happens for my FLAC files. The screenshots below demonstrates the problem. I am using the latest Gonic Docker image and DSub 5.5.3.

DSub:
![Screenshot_20230826-013405 -- gonic](https://github.com/sentriz/gonic/assets/409668/ec55377b-db06-4b82-9894-0c9f9cfb77a3)

Gonic:
![Screenshot_20230826-013330 -- gonic](https://github.com/sentriz/gonic/assets/409668/5b941b68-342e-435e-bfd8-c94877b5f8c8)

Caching result (with mobile network): 
![Screenshot_20230826-013615 -- gonic](https://github.com/sentriz/gonic/assets/409668/540d8116-ef63-4c10-89a8-bcde80274bb4)

**Comment by BetaPictoris** [comment]
Does setting a transcoding profile on the Gonic admin page for DSub fix it?

**Comment by dbogdanov** [comment]
> Does setting a transcoding profile on the Gonic admin page (server side) for DSub fix it?

Yes, it works, but in this case I am limited to a low bitrate (e.g., `mp3` preset is 128 kbps) and transcoding would also happen when using Wi-Fi network even though I have `Unlimited` setting in DSub.

**Comment by sentriz** [comment]
yes indeed you need to have a transcode rule setup on the UI. 

on top of that, the bitrate setting in DSun is a "max nitrate". so its asking gonic to transcode to mp3 @ 128 Kbps, with a maximum of 320 Kbps. so it chooses 128

to get higher nitrates we need more profiles on the gonic side. do you think it would make sense to add a 320 profile? or 192, or v0? feel free to open an issue
