### ISSUE TITLE
Can't delete a podcast

### ISSUE THREAD

**Issue by sallp** [sentriz/gonic#365]
When I hit delete I get

 please provide a valid podcast id

**Comment by sentriz** [comment]
hi, which version of gonic are you running? and from source / docker ?

**Comment by sallp** [comment]
It says it's v0.15.2 and it form source

**Comment by sentriz** [comment]
are you deleting from a subsonic client? which one if so

**Comment by sallp** [comment]
Deleting from the web ui

**Comment by sallp** [comment]
When I hit delete in the web iu it take me to a mostly black screen that says "please provide a valid podcast id" and the URL bar says "admin/delete_podcast_do?id=4" the number changes based on which one I try but none get deleted.

**Comment by sentriz** [comment]
hm it looks like gonic is returning the wrong error message there and hiding the underlying issue (likely a filesystem issue)

i just pushed a fix, but for you to run it you will have to run from master (`go install go.senan.xyz/gonic/cmd/gonic@master`)

i would recommend taking a backup of your database before upgrading!

**Comment by sallp** [comment]
I would not start, look at the logs, did not have permission to write to podcast directory. Fixed the permission and it started and I can delete podcast now.

**Comment by sentriz** [comment]
OK nice 👌
