### ISSUE TITLE
Gonic data via API

### ISSUE THREAD

**Issue by bensmith2697** [sentriz/gonic#372]
Is it possible to get information via an exposed api relating to stats in Gonic so that information can be used in a dashboard like homepage?

![image](https://github.com/sentriz/gonic/assets/144832317/d7dd4419-ad9e-435b-9059-54d82e9a98b4)

example response would be

![image](https://github.com/sentriz/gonic/assets/144832317/095a66a0-3e02-42ff-821b-ccff9a3acf81)

**Comment by BetaPictoris** [comment]
We could solve this and #150 by adding `/metrics` and `/metrics/json` or `/metrics?f=json`.

**Comment by sentriz** [comment]
if the GONIC_EXPVAR or -expvar options are provided, this can be retrieved from /debug/vars

![image](https://github.com/sentriz/gonic/assets/6832539/3a58ab4d-c0c7-44fc-af94-67ed1a61491b)

**Comment by sentriz** [comment]
> We could solve this and #150 by adding `/metrics` and `/metrics/json` or `/metrics?f=json`.

i agree, but decided to go with Go's builtin expvar package

**Comment by bensmith2697** [comment]
@sentriz Nice thank you for add this option. when will this be available in the docker nightly version?

**Comment by sentriz** [comment]
i think it should be there already, it builds daily

**Comment by bensmith2697** [comment]
then I shall wait for the next update and let you know how it goes, thank you so much for implementing this so fast.

**Comment by bensmith2697** [comment]
Works perfectly: 

![image](https://github.com/sentriz/gonic/assets/144832317/d73a715d-8c4f-4cc3-90be-94f7999f80f6)

**Comment by sentriz** [comment]
nice 👌

**Comment by playitforless** [comment]
@bensmith2697 did you modify the widget for homepage if so are you going to submit it to their GitHub?
