### ISSUE TITLE
docker-compose multiple folders format

### ISSUE THREAD

**Issue by jbmfg** [sentriz/gonic#375]
gonic version: v0.15.2
sentriz/gonic:latest

What is the proper format for docker-compose to add multiple music folders?  The docs just say to comma separate if using docker.  These don't find any music at all:

`- /media/Storage/Music, /media/Storage/NewMusic:/music:ro # your music`
`- /media/Storage/Music,/media/Storage/NewMusic:/music:ro # your music`

**Comment by sentriz** [comment]
the comma syntax is for gonic environment variables, not docker volumes. you need to mount both volumes into the container, then tell gonic where they are in the container 

eg:

volumes:
  - /a:/a:ro
  - /b:/b:ro
environment:
  GONIC_MUSIC_PATH=/a,/b
