### ISSUE TITLE
Wrong release number in the admin interface ?

### ISSUE THREAD

**Issue by garfieldairlines** [sentriz/gonic#377]
gonic version:

if from docker, docker tag: sentriz/gonic:v0.16.0-rc1
if from source, git tag/branch:

Just upgraded to the 0.16.0-rc1 and when I check the footer I get 

v0.15.2 senan kelly, 2020 | [github](https://github.com/sentriz/gonic)

However the CSS did change so it looks like I indeed upgraded, did you forget to edit the version number on the webpage too ?

**Comment by sentriz** [comment]
that's right. it doesn't get updated for prereleases. though I may change that at some point. thanks
