### ISSUE TITLE
App version for 16.0-rc1 shows as 15.2

### ISSUE THREAD

**Issue by shadowjig** [sentriz/gonic#381]
gonic version: 16.0-rc1

Docker tag: sentriz/gonic:v0.16.0-rc1

When I run the docker image above I still see 15.2 show up in the logs when starting the docker container.  It also shows 15.2 in the admin web interface at the bottom.  I think I'm running the new code, because the admin interface looks slightly different.

**Comment by aswerkljh** [comment]
Known; see https://github.com/sentriz/gonic/issues/377
