### ISSUE TITLE
Support multi-valued tags for track artists

### ISSUE THREAD

**Issue by ProfMoo** [sentriz/gonic#388]
Now that multi-valued tags are supported for album artists [in v0.16](https://github.com/sentriz/gonic/releases/tag/v0.16.0), I think it'd be great to expand this functionality to track artists 😄.

From a user perspective, I'd be great to be able to find all the tracks that a certain artist was involved with (ex: Skrillex was featured on one song on J Balvin's album. Ideally, we could associate that will Skrillex in the db).

As an example, here is how it looks in Roon currently on the track "Scenario" by A Tribe Called Quest:
![image](https://github.com/sentriz/gonic/assets/32044819/c7da66b7-1581-4003-909a-9aa81aba441a)

Musicbrainz link [here](https://musicbrainz.org/release/69959f4a-29fd-4867-83ec-bfb4036b30d1), track #14. Each artist in Roon is individually navigable. Although I believe Roon is enabling this via Musicbrainz rather than via tags/folder structure.

**Comment by sentriz** [comment]
I would called this closed with #397 being merged. it's a little experimental at the moment but can be configured with the new GONIC_MULTI_VALUE_ARTIST setting

I'll be improving it again with a follow up PR
