### ISSUE TITLE
Error when no playlists directory is found

### ISSUE THREAD

**Issue by Underpath** [sentriz/gonic#389]
**gonic version:** v0.16.0

**if from docker, docker tag:** latest (Linux/amd64 digest: 257089075b207bd66a7cc2cf552c463eeae9e35b0b6a839ef6cf61fda9fc26d0)

---

Gonic Docker container gets into a restart loop with error `checking playlist directory: path does not exist, please provide one`. This started happening when Watchtower updated Gonic to the latest version a couple of days ago. I am not sure if in previous releases I had set the `GONIC_PLAYLIST_PATH` variable, but after the update it was set to `/playlists`. Since I did not have this directory mapped in Docker it was not being created, after I mapped it the errors stopped and Gonic is working again.

**Comment by sentriz** [comment]
hi thanks for the report - though this is expected behaviour. I decided to make it required as a part of the update

there is notes about this in the releases notes. but the gist of it is it was a tradeoff that was made 👍
