### ISSUE TITLE
Scanner crash

### ISSUE THREAD

**Issue by headfog** [sentriz/gonic#399]
gonic version: 0.16.0

if from docker, docker tag:
if from source, git tag/branch:

My library contains some audio files causing the scanner to crash. Apparently due to having tags which are not readable. Perhaps the files are corrupt in some way but they are perfectly playable.
Here is the info in the log

goroutine 1 [running]:
log.Panic({0xc0000e3c28?, 0xc000539560?, 0x55b3b4875318?})
	log/log.go:432 +0x5a
main.main()
	./gonic.go:432 +0x29bd

**Comment by sentriz** [comment]
can you provide the full log please

**Comment by headfog** [comment]
[gonic.log](https://github.com/sentriz/gonic/files/13216947/gonic.log)

**Comment by sentriz** [comment]
thanks should be fixed now, where scan errors won't panic main()
