### ISSUE TITLE
regex help

### ISSUE THREAD

**Issue by Dubwize** [sentriz/gonic#400]
gonic version:

if from docker, docker tag:latest

Hello

I am trying to get the exclude pattern regex working.  Specifically for the folder @eaDir that is created in my nas.  Does anyone have a working example for that, or at least some examples I might be able to extrapolate from.

I should be able to match like this snippet from docker-compose shows.  I have also tried a number of other patterns like a full match.  

environment:
      - GONIC_EXCLUDE_PATTERN=^@
      
When the gonic server starts, I see the exclusion in the logs. So it's taking the env variable on compose, but it still scans those folders.
![image](https://github.com/sentriz/gonic/assets/16105140/5922bae3-a6ad-4b5f-b202-adc5da2e88d6)

Thank You

**Comment by sentriz** [comment]
hey, the regex matches on absolute paths like /mnt/music/thing/@eaDir so a pattern like `/@` should do it. please reopen if not :+1:
