### ISSUE TITLE
Set several library path in the docker-compose?

### ISSUE THREAD

**Issue by awsms** [sentriz/gonic#401]
How can you add several library path? If I put
```
      - /data/musicfolder1:/data/musicfolder1
      - /data/musicfolder2:/data/musicfolder2
```
in my docker-compose.yml, gonic ignores both of these folders (despite having an existing gonic.db, which gets wiped up when i launch a rescan).
gonic only expects music to be located in `/music` for the docker image?

**Comment by awsms** [comment]
answered here: https://github.com/sentriz/gonic/issues/375
too bad it wasn't in the wiki page!

**Comment by sentriz** [comment]
the readme is more useful and up date compared to the wiki. I think I might delete the wiki
