### ISSUE TITLE
Artwork folders at root

### ISSUE THREAD

**Issue by headfog** [sentriz/gonic#402]
gonic version: 0.16.0

The root directory gets polluted by artwork directories. This happens when gonic encounters an error in reading tags of tracks stored alongside. In such situation the parent_id of the containing album is empty

[gonic.log](https://github.com/sentriz/gonic/files/13256357/gonic.log)
[gonic.db.zip](https://github.com/sentriz/gonic/files/13256367/gonic.db.zip)

**Comment by sentriz** [comment]
btw, you can exlcude Artworks dirs with the GONIC_EXCLUDE thing

**Comment by headfog** [comment]
Great. Yes, the regex works but using it has a global effect. Not all artwork directories end up at the root and i like to see covers when they're available

**Comment by headfog** [comment]
fix ddb686b tested and got the same error unfortunately
