### ISSUE TITLE
Respect Client's maxBitRate query param stream request

### ISSUE THREAD

**Issue by OpenSrcerer** [sentriz/gonic#403]
## Context

gonic version: `v0.16.0`
client: `symfonium`
if from docker, docker tag:  `257089075b20`

## Issue
I was having a confusing time understand why my Symfonium client was using so much data, and [in the process I found out](https://support.symfonium.app/t/p8p-gonic-bitrate-configuration-ignored/2720) that Gonic does not respect the `maxBitRate` setting of the client upon a stream request.

In #244 you state:
> I think hopefully that shouldn't happen. gonic will skip a transcoded if
> the source bitrate is less than the requested bitrate
> the client requests a maxBitrate higher than the source nitrate
> the client requests to not transcode

However, right now the behavior seems to be that the `maxBitRate` param is completely ignored, and the only setting that is respected is the "transcoding device settings" override that you set in the control panel.

I think respecting the param is a good thing to have because it allows users to select different bitrates client-side depending on factors such as WiFi connection status, or (come up with some creative idea here).

**Comment by sentriz** [comment]
hi it does respect it, you just need to enable transcoding on the gonic web interface

**Comment by OpenSrcerer** [comment]
Hi @sentriz thanks for the reply! Perhaps I'm confused, but you do mean this, right?
![image](https://github.com/sentriz/gonic/assets/46500918/b7c6a33e-73a6-498c-adfd-0b1af3883b07)
Wouldn't this force the client to use opus @ the bitrate you've provided on the wiki, so 96kb/s?

**Comment by sentriz** [comment]
without a maxbitrate yes it will default to 96kbps, however if the client instead says maxBitRate 50kbps, then it will be opus @ 50kbps

but it must be lower than the profile

so you could instead set the profile to opus 192, then the client can request anywhere from 0 to 192

**Comment by OpenSrcerer** [comment]
Okay makes sense! Thanks for the explanation.

I'm not super well-versed in the new OpenSubsonic impl to really understand the reasons behind your necessity for the extensions, since the `maxBitRate` param already exists. However, Opus@192 & less is perfect for my usage so I'll call this issue closed on my end.
