### ISSUE TITLE
support getAlbumList2 `type=highest`

### ISSUE THREAD

**Issue by GioF71** [sentriz/gonic#404]
Hello, thank you for your great software.

I am maintaining a subsonic client for upmpdcli: see [here](https://github.com/GioF71/upmpdcli-docker/discussions/291) a slightly outdated changelog.
I started with navidrome, and only recently I tried to update my work so that it could support Gonic as well.
I have a small issue with the album title missing (available in 'name' however), which is a different behavior compared to navidrome, but no big issue there, I could work around this issue easily.

On the other hand I noticed that, while Navidrome supports "highest" as list type in the getAlbumList2 api method, Gonic doesn't seem to.
I understand that, looking at the api documentation, that value should not be supported anyway, but considering that Navidrome supports it, is there a chance that Gonic can implement it?

Thank you for any feedback, all the best.

**Comment by sentriz** [comment]
oh i see. i'm not sure when `highest` became a thing, but yes it does seem to be part of @opensubsonic now. so sure i can add it :+1:

https://opensubsonic.netlify.app/docs/endpoints/getalbumlist2/

**Comment by GioF71** [comment]
Awesome! Thank you!

**Comment by sentriz** [comment]
i added support for `getAlbumList?type=highest` and `getAlbumList2?type=highest`

also fill the "album", "title" and "name" fields for subsonic albums in tags/folder modes :+1:

**Comment by GioF71** [comment]
That worked perfectly! Thank you!
