### ISSUE TITLE
Support for Artists tag (Picard)

### ISSUE THREAD

**Issue by TypicalFence** [sentriz/gonic#406]
gonic version: v0.16.0

if from docker, docker tag: sentriz/gonic:nightly

I struggled getting multiple artists to work, my files were tagged by beets but beets seems to follow the default tag format of Picard, which can be found here: https://picard-docs.musicbrainz.org/en/variables/tags_basic.html

to quote the docs:
```
artist
Track Artist Name(s). (string)

artists
Track Artist Name(s). (multi-value) (since Picard 1.3)
```

Retaining the value of the artist field would also be nice as it appears to contain the artists in a formatted way, example (eyeD3 output).
```
ID3 v2.4:
title: UN1TE
artist: Massive New Krew ft. YUC'e

UserTextFrame: [Description: ARTISTS]
Massive New KrewYUC'e
```
OpenSubsonic appears to have a `displayArtist` field that would fit that. 

The AlbumArtists field is also a thing that might make sense should this feature be considered.

Also the type mapping per file format: https://picard-docs.musicbrainz.org/en/appendices/tag_mapping.html#artists

**Comment by sentriz** [comment]
are you asking about getting the multi valued tags scanned into gonic, or returning the display artist / artist credit tags over the api?

**Comment by TypicalFence** [comment]
I am asking about the multi value tags under `Artists` & `Albumartists` being scanned into gonic, which doesn't seem to be the case at the moment.

But I was overthinking the whole thing because I started to wondering if it should be merged with the content of `Artist` or overwrite it and the fact that potentially some meaning could get lost from the single value string. 

Due to that I found out about `display artist` and wanted to note that probably the single value should be used based on what beets is tagging opposed to for instance concatenating the content of the artists fields.

**Comment by sentriz** [comment]
have you set the multi valued settings like GONIC_MULTI_VALUE_ARTIST, GONIC_MULTI_VALUE_ALBUM_ARTIST? they need to be set first, check the readme

as for tags, yes the picard settings should work. for example this release https://musicbrainz.org/release/d7e1ff31-5bc1-4d8a-a218-5861eaf4a59a

if picard sets the albumartist and albumartists tags, you would see for example in a gonic album response

```json5
{
  "id": "al-22",
  "name": "Liumin",
  "year": 2010,
  
  // compatibility
  "artistId": "ar-18",
  "artist": "DeepChord",

  "artists": [
    { "id": "ar-18", "name": "DeepChord" },
    { "id": "ar-19", "name": "Echospace" }
  ],
  "displayArtist": "DeepChord Presents Echospace",
  
  "genre": "electronic",
  "genres": [
    { "name": "electronic" },
    { "name": "techno" }
  ],
}
```

**Comment by sentriz** [comment]
does that make sense?

**Comment by TypicalFence** [comment]
I just ran another full scan and it appears to pick it up now.
