### ISSUE TITLE
Last.fm account linking does not work

### ISSUE THREAD

**Issue by L4R5** [sentriz/gonic#407]
gonic version:v0.16.1
if from docker, docker tag: sentriz/gonic:v0.16.1

I created an API key for my gonic installation and registered it in gonic using the admin user.
After that I tried to link another non-admin account to last.fm and receive the following error message in gonic after clicking the "Yes, Allow Access" button in last.fm

```
make request: Invalid method signature supplied: last.fm error
```

![image](https://github.com/sentriz/gonic/assets/2116324/1b45a19a-91ae-4ac9-b7c5-9cb01e064426)

![image](https://github.com/sentriz/gonic/assets/2116324/cd9d66dc-f841-4923-9e8d-7884ec01c8cc)

**Comment by sentriz** [comment]
hmm are you sure your api secret is correct? (when logged in as the admin)

**Comment by sentriz** [comment]
its working for me. looks like your api secret isn't right. if not, please reopen 👍

**Comment by L4R5** [comment]
thanks for the hint, it was human error :)
