### ISSUE TITLE
Ambiguous IDs in subsonic views

### ISSUE THREAD

**Issue by Duncaen** [sentriz/gonic#41]
There are subsonic views accepting IDs for different types like [getArtistInfo](http://www.subsonic.org/pages/api.jsp#getArtistInfo):

> `id` The artist, album or song ID.

Is there any plan on how to handle this or am I missing some view where this is already supported?

My idea would be to provide all ids in the form of `album:1`,
`artist:1` and `song:1` or `track:1` and maybe add some helper to the `params` package like:

```
// GetAlbumId returns the album ID or an error if the type prefix is not `album` or has no integer suffix.
params.GetAlbumId("id") (int, error)
// GetId returns the type prefix or an error if the ID has a wrong format or has no integer suffix.
params.GetId("id") (string, int, error)
```

Currently `getArtistInfo2` is implemented per `getArtistInfo` spec, `getArtistInfo2` uses ID3 tags, but gonic implements it by using lastfm info, to fix this the ambiguous IDs have to be managed.

**Comment by sentriz** [comment]
Hmm yeah I was thinking this may be an issue at some point. Slightly confusing though, that getArtistInfo could return things for track or album ids

**Comment by Duncaen** [comment]
A song could return the artist instead the album artist which includes featuring artists but with how the response is structured and how there is no standard on formatting featuring artists I don't really see a way to really make use of it.

**Comment by Duncaen** [comment]
Starring and Rating are two other functionalities which use ambiguous IDs.

**Comment by sentriz** [comment]
i've been doing some work on this on the ambig-ids branch. parameter parsing and creating types etc is done, what's left is just reading the right ids in the handlers

**Comment by sentriz** [comment]
tests are failing the way we expect now https://termbin.com/q1jmf
