### ISSUE TITLE
Request: Show audio metadata in stream logs

### ISSUE THREAD

**Issue by SaveRobots** [sentriz/gonic#412]
Docker tag: latest

A while back, I submitted a feature request #212 to add additional detail to see what users are streaming within the logs. The feature was working great until today when I updated to the latest version. The logs now look something like:

GET /stream?u=USER&s=REDACTED&t=REDACTED&v=1.2.0&c=DSub&id=tr-53823&maxBitRate=273

Can we get readable stream logs back? This was a highly used feature for myself.

**Comment by sentriz** [comment]
whats the usecase for this? there is some compexity in this since we can potentially stream lots of different file types including podcasts etc

**Comment by SaveRobots** [comment]
To log and understand what parts of my library that my users are accessing. This seems like a pretty common feature for a media library/streaming platform.

**Comment by sentriz** [comment]
sorry i think i don't really like this feature. there's something about it. maybe it's a little specific/spammy/or just creepy

one idea if you want to watch a stream of currently playing track try this

`docker compose logs --tail 20 -f main | while read -r line; do id="$(echo "$line" | grep -Po "tr-\K[0-9]+")"; [ -z "$id" ] && continue; echo "playing track $id"; sqlite3 main_data/gonic.db "select artists.name, tracks.tag_title from tracks join track_artists on track_artists.track_id=tracks.id join artists on artists.id=track_artists.artist_id where tracks.id=$id"; done`

assuming docker, and your log stream is `docker compose logs --tail 20 -f main`, and your gonic db path is `main_data/gonic.db`

**Comment by SaveRobots** [comment]
That is kind of a strange response, considering this was a feature you had previously implemented via request.

I appreciate the alternative solution, but not really what I was looking for. Thanks anyways.
