### ISSUE TITLE
Problem with cookie or specific proxy configuration needed

### ISSUE THREAD

**Issue by Cherryblue** [sentriz/gonic#414]
Hi,

Setup : gonic 0.16.1 in docker.
Reverse-Proxy : HAPROXY (previously NGINX)

Problem : when browsing the web portal, I only get Error 500 : "error saving session: securecookie: hash key is not set".

Not sure if it's linked to new version, or me going from NGINX to HAPROXY, but I'd sure like some help on this :).

I've tried [this](https://www.haproxy.com/blog/how-to-secure-cookies-using-haproxy-enterprise) and [that](https://stackoverflow.com/questions/66263928/how-do-i-secure-cookies-in-haproxy-2-2-using-an-http-response-line) with no success so far.

**Comment by sentriz** [comment]
is the issue only with HAPROXY, not Nginx?

**Comment by Cherryblue** [comment]
> is the issue only with HAPROXY, not Nginx?

I just switched to my old configuration for gonic using NGINX in order to check : I get the same error with nginx.
It seems to be linked to 0.16.x.

Thanks for taking this into account :).
