### ISSUE TITLE
Scrobbles not working

### ISSUE THREAD

**Issue by fletchowns** [sentriz/gonic#421]
gonic version: v0.16.2

if from source, git tag/branch: 5b5572d

I wasn't able to get scrobbling working, for either last.fm or listenbrainz. It sounded similar to #168 

I've got both services linked in the settings:
![image](https://github.com/sentriz/gonic/assets/153107/e66f239b-0dd0-43b5-9e75-efdff0bd08c5)

In my gonic log, I see the `/scrobble` endpoint is being hit:
```
2023/12/02 21:44:17 response  200  GET /scrobble?id=tr-17777&submission=false&v=1.15.0&f=json&c=https%3A%2F%2Fmusic.mydomain.net&u=fletchowns&s=KAp...&t=8f6...
```

However, I don't see any scrobbled being added to my last.fm or listenbrainz accounts. Is there a way to turn on debug logging of the HTTP requests it's sending to those services?

**Comment by sentriz** [comment]
hmmm looks like that is a submission=false scrobble, mean just "now playing" instead of a real scrobble

do you have any with submission=true?

also which client are you using?

**Comment by fletchowns** [comment]
Ahh, thanks! That gives me something to go on.

I am using [airsonic-refix](https://github.com/tamland/airsonic-refix) for my client, looks like this is where it handles the scrobbling: https://github.com/tamland/airsonic-refix/blob/bc4920fa57a20236ad7eef6f4483e50726b845c6/src/player/store.ts#L359-L384

From that, it looks like there should be another /scrobble call when you get to 70% of the track

Sure enough, shortly after that original log line I posted, I see the call with `submission=true`:
```
2023/12/02 21:44:17 response  200  GET /scrobble?id=tr-17777&submission=false&v=1.15.0&f=json&c=https%3A%2F%2Fmusic.mydomain.net&u=fletchowns&s=KAp...&t=8f6...
2023/12/02 21:46:44 response  200  GET /scrobble?id=tr-17777&submission=true&v=1.15.0&f=json&c=https%3A%2F%2Fmusic.mydomain.net&u=fletchowns&s=KAp...&t=8f6...
```

**Comment by fletchowns** [comment]
Oh jeez - I just realized my mistake. The account linking to last.fm & listenbrainz is per-user. I had established the linking for my admin account, but not the gonic user account that I'm actually using from my player. I've logged into gonic with the user I'm _actually_ using from refix, and linked last.fm & listenbrainz, and it's working now! Apologies for wasting your time 🤦

**Comment by sentriz** [comment]
glad you got it working 👍

I think I mention that idea of multi user scrobbling stuff in the UI . if you think the copy could be improved let me know

**Comment by fletchowns** [comment]
I do see the copy refers to that, and upon careful reading it makes sense
> scrobble to listenbrainz and compatible sites on a per user basis

I think what threw me off was the mix of contexts in the sections in the gonic ui.
* **stats** section is global, all gonic users see the same thing
* **user** management is user specific. admin user sees all users and can add new users, other users only see themselves listed here
* **recent folders** is global, all gonic users see the same thing, but only admin can initiate a scan
* **transcoding device profiles** is user specific, you are setting the transcoding preferences for the logged in user
* **last.fm** is specific to the logged in user
* **listenbrainz** is specific to the logged in user
* *podcasts* is admin only
* **internet radio stations** seems to be admin only
