### ISSUE TITLE
config file flag "cdcmusic-path" not defined in flag set

### ISSUE THREAD

**Issue by luluone** [sentriz/gonic#427]
gonic version: 0.15.2
Installed from AUR : gonic 0.15.2-3

Error with systemctl start gonic.service : (code=exited, status=1/FAILURE)

journalctl -u gonic :
déc.` 13 13:16:39 VM-Arch systemd[1]: gonic.service: Scheduled restart job, restart counter is at 37.
déc. 13 13:16:40 VM-Arch systemd[1]: Started gonic service.
déc. 13 13:16:40 VM-Arch gonic[675]: 2023/12/13 13:16:40 error parsing args: config file flag "cdcmusic-path" not defined in flag set
déc. 13 13:16:40 VM-Arch systemd[1]: gonic.service: Main process exited, code=exited, status=1/FAILURE
déc. 13 13:16:40 VM-Arch systemd[1]: gonic.service: Failed with result 'exit-code'.

what is cdcmusic-path ?

**Comment by sentriz** [comment]
can you share your config file? looks like you have a typo

**Comment by luluone** [comment]
I'm very sorry it's a typo 
After correction I have : mkdir /var/cache/gonic/audio: permission denied
In my config file : cache-path        /var/cache/gonic/
Who should be the owner of the cache directory ?

**Comment by sentriz** [comment]
it depends how you've setup gonic. i'm not familar with the AUR package honestly. are you using this guide? https://github.com/sentriz/gonic/wiki/installation#with-systemd

if so maybe try $ chown -R gonic:gonic /var/cache/gonic/

**Comment by sentriz** [comment]
going to close since it's not an issue on gonic's side - but feel free to ask questions about above :point_up:
