### ISSUE TITLE
Gonic fails to see all podcast episodes for Revolutions podcast

### ISSUE THREAD

**Issue by khers** [sentriz/gonic#430]
gonic version: v0.16.2

if from docker, docker tag: sentriz/gonic:latest

I am moving to Gonic from Airsonic-advanced and in adding my podcast subscriptions I cannot get all of the published episodes for Revolutions (rss feed here: http://revolutionspodcast.libsyn.com/rss The XML file that is found there contains all 10 seasons and the final appendix, but when I try and download all, I only get as far back as episode 10.8. So I am missing the first 7 episodes of season 10 and all of seasons 1-9.

**Comment by sentriz** [comment]
any ideas on this @lxea?

**Comment by sentriz** [comment]
ah it looks like we bail after we see just one error when adding the podcast

so in this case, gonic was giving up after it came across an episode that had no audio URL in it

should be fixed now

**Comment by khers** [comment]
Thanks for the quick turn around! As soon as this is available in the latest (stable) docker I will give it a go
