### ISSUE TITLE
Feature Request: Let users ask the server to download individual podcast episodes

### ISSUE THREAD

**Issue by khers** [sentriz/gonic#431]
gonic version: v0.16.2

if from docker, docker tag: sentriz/gonic:latest

The API allows users to request individual episodes be downloaded but when I attempt this (via the dSub app) I get a permission denied. I would like to allow regular users to request download of individual episodes, even better if this is a permission I can grant on a per users basis.

**Comment by sentriz** [comment]
closing in favour of #156 which will expand user permissions outside of just admin

**Comment by khers** [comment]
:+1:  Thanks, and sorry for the noise. Also, thanks for all your work on this.
