### ISSUE TITLE
sync starred songs to last.fm

### ISSUE THREAD

**Issue by TorchedSammy** [sentriz/gonic#434]
Seeing as starred songs are just a way to favourite songs, I suggest being able to sync them to last.fm (and listenbrainz as well)

**Comment by sentriz** [comment]
there's and experimental repo you can try out or contribute here 👍 https://github.com/sentriz/gonic-lastfm-sync/

**Comment by TorchedSammy** [comment]
It seems this just runs based on a timer and updates everything. Would there be a better way to do it based on when I actually star something from a client?

**Comment by sentriz** [comment]
that would indeed be a better experience, but tight (and niche) lastfm integration like you describe is out of scope for gonic - hence the external repo

if it helps you could increase the sync frequency
