### ISSUE TITLE
external user authentification

### ISSUE THREAD

**Issue by unclesamwk** [sentriz/gonic#44]
Hey,

subsonic supports authentication against a ldap server. This feature would be nice. Additionally the oauth support.

thanks
sam

**Comment by sentriz** [comment]
this would be a cool feature alright. im wondering about how much complexity it would add to the codebase though

**Comment by unclesamwk** [comment]
Very nice LDAP Server 
https://github.com/glauth/glauth

**Comment by helmut72** [comment]
LDAP authentication would be great. All of my other self hosted services use LDAP to have a single point of user administration.

**Comment by helmut72** [comment]
Maybe some http header based auth with automatic user creation is easier to implement? Then everyone can choose the prefered auth system (ldap, openid connect, saml...). I use http header based auth with FreshRSS and it works really great. To connect the any apps, the user must login and create an "app password" of course.

**Comment by sentriz** [comment]
looking at this again, I'm not sure its possible given the subsonic API's auth mechanism using query params. if anyone has any other ideas please reopen 👍

**Comment by BetaPictoris** [comment]
I'm not sure about how it was implemented, but Airsonic-Advanced has LDAP authentication.
