### ISSUE TITLE
prallel transcoding prioritization

### ISSUE THREAD

**Issue by luopa** [sentriz/gonic#442]
gonic version: v0.16.2

docker tag: latest

in general, playback of transcoded songs works.

however, under certain circumstances the prallel transcoding prioritization seems to fail.

**steps to reproduce**
- start playback of a song
- move to next song in queue
- move to next again
- start playback of another song not from current queue,  eg. from different album
- song is transcoded for a few seconds - and then doesnt transcode further. 
  - see this video for a demo of the issue:  [YouCut_20231226_115611037.mp4](https://unibe365-my.sharepoint.com/:v:/g/personal/jan_degen_students_unibe_ch/EYUnw09HPIRDnmj2qg8F68QBGjvXo_OPYunsr78moRLudg?e=sCFGE5)
  - the issue is nicely visible at 00:24 when i start the song "1. Blue Orchid"
  - i think its even visible through the playback cache bar not filling up in symfonium.

i can observe this with symfonium. however, eg. not with dsub. it seems as if dsub only requests one transcoding job at a time, whereas symfonium requests multiple?

would be happy to provide further information/logs if needed?

in any case - thanks for all the work on gonic. its currently my goto music server and i love it!

**Comment by sentriz** [comment]
some more logs would indeed be handy if you had them. or more info about how symfonium makes its requests. I would have a look but it's a proprietary app :( 

fwiw gonic handles parallel transcoding fine in my testing so far

**Comment by luopa** [comment]
hi sentriz, i ran another test and collected some logs:

- [video of what happens](https://unibe365-my.sharepoint.com/:v:/g/personal/jan_degen_students_unibe_ch/EWWncpRhwQlEqhxwVLPm1E0BaMBYZCnXDaaPaLouuI7VXQ?e=By67C2)
- gonic log [2023-12-28-logs-gonic.txt](https://github.com/sentriz/gonic/files/13784359/2023-12-28-logs-gonic.txt)
- symfonium log [2023-12-28-log-symfonium.txt](https://github.com/sentriz/gonic/files/13784360/2023-12-28-log-symfonium.txt)

i hope this provides some clues?

**Comment by sentriz** [comment]
it's very hard to debug this without access to the symfonium app or source. would you mind asking the symfonium devs to help with this? FWIW parallel transoding works fine in all my testing so far
