### ISSUE TITLE
error creating playlists store: sanity checking: reading dir: open : permission denied

### ISSUE THREAD

**Issue by michael-keyes** [sentriz/gonic#446]
gonic version:

if from source, git tag/branch: latest 

Forced to use a playlists-path now.
Config looks like this:
```
listen-addr                 0.0.0.0:4747
db-path                     /var/lib/gonic/gonic.db
music-path                  /home/mgk/gonic/music
podcast-path                /home/mgk/gonic/podcasts
playlists-path              /home/mgk/gonic/playlists
cache-path                  /var/cache/gonic/
```
Which now causes...
error creating playlists store: sanity checking: reading dir: open /home/mgk/gonic: permission denied

Any ideas?

**Comment by sentriz** [comment]
try chown the playlists dir to be the same user as which gonic runs as
