### ISSUE TITLE
error opening database: with gorm: unable to open database file

### ISSUE THREAD

**Issue by tordenflesk** [sentriz/gonic#45]
Portainer Volumes:
https://i.imgur.com/wpsSvY0.png
Portainer Env:
https://i.imgur.com/OOUrPvT.png

Am I missing something obvious?

**Comment by sentriz** [comment]
Hmm interesting. Is this the first time you're using gonic. And could you also post the full gonic logs please? (Just for line numbers etc)

**Comment by tordenflesk** [comment]
That's all the log says in Portainer, repeatedly.
I'm unable to connect to the console in Portainer because the container is constantly restarting.
I've used Gonic just fine before, but decided to start a new one, so there is no old database.
I did try restoring my old database file just to try with no change.

**Comment by sentriz** [comment]
Could it be a permissions issue on your host perhaps? And port may need to be ":8080:" instead of "8080"

**Comment by tordenflesk** [comment]
```
ls -la /sharedfolders/DOCKER_CONFIG/GONIZ_Music/
total 8
drwxrwsrwx  2 root users 4096 Mar 13 02:12 .
drwxrwsrwx 19 root users 4096 Mar 13 02:12 ..
root@SRV-OMV01:/sharedfolders/DOCKER_CONFIG#

```

Doesn't look like it to me.

**Comment by sentriz** [comment]
can you try change the list addr env var to ":8080" instead? i dont think gonic will start with just "8080"

**Comment by tordenflesk** [comment]
I've tried both:
https://i.imgur.com/qHI0p8u.png

**Comment by sentriz** [comment]
hmm okay. could you try get the logs from docker instead of portainer? `docker logs --tail 200 -f <gonic_id>` should show everything, even if it's restarting

**Comment by tordenflesk** [comment]
That gives the same output:
`2020/03/13 21:21:02 error opening database: with gorm: unable to open database file`

**Comment by sentriz** [comment]
ohh! i think i see it now. try change `GONIC_DB_PATH` to `/data/gonic.db`

**Comment by tordenflesk** [comment]
That looks to be it. I hadn't noticed that the var needed the file 
aswell. :)

-Espen

**Comment by sentriz** [comment]
cool :) please reopen if there's anything else
