### ISSUE TITLE
Where does everything go and how??

### ISSUE THREAD

**Issue by coacharnold1** [sentriz/gonic#450]
This is a silly issue ...   but i'm confused I've installed the most recent version of gonic ... I have 2 questions that are not version specific.

1 - where is the bast place to stick the docker-compose file if running from Docker??

2 -  If my collection exists in on several hard drives,  what is the best syntax in the docker-compose file to direct gonic to multiple folders?

Thanks ....  this is a spectacular implementation

Tim

**Comment by sentriz** [comment]
1. it's very much up to you. I keep mine in /opt/containers/gonic/compose.yml
2. have a look at this, maybe it's useful https://github.com/sentriz/gonic/issues/375#issuecomment-1725814503
