### ISSUE TITLE
Scan DataBase

### ISSUE THREAD

**Issue by coacharnold1** [sentriz/gonic#451]
Sorry to post something that has a lot of discussion already.  I just cannot  figure out how to imploment any of this.

I am running gonic 0.16.2  on Docker in Fedora 39

I think I have sorted out how to add multople collection folders  by adding this to the docker-compose file:

   volumes:
      - ./data:/data # gonic db etc
      - /home/fausto/Music:/music/1:ro # your music
      - /home/fausto/Music2:/music/2:ro # your music
      - /path/to/podcasts:/podcasts # your podcasts
      - /path/to/playlists:/playlists # your playlists
      - /path/to/cache:/cache # transcode / covers / etc cache dir

The syntax is confusing ....  I can't seem to figure out how to test if this is working as I can't get a re-scan to initiate with any of the following:

  sudo docker run sentriz/gonic:full-scan
 sudo docker-compose up -d --full-scan

Some of this may be because I'm running this on docker and not just installing it ..

HOw about log to set up transcoding?  Where does all that reside when tunning in docker 

Are most folks running this localy? Or in Docker?

Thanks for the help

TIm

**Comment by sentriz** [comment]
have access the gonic web interface? that's where you can start a scan and setup transcoding

**Comment by coacharnold1** [comment]
Done
