### ISSUE TITLE
Inccrect return from getAlbum endpoint when requested album id does not exist

### ISSUE THREAD

**Issue by khers** [sentriz/gonic#454]
When I use the getAlbum endpoint and pass it an id that is clearly not present, e.g. "notARealAblumId" I get a error 10 (Required Parameter was Missing) response but should get 70 (Requested data was not found).

gonic version: 0.16.2

if from docker, docker tag: latest
if from source, git tag/branch:

Response from getAlbum with 'id' set to 'notARealAlbumId':
```{'status': 'failed', 'version': '1.15.0', 'type': 'gonic', 'serverVersion': '0.16.2', 'openSubsonic': True, 'error': {'code': 10, 'message': 'please provide an `id` parameter'}}```

**Comment by sentriz** [comment]
what happens if you pass an actual id which doesn't exist like id=ar-133556

**Comment by sentriz** [comment]
fixed, but the id needs to look like a valid gonic id such as al-123
