### ISSUE TITLE
Gonic doesn't handle playcounts properly

### ISSUE THREAD

**Issue by aero31aero** [sentriz/gonic#458]
gonic version: v0.16.2

if from docker, docker tag: latest, deployed yesterday.

Gonic responds with HTTP 200 on /scrobble requests but doesn't actually handle playcounts or returns them when queried later.  Please check the logs at http://support.symfonium.app/t/playcount-sync-not-working-with-gonic/3267/5

This kinda makes it a showstopper re: using Gonic with Symfonium. I was really loving the multi-folder support and the minima configuration system so far. <3 I'm hoping there is an easy fix for this? Maybe something as crude as writing playcounts to the original files as a temp config option, if there's only a single user on the machine?

**Comment by sentriz** [comment]
oh, didn't know there was a playcount in the album response. added

**Comment by sentriz** [comment]
`:nightly` is building [here](https://github.com/sentriz/gonic/actions/runs/7576099546)
