### ISSUE TITLE
FR: Redownload existing podcast episodes

### ISSUE THREAD

**Issue by khers** [sentriz/gonic#461]
Occasionally a podcast will release an episode that they later update (maybe to fix poor audio quality) but if gonic found the initial release we have no way of grabbing the fixed audio. I am not sure if the metadata in the podcast feed was updated (I would think so but do not know the ins and outs of podcast handling so this is speculation) but I would like a way to indicate that a new copy of the episode should be fetched from its source.

gonic version:0.16.2

if from docker, docker tag: latest
if from source, git tag/branch:

**Comment by sentriz** [comment]
did you try use the downloadPodcastEpisode.view, on an already downloaded episode? i think it should refetch the audio

**Comment by khers** [comment]
I will try that this evening and close the request if it works, thanks!

**Comment by khers** [comment]
This does not seem to refetch audio. The broken episode is still present.

**Comment by sentriz** [comment]
can you provide more details/investigation? like links to episode feeds, logs, what you expected/what you got. etc 

also when you have been requesting the audio, has it been transcoding? has the old episode data been cached?
