### ISSUE TITLE
taglib v2 downstream

### ISSUE THREAD

**Issue by vsl-iil** [sentriz/gonic#467]
I'm running Orange Pi OS, which is basically Arch Linux. Following installation guide and trying to build gonic myself using go install I encounter following error:

```log
audiotags.cpp: В функции «TagLib_File* audiotags_file_new(const char*)»:
audiotags.cpp:45:38: ошибка: «create» не является элементом «TagLib::FileRef»
   45 |   TagLib::File *f = TagLib::FileRef::create(filename);
      |                                      ^~~~~~
audiotags.cpp: В функции «int audiotags_audioproperties_length(const TagLib_AudioProperties*)»:
audiotags.cpp:89:40: предупреждение: «virtual int TagLib::AudioProperties::length() const» устарело [-Wdeprecated-declarations]
   89 |   return props(audioProperties)->length();
      |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
In file included from /usr/include/taglib/fileref.h:33,
                 from audiotags.cpp:28:
/usr/include/taglib/audioproperties.h:82:17: замечание: объявлено здесь
   82 |     virtual int length() const;
      |                 ^~~~~~
```

(Basically translates to "In function TagLib_File* audiotags_file_new(const char*) «create» is not an element of «TagLib::FileRef»")

I'm unsure if this error is related to gonic or taglib. I have taglib and the rest of packages installed.

**Comment by sentriz** [comment]
taglib v2 has come out recently which indeed has changed the API. for example on archlinux the taglib package is v2 now so gonic has been updated to support it.

I think you need to wait until your distro ships taglib v2

**Comment by vsl-iil** [comment]
![2024‐02‐10_05](https://github.com/sentriz/gonic/assets/36484938/8363f3b4-4291-4f80-9e4a-bfa2d03ec177)

Pacman says I have version 2.0-1, so I'm not sure if this really is the problem

**Comment by vsl-iil** [comment]
I tried master and it worked! Thanks!

**Comment by Whisprin** [comment]
Thanks @sentriz 
Are you planning to publish a new release with this change on Github soon?
Otherwise it's not picked up by distros including Arch aur which uses the [latest version from Github](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=gonic#n14).

**Comment by sentriz** [comment]
@Whisprin just waiting on Alpine linux next, since all the CI uses that. so I can't release until Alpine upgrades their taglib
