### ISSUE TITLE
Last.fm Artist Lookup not sanitizing special characters in Artist's names

### ISSUE THREAD

**Issue by flkdnt** [sentriz/gonic#472]
gonic version:v0.16.2
if from docker, docker tag:  latest
###

Hello,

I've noticed that the Last.fm Artist lookup will fail(rendering a default image) in the following cases:

1. An en-dash/em-dash in the artist's name, i.e. `Eagle‐Eye Cherry` :

Sent URL(This isn't pasting correcting into Github) : `https://www.last.fm/music/Eagle%E2%80%90Eye+Cherry`  
Correct URL: `https://www.last.fm/music/Eagle-Eye+Cherry`

2. An apostrophe in the artist's name, i.e.  `Destiny’s Child` :

Sent URL(This isn't pasting correcting into Github): `https://www.last.fm/music/+noredirect/Destiny%E2%80%99S+Child`
Correct url: `https://www.last.fm/music/Destiny's+Child` or `https://www.last.fm/music/Destiny%27s+Child`

3. Certain Artists with initials and periods, i.e. `D.J. Jazzy Jeff & The Fresh Prince` :

Sent URL:  `https://www.last.fm/music/+noredirect/D.J.+Jazzy+Jeff+&+the+Fresh+Prince`
Correct URL:  `https://www.last.fm/music/DJ+Jazzy+Jeff+&+The+Fresh+Prince`

4. Certain Artists with Foreign Names, i.e. `Cédric Gervais` : 

Sent URL: `https://www.last.fm/music/C%C3%A9dric+Gervais`
Correct URL: `https://www.last.fm/music/Cedric+Gervais`

**Comment by sentriz** [comment]
hm i definitely dont seem to have this issue. where are you getting the "Sent URL" links that you posted?

![image](https://github.com/sentriz/gonic/assets/6832539/860f74d5-dc4b-45cc-8d98-40eb77cadbce)
![image](https://github.com/sentriz/gonic/assets/6832539/7de094ae-4f0b-436b-930b-05290412981d)
![image](https://github.com/sentriz/gonic/assets/6832539/231e3594-8c51-43b1-aa33-724b795d183f)
![image](https://github.com/sentriz/gonic/assets/6832539/e5b62d51-6141-4aa1-b06a-35caac26dccd)

**Comment by flkdnt** [comment]
Thank you @sentriz!
