### ISSUE TITLE
Search Album by Name doesn't fetch all results

### ISSUE THREAD

**Issue by hak0** [sentriz/gonic#474]
https://github.com/sentriz/gonic/blob/a66463a68c9bca5cebc1a0f32487f8651c0c8c91/server/ctrlsubsonic/handlers_by_tags.go#L269

When searching albums by title, if the result entries exceed 20, the rest entries will be discarded, but no notification or document mentioned this limit. Can we remove this limit so that all the result can be retrieved to the client?

**Comment by sentriz** [comment]
that is checking a query param, with 20 as the fallback. to request more you can search3.view?albumCount=100
