### ISSUE TITLE
Scan

### ISSUE THREAD

**Issue by Beulu** [sentriz/gonic#476]
gonic version: latest

Hi ! Sorry if question was ask before :

Running gonic in docker with compose. Folders are well configured. Got folders (data, cache, audio) but scan doesn't work.

Got access to gonic UI at port 4747

![image](https://github.com/sentriz/gonic/assets/72515988/b4d72b43-3b93-414d-9e7d-84d7b36fbd32)

I now have habit to configure folders with docker/compose. I can't find where is the problem.

**Comment by sentriz** [comment]
can you be more specific? how doesn't the scan work? is there anything in the logs?

**Comment by Beulu** [comment]
How can I have access to logs ?

I just click "scan" go the message in green banner and nothing.

**Comment by sentriz** [comment]
after you clicked scan, did we relaod the gonic page to see the results?

you can view the docker logs with "docker compose logs"

**Comment by Beulu** [comment]
I click on scan and even after a refresh : nothing

here the log :

[_gonic-gonic-1_logs.txt](https://github.com/sentriz/gonic/files/14424941/_gonic-gonic-1_logs.txt)

**Comment by sentriz** [comment]
could you share your docker compose?

**Comment by Beulu** [comment]
sure ! (code balise doesn't work well)

`# example docker-compose.yml

version: "2.4"
services:
  gonic:
    image: sentriz/gonic:latest
    environment:
      - TZ=Europe/Paris
    ports:
      - 4747:80
    volumes:
      - /HDD/System/Data:/data # gonic db etc
      - /HDD/Musique:/musique:ro # your music
      - /HDD/Podcasts:/podcasts:ro # your podcasts
      - /HDD/Radios_internet:/internet_radios:ro # your internet radios
      - /HDD/System/Playlists:/playlists # your playlists
      - /HDD/Cache:/cache # transcode / covers / etc cache dir

    # set the following two sections if you've enabled jukebox
    group_add:
      - audio
    devices:
      - /dev/snd:/dev/snd`

/HDD is for the music hard disk drive on my server. Is well linked in my docker compose (copy/paste from HDD list)

**Comment by Beulu** [comment]
Links to the music files are good, compared with navidrome and it work perfectly

![image](https://github.com/sentriz/gonic/assets/72515988/a223c36c-5d60-417a-8b76-770d4fb972a6)

**Comment by sentriz** [comment]
you have mounted your music into the container as `/musique`, gonic is expecting `/music`. you need to either change the mount to `/music`, or else set `GONIC_MUSIC_PATH=/musique`

**Comment by Beulu** [comment]
It works ! ^^

thank you !

Now I have to found how navidrome can use Gonic database ^^

**Comment by Beulu** [comment]
Does Gonic detects internet radios links files to had them automaticcaly in the list with the name (from title, tags, url balises) ?

![image](https://github.com/sentriz/gonic/assets/72515988/cef93718-134c-4e1b-aa8f-0526b2630baf)

**Comment by Beulu** [comment]
Gonic doenst detect my podcasts files in my podcasts folder. podcasts is well asked in docker compose

- /HDD/Podcasts:/podcasts:ro # your podcasts (no modification)

**Comment by sentriz** [comment]
gonic will not detect internet radio stations or podcasts from your filesystem unfortunately 

this is inherent to the subsonic protocol, where internet radio stations and podcasts have associated users, ratings, favourites, etc - note of which can be deduced from the filesystem. you will need to use a client like airsonic-refix or dsub or whatever else your using to add them to gonic

**Comment by Beulu** [comment]
It's not important, Audiobookshelf can be used for podcasts. ^^


Thanks for your time !
