### ISSUE TITLE
Transcoding device profiles have incorrect DB constraints

### ISSUE THREAD

**Issue by spijet** [sentriz/gonic#48]
At the moment device profiles (the one set in the web UI) are per-user, not server-wide (which is understandable), but DB seems to have a `UNIQUE` constraint on client name:
```
2020/03/24 03:02:40 response  303  for `/admin/create_transcode_pref_do`
gorm error/src/server/ctrladmin/handlers.go:292 UNIQUE constraint failed: transcode_preferences.client, transcode_preferences.profile
```
Maybe it'd be better to check for "user ID and client name" combo instead? This way different users can set different transcoding profiles for same clients.

(I'd rather have a server-wide transcoding profile list, but this might be unacceptable for others, so... :D)

**Comment by sentriz** [comment]
Oops! Yes it's currently client & profile, but should be user & client. Thanks :) 
Am currently in bed but will fix tomorrow

**Comment by spijet** [comment]
Wow, that was fast! :laughing: 
Thank you. :)

**Comment by sentriz** [comment]
updated. since i havent done a proper release since transcoding was added, not gonna bother with a migration. 
if anyone comes across this issue, run these:
```sh
$ (stop gonic)
$ (get the latest gonic)
$ sqlite3 gonic.db "drop table transcode_preferences"
$ sqlite3 gonic.db "delete from migrations where id=202003111222"
$ sqlite3 gonic.db "delete from migrations where id=202003121330"
$ (start gonic)
```
