### ISSUE TITLE
Libraries without folder album art won't get any cover art

### ISSUE THREAD

**Issue by NyaomiDEV** [sentriz/gonic#484]
gonic version: 0.16.3
docker tag: sentriz/gonic:latest

My library relies heavily on embedded album art, and it's so extensive that adding cover jpegs would add up to literal gigabytes - not worth it unless I also remove the embedded cover arts from each and every file (which will be problematic with other music players).

Gonic seems to not like embedded album arts, and it relies on whatever image is in the album directory to provide it.

I think Gonic could scan for all tracks in an album and extract the cover art by itself from the first available track of said album.

I know this allows for "undefined behaviour" in poorly tagged libraries, but I am more than sure that some cover art is better than no cover art, plus this could be a default-off configurable entry.

**Comment by sentriz** [comment]
dupe #11
