### ISSUE TITLE
Mixed case file extension (Mp3) not being picked up in scan

### ISSUE THREAD

**Issue by shadowjig** [sentriz/gonic#491]
I have some mp3s with the file extension of .Mp3.  I see that commit d83fe56 was supposed to address mixed case file extensions. And that commit was in release 0.16.0.  But I had 0.16.0 installed and it was still not picking up the files.  I installed 0.16.4 and it was didn't find the files.  I deleted the database and cache folders and re-ran the scan and it's still not picking up the files with .Mp3 extensions.  If I rename the extension to all lowercase (.mp3) the file is picked up.

gonic version: 0.16.0 and 0.16.4

if from docker, docker tag: sentriz/gonic:latest (I pulled the new image tonight which downloaded 0.16.4 version)

**Comment by sentriz** [comment]
oops, that must have been undone at some point. thanks for reporting
