### ISSUE TITLE
Option to selectively scan music library

### ISSUE THREAD

**Issue by kokonguyen191** [sentriz/gonic#498]
First off, thanks for developing this superb subsonic implementation, it's the best one among all I have tried and I have been using it every day for a few months.

I have one simple question/feature suggestion if it's not already implemented. Is there any option to selectively include (or exclude) which music library/paths to scan? I have a quite massive library (half a million tracks), and I enable `GONIC_SCAN_INTERVAL` (every hour, is it too frequent?) and `GONIC_SCAN_WATCHER_ENABLED`. The majority of the tracks are sorted and stay unchanged for months/years, but a few thousand tracks under this `Unsorted` folder change quite regularly and need to be tracked and automatically updated while the others don't. AFAIK I don't think there seem to be such a feature?

**Comment by sentriz** [comment]
there is already a GONIC_EXCLUDE_PATTERN btw not sure if you've used that

**Comment by kokonguyen191** [comment]
I tried `GONIC_EXCLUDE_PATTERN` but it just outright excluded all the files defined by the patterns. I guess the watcher + one initial scan is what I'm supposed to use and I should disable the periodic full scanner. Thanks for helping!
