### ISSUE TITLE
Better documentation of GONIC_EXCLUDE_PATTERN

### ISSUE THREAD

**Issue by garfieldairlines** [sentriz/gonic#504]
Just a little nitpick, it would be great to add examples to GONIC_EXCLUDE_PATTERN, it took me a while to understand it's regex (just like Airsonic) and even now I'm not really really 100% sure I did it right, would be great to add a little clue in the docs like : 

`GONIC_EXCLUDE_PATTERN="/@eaDir|Artwork|Covers|Scans"`

It's a bit more confusing since GONIC_MUSIC_PATH uses commas to separate folders.

**Comment by sentriz** [comment]
sounds good, pull requests welcome if you fancy updating the readme/wiki 👍
