### ISSUE TITLE
Allow setting user for docker image

### ISSUE THREAD

**Issue by ismay** [sentriz/gonic#506]
For docker containers that place files on the host it's nice to be able to define the user. Currently files that gonic creates are owned by root. Similar to for example how https://www.navidrome.org/docs/installation/docker/ accepts the `user` parameter for their docker images.

**Comment by mstcl** [comment]
I might be wrong but I don't think gonic requires any root privileges while running? Which means you should be able to use the `user` docker directive to control the runtime UID and GID as usual.

I'm able to run gonic with `-u 1000:1000` (for docker run) and `user: 1000:1000` (for docker compose) without any problems. You only have to make sure the database have the right permissions.

**Comment by mstcl** [comment]
Have you checked if the user is the owner or has write permission for both the sqlite file and the directory the file is in?
