### ISSUE TITLE
Improve security regarding CSP headers

### ISSUE THREAD

**Issue by dpertin** [sentriz/gonic#51]
Using the [Mozilla Laboratory addon](https://addons.mozilla.org/fr/firefox/addon/laboratory-by-mozilla/) on Gonic, it generates the following [Content Security Policy](https://developer.mozilla.org/fr/docs/Web/HTTP/CSP) (CSP):
```
default-src 'none'; font-src https://cdn.materialdesignicons.com; form-action 'self'; img-src 'self'; script-src 'unsafe-inline'; style-src 'self' https://cdn.materialdesignicons.com/3.6.95/css/
```

This seems to work well, when used for instance behind `nginx` as a reverse proxy.
However, this policy shows the presence of `unsafe-inline` scripts in Gonic. Using inline JS is a security flaw at the foundation of an XSS attack, which is when an attacker finds a way to inject scripts into the page (more information [here](https://scotthelme.co.uk/content-security-policy-an-introduction/)). 

I found the [related content](
https://github.com/sentriz/gonic/blob/7231b9dee43916bff5a360916833d9ea4c1012dd/server/assets/pages/home.tmpl#L175) in the code. This script should be externalized in a separate `.js` file before we can remove `script-src 'unsafe-inline';` from the CSP.

**Comment by sentriz** [comment]
thanks!
