### ISSUE TITLE
Can’t see playlists. Difference from Subsonic API?

### ISSUE THREAD

**Issue by saysaar** [sentriz/gonic#514]
gonic version:

if from docker, docker tag: latest
if from source, git tag/branch:

Can’t see playlists in iSub client or on browser but can save playlists from client in a subfolder of the playlist folder, which are invisible in client. Subsonic API requires /rest/ping for example. That doesn’t work in browser but /ping works. Are the clients looking for API commands under /rest? In browser /rest/getPlaylists or /getPlaylists both do not work.

**Comment by sentriz** [comment]
try using a subsonic clients "create playlist" feature.

otherwise you need to prefix the playlist dir with the gonic users id. for example admin: playlists/1/example.m3u
