### ISSUE TITLE
Could not read tags

### ISSUE THREAD

**Issue by Artifechs** [sentriz/gonic#523]
if from docker, docker tag: 0e45f5e

This happens on files that I tagged with MusicBrainz Picard, just like the rest of my collection.

2024/06/26 16:42:19 error while scanning: "/music/[...]/[ALBUM NAME]": populate track "[TRACK NAME]": open: cannot process /music/[...]/[ALBUM NAME]/[TRACK NAME]: could not read tags

This file:
[file.ogg.zip](https://github.com/user-attachments/files/15992448/file.ogg.zip)

**Comment by sentriz** [comment]
it works after extracting only the audio track `ffmpeg -i file.ogg -vn out.ogg`

**Comment by sentriz** [comment]
closing since doesnt seem to be a gonic issue (taglib can't read it either) but feel free to ask for more help

**Comment by Artifechs** [comment]
It was downloaded with `yt-dlp`, so that's probably where the issue is. Alright, thanks for the help!
