### ISSUE TITLE
example of m3u8 playlist

### ISSUE THREAD

**Issue by uGeek** [sentriz/gonic#53]
Could you give an example of what the playlist structure would look like in m3u8?. It is a very good option to avoid losing the playlists.

**Comment by sentriz** [comment]
hey an example `my_playlist.m3u8` would be 
```
/path/to/my/music/an_artist/an_album/track_1.mp3
/path/to/my/music/an_artist/an_album/track_2.mp3
/path/to/my/music/an_artist/an_album/track_3.mp3
```
provided you've given gonic a music path of `/path/to/my/music`

**Comment by uGeek** [comment]
and if there are spaces in the text?

/path/to/my/music/an artist/an album/track 1.mp3

I can't make a list...

**Comment by sentriz** [comment]
yes it should work even with spaces in the filenames. are you getting an error message?

**Comment by uGeek** [comment]
It gives me no mistake, it puts me (0 tracks)

**Comment by uGeek** [comment]
I just made a list of a song at the root. The song is called 1.mp3.

Nor does he add it to me.

I have tried

```
/music/1.mp3
/1.mp3
1.mp3
```

It could also make it possible to export the existing lists, in case the server is installed or restarted, import the lists created with the clients

**Comment by sentriz** [comment]
a couple things:

1. did you start a scan before trying the root `1.mp3`?
2. unfortunately for now, tracks in the root must have the "." path, but every normal child path is ok

here's what i did to test this

```shell
# test music dir, in my downloads folder
$ find ~/downloads/music
/home/senan/downloads/music
/home/senan/downloads/music/track in root.flac
/home/senan/downloads/music/a
/home/senan/downloads/music/a/track in dir a.flac

$ sudo docker pull sentriz/gonic:latest
$ sudo docker run -d -p 80:80 -v $HOME/downloads/music:/music sentriz/gonic:latest
# note the "using opts {... MusicPath:/music ....}" that music be the prefix for playlist lines
# now start scan from admin ui

# example playlist
$ cat ~/playlist.m3u8
/music/./track in root.flac
/music/a/track in dir a.flac
```

result
![](https://i.imgur.com/dPDTBhc.png)
![](https://i.imgur.com/gu8h4Wr.png)

**Comment by uGeek** [comment]
Many thanks !!!!! It works perfect!!!!

I have gotten inside docker to run find and I have taken a subdirectory.
Everything has worked perfectly.

Thank you very much for your time and work. It is a great gonic project.

**Comment by sentriz** [comment]
grreat to hear :) thanks!
