### ISSUE TITLE
Question are podcasts included in item counts?

### ISSUE THREAD

**Issue by khers** [sentriz/gonic#534]
gonic version: v0.16.4

if from docker, docker tag: latest
if from source, git tag/branch: NA

I am looking into a mismatch between album and track counts between gonic and a client pointed at my gonic instance. This client does not support podcasts so I do not interact with them via this api. Are podcasters/channels/episodes included in the counts for artists/albums/tracks?

For reference, my client sees 1148 albums but gonic reports 1206 and my client sees  11538 tracks and gonic reports  12254 songs. The differences are not completely explained by podcast channels and episodes but it is pretty close.

**Comment by sentriz** [comment]
more info is required here looks like. where are the two figures coming from? for gonic I presume the admin interface, but what about the other gonic client you mention? where does it get its numbers? 

as far as the admin interface is concerned, no podcast stuff is in there , only music . but I can help with specifics if you have more info on the source of discrepancies 😁

**Comment by khers** [comment]
Thanks, that addresses my question. The numbers are coming from the admin console in Gonic and my installation of Music Assistant which points at that same Gonic install. I had a user complain that the item counts are different in the two locations so I have been looking into it.

Music Assistant shows I have more artists than Gonic but fewer albums and songs. I am not overly concerned about the artist count because I believe that the MA artist count is equal to the union of Gonic Artists and Gonic Album Artists (though I have not confirmed this). I am concerned about the discrepancy between album and song counts but I have not narrowed down which items are missing.

**Comment by sentriz** [comment]
closing since this doesn't seem to be gonic related (or am i mistaken?) either way happy to help with questions on how exactly gonic counts. maybe that's different to the other software
