### ISSUE TITLE
Feature: Sync track star / unstar with last.fm / listenbrainz

### ISSUE THREAD

**Issue by d-rk** [sentriz/gonic#536]
Hey,

currently stars are only stored locally in the db. 
Storing them in last.fm / listenbrainz also would avoid losing the stars if the gonic db has to be re-initialized for some reason.
Additionally, it would help the recommendation system of last.fm / listenbrainz.

**Limitation:**  last.fm / listenbrainz only store stars on track level.

**Implementation:**
* on star/unstar forward the request to  last.fm / listenbrainz if configured.
* a CRON job or button in the UI to trigger syncing all stars from last.fm / listenbrainz to gonic.

If you are interested in such a feature I could come up with a PR for it.

Regards,
Dirk

**Comment by sentriz** [comment]
this is something i wanted too, but it's too niche to be included in the main gonic. so i put it here https://github.com/sentriz/gonic-lastfm-sync :+1:

**Comment by rfporter** [comment]
LMS is doing this already with Listenbrainz. Its a very nice feature.
