### ISSUE TITLE
checking playlist directory: path does not exist, please provide one

### ISSUE THREAD

**Issue by xtay573269555** [sentriz/gonic#539]
checking playlist directory: path does not exist, please provide one

gonic version:
sentriz/gonic:v0.16.4

If not mount a directory to `/playlists` , it will raise a error `checking playlist directory: path does not exist, please provide one`.

[dockerfile volume command](https://github.com/sentriz/gonic/blob/643ffffa0f5eb3fda589b4224305790111bd1265/Dockerfile#L48) need add a directory `/playlists` as following:

```
VOLUME ["/cache", "/data", "/music", "/podcasts", "/playlists"]
```

**Comment by sentriz** [comment]
hi that is intended behaviour since playlists are required for subsonic functionality

**Comment by xtay573269555** [comment]
The directory `/playlists` is referenced by the later env `GONIC_PLAYLISTS_PATH`,  but it(`/playlists`) is not exist in the docker image.

**Comment by sentriz** [comment]
yeah the default expected path exists as an env var, but this forces the user to mount a playlist dir so that they dont lose any data when using the subsonic playlist features later
