### ISSUE TITLE
different Bitrates on WLAN and Mobile

### ISSUE THREAD

**Issue by djusHa** [sentriz/gonic#542]
gonic version: v0.16.4

Hi,

it would be nice to have original bitrate / fileformat when i'm on Wifi and transcoded one if on mobile.
How to achieve this?

**Comment by sentriz** [comment]
hi there , that depends on the client. For example dsub has settings like this. I'd you have a transcode profile setup from the gonic web UI. Then it can transcode to the selected format capped at the bitrate by the client 

![signal-2024-09-29-15-57-38-585](https://github.com/user-attachments/assets/f17b1d48-6ae2-432d-ae24-ff6cdf873544)
