### ISSUE TITLE
Feature request: Zip file support

### ISSUE THREAD

**Issue by voltagex** [sentriz/gonic#552]
I would use the Discussions tab for this if it were enabled.

I've got a lot of zipped Bandcamp releases - I'm wondering how difficult it would be to add zip file support without unpacking the files to disk (except for transcoding I guess)

I will have a bit more of a look at the code to see if I can work out where to add it myself - it's gotta be easier than writing my own server from scratch, right?

**Comment by sentriz** [comment]
probably easier to use some Zip fuse impl like https://github.com/google/mount-zip, then point the scanner at it

**Comment by voltagex** [comment]
I did look at that but there aren't (m)any that will handle multiple zips and I'd be a bi worried about having 400 FUSE filesystems mounted on a single machine

**Comment by sentriz** [comment]
not sure I'd be interested in maintaining such a feature in gonic. since I think the usage would be low. but I extendening an existing fuse project to support multiple zips would be the way to go
