### ISSUE TITLE
Local artist images

### ISSUE THREAD

**Issue by smooveg1** [sentriz/gonic#555]
Hello -- I have artist images stored in a central folder within my music path folder. All of the files have the same naming convention: <musicbrainz_artistid>.<image format, jpg or png>. I was just checking if this image format and folder hierarchy was supported.

**Comment by sentriz** [comment]
dupe https://github.com/sentriz/gonic/issues/548#issuecomment-2490740503

support for local artist images was removed since multi valued tags unfortunately. but the lastfm artist iamges work well and the api key is free

**Comment by smooveg1** [comment]
OK, appreciate the confirmation.
