### ISSUE TITLE
Installation Error - Ubuntu 18.04

### ISSUE THREAD

**Issue by IUCCA** [sentriz/gonic#60]
When installing with go get, the following error occurs:
package syscall/js: unrecognized import path "syscall/js" (import path does not begin with hostname).
As prerequisites I have only installed go-lang

**Comment by sentriz** [comment]
hi! thanks for the report. may I ask what your `$ go version` is?

**Comment by IUCCA** [comment]
My go version is go1.10.4 linux/amd64

**Comment by sentriz** [comment]
ah okay. as of a few days ago, we added subsonic jukebox support which requires a more recent [go version](https://github.com/golang/go/wiki/Ubuntu). however, if you don't fancy upgrating or use jukebox mode, you can install the most recent gonic without jukebox:

`cd $(mktemp -d); go mod init tmp; go get go.senan.xyz/gonic/cmd/gonic@v0.8.5`

in the meantime, we'll be working on making gonic "go getable" for older versions of go

**Comment by sentriz** [comment]
also please do let me know if it works for you

**Comment by IUCCA** [comment]
I installed version 1.14.2, now it runs. For this I had to add the following PPA:
`sudo add-apt-repository ppa:longsleep/golang-backports`

I also configured systemd so that it now runs as a service in the background. For this I moved $HOME/go to /var/gonic/ and created the following /etc/systemd/system/gonic.service:

```
[Unit]
Description=Gonic service
ConditionPathExists=/var/gonic/bin/gonic
After=network.target

[Service]
Type=simple
User=gonic
Group=gonic
LimitNOFILE=1024

Restart=on-failure
RestartSec=10
startLimitIntervalSec=60

WorkingDirectory=/var/gonic/
ExecStart=/var/gonic/bin/gonic -music-path /mnt/storage/media/Music/ -listen-addr 127.0.0.1:4747 --proxy-prefix /gonic -db-path /var/gonic/gonic.db -config-path /var/gonic/.config

# make sure log directory exists and owned by syslog
PermissionsStartOnly=true
ExecStartPre=/bin/mkdir -p /var/log/gonic
ExecStartPre=/bin/chown syslog:adm /var/log/gonic
ExecStartPre=/bin/chmod 755 /var/log/gonic
StandardOutput=syslog
StandardError=syslog
SyslogIdentifier=sleepservice

[Install]
WantedBy=multi-user.target
```

**Comment by sentriz** [comment]
thanks for  the update and the script :) i might add it to a wiki in future if you're ok with it

**Comment by IUCCA** [comment]
I'm writing the instructions, coming up in the next few days
