### ISSUE TITLE
Browsing by folder - Order?

### ISSUE THREAD

**Issue by schui95** [sentriz/gonic#61]
Hello

Great software, thank you! I use gonic with Jamstash or Subfire. My question: Is there an option available to browse the folders in alphabetical order (descending/ascending)? I don't know if this is an issue by gonic anyway.
Thanks for any advice.

schui95

**Comment by sentriz** [comment]
hey thanks for the report. could you give `v0.8.7` a try please?

**Comment by schui95** [comment]
> hey thanks for the report. could you give `v0.8.7` a try please?

There is no change after update to v0.8.7. My folder hierarchy is: Musicfolder/Type of Music/Artist/Albums/Tracks. (e.g. Music/Pop/ABBA/ABBA - The Album (1977) - FLAC/01 - Eagle.flac)

**Comment by sentriz** [comment]
just to confirm we're look at the same things.
i went to "folders" in subfire
![](https://i.imgur.com/TkQCSwu.png)
and also the "artists" view
![](https://i.imgur.com/sbr8Bxh.png)
would you mind showing yours?

**Comment by sentriz** [comment]
oh i see now

**Comment by schui95** [comment]
Yes, for sure. As you can see below, the last level is not sorted.
![image](https://user-images.githubusercontent.com/41399294/80287289-09748580-8731-11ea-95fd-c685b41d9e7f.png)

![image](https://user-images.githubusercontent.com/41399294/80287300-17c2a180-8731-11ea-8754-1e4f6a3739fa.png)

![image](https://user-images.githubusercontent.com/41399294/80287313-2dd06200-8731-11ea-81ae-f77bee1016ce.png)

**Comment by sentriz** [comment]
oops forgot about that endpoint. can you try 0.8.8?

**Comment by schui95** [comment]
> oops forgot about that endpoint. can you try 0.8.8?

Let's try this :) Which endpoint do you mean?

**Comment by sentriz** [comment]
good to hear :)
