### ISSUE TITLE
Force partial scan

### ISSUE THREAD

**Issue by alex-phillips** [sentriz/gonic#64]
I love the ability to force a full scan. Do you think we could implement a force 'partial' scan? Possibly something that takes a directory as an argument? I have a massive library and if I need to force update a single artist / album, a 'force full scan' takes almost 2 hours for me.

**Comment by sentriz** [comment]
2 hrs? wow that's big. how long does the clean stage take may I ask?

**Comment by alex-phillips** [comment]
What do you mean clean stage? You mean a normal scan?

**Comment by sentriz** [comment]
if you check your logs it should say "finished scan in <time>" and "finished clean in <time>"

**Comment by alex-phillips** [comment]
```
2020/04/30 22:58:19 finished scan in 44.522807583s, +575/77359 tracks (0 err)
2020/04/30 22:58:42 finished clean in 22.668578276s, -39 tracks
```

**Comment by sentriz** [comment]
that clean stage should be a lot faster soon. also i've updated the scanners options to take a path. right now it doesnt do anything but i'll keep this in mind
