### ISSUE TITLE
Feature Request: Automatic Re-Scanning

### ISSUE THREAD

**Issue by nstetter** [sentriz/gonic#8]
As far as I can tell scans can only be triggered manually from the webui.

It would be nice to have automatic scheduled scanning. Or even better scanning triggered by file changes in the music dir.

**Comment by sentriz** [comment]
currently at home I have a sort of "event based" scanning system. my music organiser beets.io has a "[subsonic update](https://beets.readthedocs.io/en/stable/plugins/subsonicupdate.html)" plugin. that calls the `/rest/startScan.view`  
or you can do it with curl like `curl "https://gonic/rest/startScan.view?c=curl&v=0&u=<username>&p=<password>"`

but yeah I suppose for people without this it might be a good idea to have scheduled/watched scans

definitely on my todo list to think about this some more :)

**Comment by nstetter** [comment]
Thanks for the tip with curl. I"ll use that for now.

Still having scheduled scans directly integrated would be nice.

**Comment by sentriz** [comment]
howdy. for the meantime I added a `GONIC_SCAN_INTERVAL` or `-scan-interval`. ideally there would be file watching but this will have to do for now 

see the new https://github.com/sentriz/gonic#configuration-options

**Comment by nstetter** [comment]
Thank you very much for this quick fix.

**Comment by vartiovaara** [comment]
@sentriz Hey, any update on file watching?

**Comment by sentriz** [comment]
hey @vartiovaara, yes there's an PR #232
