### ISSUE TITLE
Please support AlbumArt.{png,jpg,jpeg} filenames for cover art

### ISSUE THREAD

**Issue by gnoack** [sentriz/gonic#80]
Hello!

Can you please add support for recognizing AlbumArt.{png,jpg,jpeg} filenames?
These are used by the Android stock music player and/or media frameworks.

Thanks,
Günther

**Comment by sentriz** [comment]
sounds good to me. why did you close the pr? :D

**Comment by sentriz** [comment]
added in v0.9.5 thanks!
