### ISSUE TITLE
Playlist import accepts too few MIME types

### ISSUE THREAD

**Issue by kidfrostbite** [sentriz/gonic#81]
When trying to upload valid playlist m3u8 files from my Mac (running Catalina) the process fails across all browsers with the error:

> invalid content-type "audio/mpegurl"

I can see the code is accepting only audio/x-mpegurl and application/octet-stream as MIME types, but so far in my testing Safari, Firefox, Chrome and Qutebrowser all submit as audio/mpegurl.

**Comment by sentriz** [comment]
(hopefully) fixed in v0.9.6, thanks!

**Comment by kidfrostbite** [comment]
Excellent! Really digging the project, thanks!

**Comment by sentriz** [comment]
Thank you :)
