### ISSUE TITLE
File names not being displayed on clients

### ISSUE THREAD

**Issue by gkosae** [sentriz/gonic#84]
I'm running gonic using docker and I've been able to connect to the server with Subsonic for Android and Subfire chrome extension.
Folder names are being displayed by both clients but file names aren't.
Aside from that everything else seems to be working OK.

Was it a design decision not to display file names or am I doing something wrong?

Thanks in advance

**Comment by sentriz** [comment]
interesting. I've not experienced this issue (using DSub for android) but ill check it out this evening

**Comment by sentriz** [comment]
wasn't able to reproduce it, but I think this can happen if your tracks don't have titles in their tags. could you give `v0.10.1` a try please? thanks!

**Comment by gkosae** [comment]
Ok. Will do

**Comment by gkosae** [comment]
That last commit, 373f5a2ccaff58bc30eac61b761f7f25a9a83882, seems to have fixed the issue.

Thanks!

**Comment by sentriz** [comment]
Very nice :D thanks for the report

**Comment by sentriz** [comment]
btw, if you were having issues with weird cover sizes in Subsonic for Android, it should be fixed after #87 :sunglasses:
