### ISSUE TITLE
Scanning songs

### ISSUE THREAD

**Issue by TheUltimateC0der** [sentriz/gonic#88]
My setup is that I have a server that has about 1TB storage. The songs are available on the local storage for initial scanning, and after a certain limit is reached, they get uploaded to a cloud storage which is mounted by using rclone. So after they are uploaded to the cloud storage, it would be less than ideal when they are scanned again.

I noticed gonic not responding while scanning my library which I guess is caused by the "high latency" that rclone creates when accessing (and therefore downloading) the files which get scanned again.

I would recommend implementing a switch that ignores already existing files when rescanning.

**Comment by sentriz** [comment]
hey, the scanner already tries to be smart about not rescanning already scanned files. but at a minumum it needs to stat the file to get the updated at timestamp. also there we some performance improvements on master recently. perhaps it's better now?
