### ISSUE TITLE
Support for multiple albums in one folder

### ISSUE THREAD

**Issue by Thor77** [sentriz/gonic#89]
In some cases, I store music files from different albums in one folder.
It looks like that structure is not really usable with gonic, because it just deletes songs which don't have the same artist as the album associated with the folder they're in (at least that what the behaviour of `Scanner.cleanArtists` looks like to me).
Additionally gonic will only pick up the album tag of one of the files in the folder, which is also very.. unfortunate for my usecase.

Is there a reason it is implemented this way? Are there plans to change it/would you accept a PR doing that?

**Comment by sentriz** [comment]
hey sorry gonic isn't working out for you. 

i made this decision as compromise to make both the subsonic tags and folders APIs do-able. it also solves an issue where an artist has [multiple albums with the same name](https://en.wikipedia.org/wiki/American_Football_(band)#Discography). where the only real way to distinguish them (without looking different combinations of tags) is by folder

**Comment by raffomania** [comment]
could we document the folder structure gonic expects in the README? I've just found this after wondering why gonic doesn't work with my playlist folders :D

**Comment by icyphox** [comment]
ah, that would explain why 90% of my music isn't getting scanned! it's all like this (a lot of mp3s in the same folder):
![image](https://user-images.githubusercontent.com/17672379/101900318-482e5180-3bd5-11eb-9b75-a288dea78738.png)

agree with @raffomania, perhaps documenting what folder structure is expected would be great.

**Comment by sentriz** [comment]
added a section to the readme :+1: 
https://github.com/sentriz/gonic#directory-structure

**Comment by balthild** [comment]
Hello! I have a question: where should I put those musics without albums?

**Comment by sentriz** [comment]
@balthild you cab just put then in any folder on the filesystem

**Comment by sonbill** [comment]
Hello, i just start running gonic, i scanned and got 1 track, how i can play this track on web? or this is for backend API, thanks

**Comment by sentriz** [comment]
@sonbill you need a subsonic client such as one of these [airsonic-refix](https://github.com/tamland/airsonic-refix), [symfonium](https://symfonium.app), [dsub](https://f-droid.org/en/packages/github.daneren2005.dsub/), [jamstash](http://jamstash.com/), [subsonic.el](https://git.sr.ht/~amk/subsonic.el), [sublime music](https://github.com/sublime-music/sublime-music), [soundwaves](https://apps.apple.com/us/app/soundwaves/id736139596), [stmp](https://github.com/wildeyedskies/stmp), [termsonic](https://git.sixfoisneuf.fr/termsonic/), [strawberry](https://www.strawberrymusicplayer.org/), and [ultrasonic](https://gitlab.com/ultrasonic/ultrasonic)

**Comment by xxxserxxx** [comment]
> you cab just put then in any folder on the filesystem

@sentriz not any more, apparently. Sonic is ignoring top-level songs since some recent version. A minimum test is:

```
$ mkdir -p tmp/songs tmp/playlists tmp/podcasts tmp/cache
$ cp some-song.mp3 tmp/songs/
$ go run ./cmd/gonic -listen-addr :9324 \
   -db-path ./tmp/gonic.db -music-path tmp/songs \
   -playlists-path tmp/playlists -cache-path ./tmp/cache -podcast-path tmp/podcasts \
   -scan-at-start-enabled
^c
$ sqlite3 tmp/gonic.db 'select count(*) from tracks;' | xargs echo
0
```

Now, create an arbitrary subdirectory and copy the file into it:

```
mkdir tmp/a
cp some-song.mp3 tmp/songs/a/
go run ./cmd/gonic -listen-addr :9324 \
   -db-path ./tmp/gonic.db -music-path tmp/songs \
   -playlists-path tmp/playlists -cache-path ./tmp/cache -podcast-path tmp/podcasts \
   -scan-at-start-enabled
^c
sqlite3 tmp/gonic.db 'select count(*) from tracks;' | xargs echo
1
```

This is new behavior, but I don't know when it was introduced -- I only noticed it last week. I haven't tried to bisect it yet.

There's no reason why music files at the top level should be ignored, is there?
