### ISSUE TITLE
Feature request: playlist support

### ISSUE THREAD

**Issue by alex-phillips** [sentriz/gonic#9]
Also ability to import via M3U8 files would be amazing.

**Comment by sentriz** [comment]
howdy alex. would this be related to subsonic playlists? like the ability to create them, add songs, listen to them via the clients, and also import existing playlist files?

or maybe something to do with scanning the filessystem, at the stage where your tracks are scanned?

**Comment by alex-phillips** [comment]
Related to subsonic playlists. i.e., in dsub, you can create / alter playlists in the app, but the server needs to support it.

**Comment by sentriz** [comment]
yep that's definitely a feature I would like to support soon

**Comment by alex-phillips** [comment]
Great! I look forward to it. Great work so far! This is working wonderfully.

**Comment by sentriz** [comment]
thank you very much :)

**Comment by sentriz** [comment]
hi 
I nearly have playlists implemented now. from dsub i seem to be able to create, update, delete, etc. could you provide some example playlists for the import feature? thanks !

**Comment by alex-phillips** [comment]
Awesome! And sure. I believe it just uses the standard m3u8 format for playlists which is just a list of file locations.

Here's one playlist I've imported into my current server setup: https://hastebin.com/selidupizu.sql

I can provide more if necessary, but they're all just a list of absolute file locations. Being able to set a playlists folder in the server would be awesome and it just reads / imports them on a library scan. The playlist created will be named whatever the file is. If it already exists, it overwrites the current playlist contents I believe.

**Comment by sentriz** [comment]
cool that's what I was thinking. one thing though, if the server were to check a playlists folder, how does it determine which user owns each playlist? 

something which might be a little easier is an "upload playlist" section on the web interface. where a user logs in, clicks this button, then selects all their playlist files. then they appear just for them in dsub/whatever client, etc.

not sure if that's the norm though

**Comment by sentriz** [comment]
hey can you try out the latest release when you can?
normal subsonic playlist create/update/delete should (hopefully) be working, and also for the meantime there's a thing that lets you upload in the web interface

**Comment by alex-phillips** [comment]
Great! I'll check it out now.

And good point about the playlists import. I'm not sure how sub/airsonic handles it now. I guess it's a global playlist? Not sure. But I think an upload via the interface would be fine. Could this be done with a cURL request? (I keep a couple players in sync with playlists via a cronjob).

**Comment by alex-phillips** [comment]
@sentriz this is working great! Uploading as well as creating / adding / deleting via the API (using dsub for testing). Great work!

**Comment by sentriz** [comment]
good to hear alex :) please let me know if you find problems with it. closing for now

**Comment by sentriz** [comment]
also for the curl thing. 
it should be possible. but you might need to make two requests to get the cookie for the admin page.
```
curl -c /tmp/cookie -X POST --data "username=<username>" --data "password=<password>" http://my.gonic/admin/login_do
curl -c /tmp/cookie -X POST -F playlist-files=@playlist_one.m3u8 -F playlist-files=@playlist_two.m3u8 http://my.gonic/admin/playlist_upload_do
```

but I haven't testing that I'm afraid

**Comment by dbogdanov** [comment]
Does it work? I am trying to use curl with
```
curl -c /tmp/cookie -X POST --data "username=<username>" --data "password=<password>" http://my.gonic/admin/login_do
curl -c /tmp/cookie -X POST -F playlist-files=@playlist_one.m3u8 -F playlist-files=@playlist_two.m3u8 http://my.gonic/admin/upload_playlist_do
```
but I am getting 
```
response  303  for `/admin/upload_playlist_do`
```
and no playlist is being added.

**Comment by sentriz** [comment]
@dbogdanov perhaps try this instead

```shell
$ curl -v -L -c /tmp/cookie -b /tmp/cookie -X POST --data "username=<username>" --data "password=<password>" https://gonic.senan.xyz/admin/login_do
$ curl -v -L -c /tmp/cookie -b /tmp/cookie -X POST -F playlist-files=@fai.au https://gonic.senan.xyz/admin/upload_playlist_do
```

the first command includes `-L` to follow redirects, so can check the output HTML for error messages like wrong username. 
it also adds a second cookie flag `-c /tmp/cookie -b /tmp/cookie`

**Comment by sentriz** [comment]
@dbogdanov perhaps try this instead

```shell
$ curl -v -L -c /tmp/cookie -b /tmp/cookie -X POST --data "username=<username>" --data "password=<password>" https://my.gonic/admin/login_do
$ curl -v -L -c /tmp/cookie -b /tmp/cookie -X POST -F playlist-files=@playlist_one.m3u8 https://my.gonic/admin/upload_playlist_do
```

the first command includes `-L` to follow redirects, so can check the output HTML for error messages like wrong username. 
it also adds a second cookie flag `-c /tmp/cookie -b /tmp/cookie`

**Comment by dbogdanov** [comment]
Thank you, @sentriz, this helped a lot. Everything works.
