### ISSUE TITLE
Respect maxBitRate

### ISSUE THREAD

**Issue by fijam** [sentriz/gonic#91]
Subsonic 1.2 API introduced maxBitRate as part of the stream method:

> If specified, the server will attempt to limit the bitrate to this value, in kilobits per second. If set to zero, no limit is imposed.

Currently it seems to be ignored:

```
2020/09/18 02:00:39 response  200  for `/rest/stream.view?id=tr-123&maxBitRate=256&u=admin&c=Ultrasonic&f=json&v=1.15.0
2020/09/18 02:00:44 serving raw "01 Minority.flac"
```

Perhaps it could be tied into making transcoding more adaptive depending on what the client requests (currently mp3 is hardcoded to 128kbps and opus to 96kbps)

**Comment by sentriz** [comment]
Hey it should be respected. Have you set up transcoding preferences in the web UI?

**Comment by fijam** [comment]
Hi,

I should clarify - currently when transcoding is enabled all files will be transcoded regardless of what maxBitRate the client requests.

For example, here I made a 128kbps mp3 file. With transcoding enabled, gonic will transcode it *again* to 128kbps mp3.

```
2020/09/18 09:23:28 serving transcode `128-test.mp3`: cache [mp3/128k] miss!
2020/09/18 09:23:45 response  200  for `/rest/stream.view?id=tr-1989&maxBitRate=256&u=admin&c=Ultrasonic&f=json&v=1.15.0&t=9a63bf9906b98ad5ed00524a42b2fe97&s=3kkli0e1bh4g7auv8pfq07dnnl
```

Ideally, you could have the client request for example `maxBitRate=224`, and gonic would only transcode files which have a higher bitrate (such as FLACs or large mp3s). 

Alternatively, if this is hard to implement, perhaps there could be a server-side option to only transcode FLACs.

**Comment by fijam** [comment]
>  currently when transcoding is enabled all files will be transcoded regardless of what maxBitRate the client requests.

This wasn't quite right. The condition is 
```
if preferred != 0 && preferred < defined {
		return preferred
```

so it would trigger only if client was requesting an mp3 file _smaller_ than 128k which I never tried. 

Instead, I would like to give more weight to what the client wants, see PR https://github.com/sentriz/gonic/pull/93

**Comment by fijam** [comment]
Thanks!
