### ISSUE TITLE
Folder names reported as album names

### ISSUE THREAD

**Issue by kdmn2** [sentriz/gonic#94]
Hello there,
I love the app and I can't wait to drop airsonic for it, but I've noticed one small issue.
It appears that gonic reports folder names as album names when playing songs. I've checked that both on jamstash and play:Sub.
If the album in the folder "Artist_(1998)_AlbumName123" songs from it will show up as not being from "Album123" album, but instead from "Artist_(1998)_AlbumName123". Apologies for maybe slightly convoluted way of expressing myself, but I hope you know what I mean.
My files are properly tagged (FLAC with Vorbis tags, MP3's with ID3v2.4@utf8.
Please let me know if you need more info or examples, thanks!

**Comment by sentriz** [comment]
hey there. gonic supports two modes of browsing as specified by the subsonic api spec. they are "browse by tags" and "browse by folder" 

for gonic of album titles is: 
browse by tags -> use the id3 album name
browse by folder -> use the name of the folder

when I last used jamstash I think it only supports the browse by folder mode. (hence you see your folder names)
im also not sure what play:Sub does but there might be a setting in it for browse by tags?
