### ISSUE TITLE
Jamstash asking for podcasts

### ISSUE THREAD

**Issue by trashhalo** [sentriz/gonic#98]
Jamstash is listed on the site as working but its not working for me. When I connect it to my gonic server it makes this call:

https://xxx/rest/getPodcasts.view?c=Jamstash&callback=angular.callbacks._e&f=jsonp&includeEpisodes=false&p=xxx&u=xxx&v=1.6.0

the key part being "getPodcasts" which is unimplemented on gonic so it gives up.

**Comment by sentriz** [comment]
strange, i don't remember that being a problem in the past. but ive added a dummy getPodcasts.view now. jamstash is working for me

**Comment by trashhalo** [comment]
Confirmed it works now after docker pulling. Thank you!

On January 3, 2021, GitHub <notifications@github.com> wrote:
> Closed #98 <https://github.com/sentriz/gonic/issues/98> via 3a71358
> <https://github.com/sentriz/gonic/commit/3a71358df696d803b12ac97b03fe36a35c2c5913>.
>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/sentriz/gonic/issues/98#event-4162684575>, or
unsubscribe <https://github.com/notifications/unsubscribe-
auth/AABLKU6KXCLK75KHD6ZPGULSYCX4FANCNFSM4TT7MVSA>.
